### ISSUE TITLE
Мили урон(белые атаки) не сбивает любой контроль

### ISSUE THREAD

**Issue by nochnikk** [wowmw/bugtracker#102]
На видео видно, как "белые атаки" не снимают сап и блайнд, а так-же полиморф, фир и т.д... Тут даже и пруфы не нужны, все и так прекрасно знают, что подобный контроль снимается любым уроном.
Баг нашли:
Nochnik
Invisibility
https://user-images.githubusercontent.com/77924580/105631958-2cc49080-5e7b-11eb-8e1f-6e7c1a626261.mp4

**Comment by Gensen1** [comment]
Баг появился пару дней назад после экспериментального обновления. Исправлено, закрыто.
