### ISSUE TITLE
Баг с Invisibility

### ISSUE THREAD

**Issue by nochnikk** [wowmw/bugtracker#103]
Баг с инвизом, можно уйти в инвиз получая урон от автоатак или от урона мобов, только спеллы сбивают, должен выбивать любой урон.
Пруф:
https://wow.gamepedia.com/Invisibility#:~:text=Invisibility%20is%20a%20level%2034,an%20ability%20to%20skip%20content.&text=Turns%20you%20invisible%20over%203,you%20are%20untargetable%20by%20enemies.
`Patch 2.1.0 (2007-05-22): Invisibility's tooltip has been updated to reflect that any action will cancel the Invisibility effect.`
Баг нашли:
Nochnik
Invisibility

https://user-images.githubusercontent.com/77924580/105633885-64383a80-5e85-11eb-838e-9b428689dccc.mp4

**Comment by Gensen1** [comment]
Баг появился пару дней назад после экспериментального обновления. Исправлено, закрыто.
