### ISSUE TITLE
"Сущность ястреба" Задание из цепочки на стремительную птицу друида

### ISSUE THREAD

**Issue by alhemist** [wowmw/bugtracker#104]
При прохождении цепочки квестов на стремительную птицу друида, вы с помощью "Манок пустельги Арторн" ( https://ru.wowhead.com/item=32657/ ) вызываете прицу, которой сдаете предыдущее задание и берете новое. Задание "Сущность ястреба" (  https://ru.wowhead.com/quest=10992 ) не был принят, при том в инвентаре пропал "Манок пустельги Арторн" ( https://ru.wowhead.com/item=32657/ ) у которой берется это задание и вся цепочка провалилась.
Повторно вернувшись перепройти задание не получается, т.к. NPC начинающий эту цепочку, уже не выдает заданий. получается вся цепочка провалена, в игре нет возможности выполнить финальный квест цепочки.
Помогите выполнить квест
Сервер x100
Персонаж Alhemist

**Comment by Dmitriyres** [comment]
> При прохождении цепочки квестов на стремительную птицу друида, вы с помощью "Манок пустельги Арторн" ( https://ru.wowhead.com/item=32657/ ) вызываете прицу, которой сдаете предыдущее задание и берете новое. Задание "Сущность ястреба" ( https://ru.wowhead.com/quest=10992 ) не был принят, при том в инвентаре пропал "Манок пустельги Арторн" ( https://ru.wowhead.com/item=32657/ ) у которой берется это задание и вся цепочка провалилась. Повторно вернувшись перепройти задание не получается, т.к. NPC начинающий эту цепочку, уже не выдает заданий. получается вся цепочка провалена, в игре нет возможности выполнить финальный квест цепочки. Помогите выполнить квест Сервер x100 Персонаж Alhemist

 Добрый день . Проверил работает коректно . Вероятно прошёл сбой в заданиях. Обратитесь к Администрации для помощи. Напишите тикет.
