### ISSUE TITLE
Жизнецвет ( Lifebloom ) друидов

### ISSUE THREAD

**Issue by ariand2020** [wowmw/bugtracker#105]
При снятии с себя правой кнопкой мышки спел  [http://ru.wowhead.com/spell=33763](Жизнецвет) - он должен давать финальный хил. Отсутствует в этом случае.

**Comment by Gensen1** [comment]
Нужны пруфы

**Comment by ariand2020** [comment]
> Нужны пруфы

https://www.youtube.com/watch?v=wFYUzm-b6qo&feature=youtu.be

**Comment by Gensen1** [comment]
Пруфы того, что спелл должен работать именно так, как вы описали.

**Comment by ariand2020** [comment]
> Пруфы того, что спелл должен работать именно так, как вы описали.
https://db.moonwell.ws/?spell=33763

`Исцеление цели на 273 ед. в течение 7 сек. Когда срок действия заклинания "Жизнецвет" заканчивается или эффект **### снимается**, цель мгновенно исцеляется на 600 ед. Эффект может суммироваться до 3 раз на одной цели.`

Аура
| Жизнецвет | Магия | 
```
Восстановление 39 ед. здоровья в секунду и 600 ед. здоровья, когда эффект **заканчивается** или рассеивается.
Срок действия: 7 сек
```
-- | -- | -- | --

**_Снимается_**, а сниматься спел может как от рассеивания (что работает), так и от снятия вручную друидом с помощью ПКМ. Я на это обратил внимание, потому что когда играл на 2.3.3 версии еще очень давно - Жизнецвет именно так и работал.

**Comment by Gensen1** [comment]
Из английского описания:

Heals the target for 273 over 7 sec. When Lifebloom completes its duration or is dispelled, the target instantly heals themself for 600. This effect can stack up to 3 times on the same target.

Ничего про "снятие мышкой" не говорится. Русский перевод имеет много ошибок и неточностей.
