### ISSUE TITLE
Баг текстуры на Ущелье Песни Войны (ВСГ)

### ISSUE THREAD

**Issue by cladonosets** [wowmw/bugtracker#110]
Был на Бг ущелье песни войны,играл магом и тем самым сделал Spell blink и в результате оказался на верху какой то палки (на скриншоте все видно) где можно стоять с флагом тем самым не давать противнику победить на ущелье песни войны.
https://imgur.com/iQBETux

**Comment by Gensen1** [comment]
Это глобальные баги с текстурами. В целом все с ними хорошо, но чтобы сделать идеально, нужно проделать огромный объем работы. Когда-нибудь займемся.
