### ISSUE TITLE
Omen of Clarity doesn't work with Ferocious Bite

### ISSUE THREAD

**Issue by Shadess2** [wowmw/bugtracker#112]
When getting the Omen of Clarity Buff (https://tbc-twinhead.twinstar.cz/?spell=16864) and u wanna do the Finisher Ferocious Bite Rank 6 (https://tbc-twinhead.twinstar.cz/?spell=24248) it shouldn't delete all Energy you got. With Omen of Clarity you should have a spell without needing Energy.

Thanks a lot, Gensen!
Shadess

**Comment by Gensen1** [comment]
"and converts each extra point of energy into 4.1 additional damage" I guess it has more priority than Clearcasting state. I need proof that it should not drain energy.
