### ISSUE TITLE
Праведное неистовство

### ISSUE THREAD

**Issue by sheriff1981** [wowmw/bugtracker#116]
Играя паладином танком заметил, что игроки часто срывают с меня агро.
На манекене в процессе тестов выяснил причину.
Праведное неистовство не работает -  нет увеличения трита.
Прошу исправить.

**Comment by Gensen1** [comment]
"Правосудие" от "Печать праведности" по манекену 
без "Праведное неистовство" - 660 урона - 660 трита
с "Праведное неистовство" - 654 - 1046 трита (+60%)

Всё работает правильно. Приводите свои доказательства, если считаете иначе.
