### ISSUE TITLE
Сделайте наконец пожалуйста

### ISSUE THREAD

**Issue by astabi1** [wowmw/bugtracker#117]
Добрый день, у меня проблема купил специально оружие для хорошего урона под названием Миродробитель , ТК на нём есть прок дать на 4 секунды 900 критического урона ,но уже неделю почти хожу с ним ни разу он не сработал, почините эту пушку она должна срабатывать при чем часто https://db.moonwell.ws/?item=30090

**Comment by Gensen1** [comment]
Работает.
