### ISSUE TITLE
Ритуал призывания

### ISSUE THREAD

**Issue by Bleiriam** [wowmw/bugtracker#124]
При активации заклинания "Ритуал призывания" тот что вызывает маунт https://db.moonwell.su/?item=12440 Поводья льва.
На панели заклинаний у чернокнижника светится каст "Ритуал призывания"  https://ru.tbc.wowhead.com/spell=698/%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2-%D0%BA%D0%B0%D0%BC%D0%BD%D1%8F-%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87 для призыва игроков.... в итоге 2 каста с призывания маунта и игрока светятся.....

**Comment by Gensen1** [comment]
Такая реализация кастомного спелла. Не вижу никакой проблемы в этом.
