### ISSUE TITLE
Mob Agro Distance

### ISSUE THREAD

**Issue by Whackeroo** [wowmw/bugtracker#126]
Mob agro distance is ridiculous all over the world and in some instances such as Sethekk Halls
It needs to be reduced by at least 5 yards.

**Comment by Gensen1** [comment]
Aggro radius changed from 50 to 45 (mangos default).

**Comment by Ghostivan** [comment]
I would like to comment this issue.

Is it possible to put a dynamic range aggro depending on our level and how monsters can see us.

For example : 
- If the mob is 💀 => Range 50
- If the mob is 🔴 => Range 45
- If the mob is 🟠 => Range 40
- If the mob is 🟡  => Range 35
- If the mob is 🟢  => Range 30
- If the mob is Grey => Range 20

Something like the current mechanics blizlike

@Gensen1
