### ISSUE TITLE
Cannot solo Mana Tombs

### ISSUE THREAD

**Issue by LordPalandus** [wowmw/bugtracker#138]
The second boss has an ability that deals 10% of maximum health, per second, for 4 seconds. It casts it at least 3 times during the fight, making it impossible to defeat solo. It does this on both normal and heroic mode. 

Playing a prot warrior, with half epics and half blues. I need to kill the second boss on Heroic, to get my tanking shield. Otherwise, the only other epic tanking shield I know of, is the one from isle of queldanas at exalted from the quartermaster.

**Comment by Gensen1** [comment]
Made it easier.
