### ISSUE TITLE
Low Drop Rate of Moon Coins

### ISSUE THREAD

**Issue by LordPalandus** [wowmw/bugtracker#142]
So I and a group of others did a raid of Karazhan. Each boss had a chance to drop a single moon coin, but wasn't guaranteed. Considering that it costs like 15 MCs to acquire a key to unlock a chest, and you cannot acquire keys in random loot, it is really hard to acquire sufficient MCs to be able to purchase keys. And as everyone is fighting over who gets the single moon coin that drops... I don't know if this is a bug or a feature, but reporting it anyway.

In that raid, I won a rare chest and an epic chest, and a ghost chest, and one MC. Going to be a long time before I can open up those chests at this rate. Maybe if those MCs dropped off the elites in Karazhan as well, then you might be able to win 3-4 each raid... which still isn't great but its better than 3-4 dropping period.

**Comment by Gensen1** [comment]
It's normal. Key costs more than chests. If you want to farm Moon Coins go to heroic raids.
