### ISSUE TITLE
ТП соствляющая шадоустепа нерабoтает.

### ISSUE THREAD

**Issue by ThriveMNWL** [wowmw/bugtracker#145]
ТП соствляющая шадоустепа нерабатает. Я об это говорил уже давно но ничего не меняется.
Просто шс тпшит в нижнюю точку за таргетом, а не за спину. На арене постоянно тпшит на низ если таргет стоит на уступе....

Какак работает сейчаc:
https://drive.google.com/file/d/1R0AgjFKH_BMirRjsIv7CEgBERGMSgjOm/view?usp=sharing
https://drive.google.com/file/d/1c3fF6NTq3Xu0bMWXorBHJnoRpG-DX9Xt/view?usp=sharing

Должно:
ТП за спину в случаях если за целью есть место, если нет места - тп должно быть в таргет.

Пруфы:
https://www.youtube.com/watch?v=5Jw-PGsJKo0
https://www.youtube.com/watch?v=UhZfFo5zq_k

https://www.wowhead.com/spell=36554/shadowstep#comments:id=36292
https://www.wowhead.com/spell=36554/shadowstep#comments:id=264278

**Comment by Gensen1** [comment]
Нужно писать в багтрекер - тогда будет меняться :)

Будет исправлено в следующем обновлении.
