### ISSUE TITLE
Noted Issues of Golem Companion

### ISSUE THREAD

**Issue by LordPalandus** [wowmw/bugtracker#149]
These are all the issues I've seen with the new Golem companion. Overall really useful to have and thanks for adding it. I'll keep this list updated, as I find them / they get fixed. 

Issues:

-> Really great for a Protection Warrior but my Beastmaster Hunter finds them highly unreliable. 
-> Golems don't heal your pets, and so my Beastmaster Hunter has to Mend it... which draws agro to him and he is quite squishy. 
-> The Golem has a lot of issues with The Mechanar dungeon. It cannot ride the lift, and when it is on the "light bridge", it constantly agros fresh enemies, and so it is one long fight on the bridge. 
-> The Golem won't accompany you to Vanilla WoW dungeons/raids, if I had wanted to solo them. Can be useful to do so as specific nice enchantments and potion recipes drop in them, that are still relevant for Burning Crusade. ie Fiery Weapon in Blackrock Depths is still a powerful and useful enchantment. 
-> The Golem gets confused when Grand Warlock (in Shattered Halls), begins his constant whirlwind. It doesn't attack, doesn't heal, and just stands right on the guy whirling around. I nearly died, as you have to attack him from range (when he is at this stage), and as a warrior, that wasn't going to work too well. 
-> The Golem will shut down mid-boss battle, if the boss has over 80k hp. So, bosses in Shattered Halls, Shadow Labyrinth, and The Mechanar, will cause it to go to sleep, due to sheer HP. Thankfully, as a prot warrior, I can usually tank the hits while I wait for the Golem to reactivate, but most users will get killed off, once the heals run out. 
-> If you get mutated (a form of polymorph; The Botanica), all enemies will attack the Golem. Not sure they damage it though. 
-> CRITICAL = Magister's Terrace has no golem companion. It is currently not soloable. 
-> CRITICAL = Unless you are an extremely well geared DPS (which at that point, you probably wouldn't be doing Shattered Halls), Shattered Halls is not soloable. The 2nd boss has enough health, that it will go to sleep mid-fight, and without heals, that boss will kill anyone that isn't a protection warrior. Tried on my Hunter and a Fury Warrior (with some 70 epics, and two Karazhan epic weapons).

**Comment by Gensen1** [comment]
The Golem has a lot of issues with The Mechanar dungeon
- and other pets too/ Global problem.

The 2nd boss has enough health, that it will go to sleep mid-fight, and without heals
- Golem action limit was doubled at last update.

Magister's Terrace has no golem companion. It is currently not soloable.
- it's not solo instance.

At next update:
1. Golem will heal pets.
2. Grand Warlock will chase character at whirlwind state, so it will fix golem confused state too.

**Comment by LordPalandus** [comment]
Fair enough. I haven't tried it with the Hunter, so didn't know.

Well, this was written before the update was released, so this should address the problem... in theory. I'll test it out to see if it actually makes it possible for my Hunter to solo dungeons or not. 

Magister's Terrace is a 5 person dungeon; it was at least in TBC. If memory serves it was at the time about as difficult as Shattered Halls or Shadow Labyrinth. You might be confusing this dungeon with the Sunwell Terrace (SWT), which is a raid dungeon.

**Comment by Gensen1** [comment]
Magister's Terrace is the one actually for 5 players, all other 5ppl-dungeons made for solo.

**Comment by Gensen1** [comment]
Well, I thought about it and decided to do MGT solo dungeon as the other.

**Comment by LordPalandus** [comment]
Ok. 

The extended limit of actions is helpful, but I do find that the golem has a tendency to agro more enemies, instead of healing me, when a battle is over with. Sometimes this results in me wiping, as I'm already at half health and the golem might already be close to its action limit when it decides to attract more to me.

**Comment by LordPalandus** [comment]
Tried out MGT on heroic:

1. Bosses do not drop Badge of Hero
2. Bosses do not drop Chests
3. Bosses rarely drop Epic Gems

Otherwise they function normally.
