### ISSUE TITLE
Талант мага\Talent mage

### ISSUE THREAD

**Issue by Alitros** [wowmw/bugtracker#152]
Талант
https://ru.tbc.wowhead.com/spell=11426/%D0%BB%D0%B5%D0%B4%D1%8F%D0%BD%D0%B0%D1%8F-%D0%BF%D1%80%D0%B5%D0%B3%D1%80%D0%B0%D0%B4%D0%B0
Во время действия способности Ледяной барьер, при повторном использовании способности, таймер не обновляется и способность переходит на перезарядку.
|
|
Talent
https://tbc.wowhead.com/spell=11426/ice-barrier
During the action of the Ice Barrier ability, when using the ability again, the timer is not updated and the ability goes to recharge.

**Comment by Gensen1** [comment]
Должно быть исправлено в обновлении #62
