### ISSUE TITLE
Заклинание мага\magician's abilit

### ISSUE THREAD

**Issue by Alitros** [wowmw/bugtracker#153]
Способность
https://ru.tbc.wowhead.com/spell=10219/%D0%BB%D0%B5%D0%B4%D1%8F%D0%BD%D0%BE%D0%B9-%D0%B4%D0%BE%D1%81%D0%BF%D0%B5%D1%85
Не снижает скорость передвижение и интервал между атаками.
|
|
The spell
https://tbc.wowhead.com/spell=10219/ice-armor
Does not reduce the speed of movement and the interval between attacks.

**Comment by Gensen1** [comment]
Должно быть исправлено в обновлении #62
