### ISSUE TITLE
Bug with Fishing skill

### ISSUE THREAD

**Issue by LordPalandus** [wowmw/bugtracker#156]
It is true that most players probably won't bother with fishing, but it does give access to a bunch of nice cooked meal buffs.

Anyway, any bonuses on your fishing skill, affects the XP you might get. In vanilla, it simply aided you to fish in harder areas. 

So how this works right now, is that:

If you get XP at maximum 325 fishing skill in an area, and you have base skill of 300, and add an Aquadynamic Fish Attractor (+100 Fishing for 10 minutes), effectively you have fishing skill 400. 

In vanilla, it would treat you with XP based on your base skill level, of 300, so you'd earn XP. But on this server, it is counting it as 400, and thus you are way above the XP range to get any XP.  

EDIT:

It looks like the skill is bugged completely.

Trying to fish in areas that should get you xp at 300 fishing, without a fishing booster, results in you losing all your fish. So you don't earn any XP. I just lost 19 fish in a row.

**Comment by mattyhead** [comment]
In the live game, I took a fishing pole to Ashara and with 300 fishing skill ticked 305 on my 8th cast and 310 on my 19th cast.  Fishing can be advanced past 300 in high level Eastern Kingdom/Kalamidor waters.  At that point I went to Zanga and ticked 315 on my 13th cast using a Nighcrawler for +50 fishing.  This was my in line with my experience playing Classic TBC, Summer of '21.  I did not experience the original TBC, so I can't compare with that.

Fishing appears to be functioning in a normal way.
