### ISSUE TITLE
What would need changing, to get me to return?

### ISSUE THREAD

**Issue by LordPalandus** [wowmw/bugtracker#162]
PS: I'd do this on the discord but I hate the 30 minute slowdown crap you have active there. Really, even if you set it to just 3 minutes it would cut down on spam there. Not a bug report per say, but as you know me from the Discord (Bone), you should know who I am by now. 

It is great to see that the past two patches have improved a lot of things. I think that will really help those that are currently playing on your server, and potentially help newcomers. But, for me, I wanted to do the content, such as raids and old-world dungeons, and thus far I've not been able to do so, as I'm GMT-8, and most English speakers are GMT or GMT+1, so completely different time zones. I'm going to bed, when most are waking up, and so I miss all the raid times unless I stay up to 4-5am local time, which I just can't do... and then have to do a raid for 2 more hours... sorry but my schedule just doesn't support those hours. 

So, thus far I've been FUBARed from doing content that I really wanted to do. So, I made a huge number of suggestions on the discord and all of them were rejected, except maybe 1 or 2, of like 100, well thought out suggestions. I get that you don't want to do certain things for certain reasons, but thus far I've not really understood your vision for your server and you've done a lousy job of explaining it. You say you don't want a funserver, when the server is effectively already a funserver. But anyway, I'm getting off topic. When I left, I found a 255 funserver for WOTLK. Its allowing me to solo the content I had wanted to do on your server. So I've gotten used to certain conveniences in it, that I'd want to keep if I were to switch back to Moonwell. Its fun for a time to be an unstoppable force of destruction on this 255 funserver, but I prefer a more fun-esque blizzlike experience, which you offered. Anyway, these are the 5 things I'd need to see happen before I'd rejoin (your server has a lot of good stuff, but the core thing I wanted to do on your server I couldn't do, hence these requirements):

1] Buffer NPC = In the 255 funserver, there is this NPC that you talk to and they buff you with common player buffs, heal you and remove all debuffs. With this you can be better prepared for dungeons and raids, and remove those really pesky nasty curses and other debuffs you frequently acquire. You could build this into the Golem and only allow accessing it, by talking to it after combat. It would remove a lot of tediousness from waiting for debuffs to elapse. 

2] Teacher NPC = In the 255 funserver, there is this NPC that automatically teaches you all available crafting recipes up to your current skill level, whether they are taught, found or purchased. So, say I get to 350 blacksmithing. If I talked to them, they would teach me all the recipes up to 350 blacksmithing, even weapon/armor smith specific ones (though you'd need the specialization to use them). This means that you don't have to go hunting around for new recipes and it means once you reach 375, you can get access to all the epic 70 ones that are dropped in raids, to be able to craft some awesome gears immediately. It also means that I wouldn't have to do Blackrock Depths to get Fiery, or Karazhan to get Mongoose. 

3] Resource Vendors = In the 255 funserver, there is a NPC that sells all the resources, but for a higher gold cost than normal, but no badge of justice/frost cost. Honestly that worked great for this server, and so I'd be able to just visit the vendors, grab the resources needed, and just do the enchant or crafting with great convenience. To balance it on your server, you could increase the gold cost for stuff, but have the option of converting vote points or donor points into gold. But having Badge of Justice costs on your vendors, just feels petty and anti-player, forcing players to farm stuff manually when things refuse to drop; ie thick clefthoof hides. 

4] Convert Currencies = Allow us to convert Badges of Justice into Moon Coins, Honor Points and Arena Points. You allow people to convert those into Badges of Justice, but not the other way around. Thus, if you don't do PVP, you don't get any access to those three currencies. Not everyone likes PVP and you have to have good hours anyway, to participate in PVP moreso than doing raids. 

5] All Vanilla Content Soloable = Let us bring the golem with us everywhere in Vanilla WoW, so that we can solo world dragons or other world bosses (so that those of us warriors that wants quel'serrar for bragging rights, can do so solo), and solo all pre-tbc dungeons. I just can't solo most of these contents without that Golem. 

6] OPTIONAL = Solo raids. Make the raids soloable, but with reduced drop rates. Then make the heroic raids, for all 10 (or more) people, with the full loot list dropping, but be only half as difficult as blizzlike (so still tougher than what it is currently, but not as bad as blizzlike). That way, for those of us who can't get on for raiding hours, we can still do the raids, but for those that can do the raids, find that the heroic version is the best option for time. That way too you'd see more groups do the heroic versions and try to be properly geared as well for the heroic version. 

Anyway, I do want to say that I appreciate the time I had on Moonwell and appreciate for the existence of it to do some things I really wanted to do in TBC vanilla (back in 2006-2008). But, you may not want to try to get me to come back, which I would understand. It was good while it lasted, but if I can't do the content I was hoping for, then its probably for the best I stay on the 255 funserver instead.

**Comment by Gensen1** [comment]
Sorry, but I don't have time to write walls of text like you do. I read ideas, think about them, and give a concrete answer. You want a fun server. Our server is highrate server, not fun. 

Thank you for your time.
