### ISSUE TITLE
flying issue

### ISSUE THREAD

**Issue by xomsilver** [wowmw/bugtracker#166]
from time to time ill randomly have my netherwing drake fall from the sky or stop flying in general, i need to dismount and remount for it to actually fly, sometimes happens right as you enter combat after mounting or landing for a moment, happened today and i lost the scroll of buffs cause i fell out of the sky

**Comment by Gensen1** [comment]
XoM silver — 15.04.2022
I haven't found a way to reproduce it but it usually happens right after I bump into something from time to time or as I enter combat as soon as I mount it doesn't happen all the time only a hand full so far
Gensen — 15.04.2022
I bump into something from time to time or as I enter combat as soon as I mount

- can you give better examples?
XoM silver — Вчера, в 3:42
I just hit a mushroom just now in zang on a druid and fell to the ground didn't lose hp this time
Have got a video of me just jumping as a bird but can't send it
XoM silver — Вчера, в 4:17
I think it has something to do with auto run happening alot atm as a druid using auto run
XoM silver — Вчера, в 5:55
Ok so I've figured out that the auto run is the issue for falling out of the sky, hits an invisible wall then glitches out for a second
