### ISSUE TITLE
Auction search bug / Баг поиска на аукционе

### ISSUE THREAD

**Issue by johnzohan** [wowmw/bugtracker#167]
Необходимо исправить баг поиска на аукционе, который появился после последнего обновления.
До 12.04.2022 поиск отрабатывал корректно.

**Сценарий воспроизведения 01:**
1. Использовать англоязычный клиент.
2. В поле поиска на аукционе через стандартный линк любого игрового объекта (shift+клик) добавляем его наименование. В моем примере на скриншотах используется Изначальная жизнь.
3. Наименование объекта через линк всегда добавляется на кириллице.
4. Поиск не даёт результатов. Это не связано с отсутствием этого объекта на аукционе (см. скриншот 01).
5. Вводим наименование объекта на английском.
6. Поиск даёт положительный результат (см. скриншот 02).

**Сценарий воспроизведения 02:**
1. Использовать русскоязычный клиент.
2. В поле поиска на аукционе через стандартный линк любого игрового объекта (shift+клик) добавляем его наименование. В моем примере на скриншотах используется Изначальная жизнь.
3. Наименование объекта через линк всегда добавляется на кириллице.
4. Поиск даёт положительный результат (см. скриншот 03).
5. Вводим наименование объекта на английском.
6. Поиск  не даёт результатов (см. скриншот 04).

Для англ. клиента поведение реально проблемное.

---

**Ссылки на скриншоты на моем Яндекс.Диске**

Англоязычный клиент
Скриншот 01 - https://disk.yandex.ru/i/ZqF4ybMEGI8ccA
Скриншот 02 - https://disk.yandex.ru/i/hagTxqu0ogmKMA

Русскоязычный клиент
Скриншот 03 - https://disk.yandex.ru/i/aF5Qli80J_oi9w
Скриншот 04 - https://disk.yandex.ru/i/dt1N48Fn-JcSoA

**Comment by Gensen1** [comment]
После смены языка клиента вам нужно удалить папку Cache в директории с игрой.

**Comment by johnzohan** [comment]
> После смены языка клиента вам нужно удалить папку Cache в директории с игрой.

Приветствую. Действительно решает проблему описанных сценариев, спасибо. Закрывайте баг.
