### ISSUE TITLE
ЛБРС краш клиента

### ISSUE THREAD

**Issue by Gensen1** [wowmw/bugtracker#173]
https://youtu.be/0NeCoKezmoM
это по поводу ошибки в лбрс
6 ранов делал ошибку выдает +-10 ярдов от средней лестничной площадки
либо не добегаю до нее либо когда перехожу на нижнюю лестницу

**Comment by Dmitriyres** [comment]
> https://youtu.be/0NeCoKezmoM это по поводу ошибки в лбрс 6 ранов делал ошибку выдает +-10 ярдов от средней лестничной площадки либо не добегаю до нее либо когда перехожу на нижнюю лестницу

Добрый Вечер. Проверил ваш баг репорт.
Всё исправно с нашей стороны. Проблема в вашем клиенте игры. По этому вас крашит.
