### ISSUE TITLE
Trinket buged 

### ISSUE THREAD

**Issue by Tastemydmg** [wowmw/bugtracker#174]
[Mark of Conquest] this trinket buged

**Comment by Dmitriyres** [comment]
Holla Tastemydmg . I see ur post about this trink https://tbc.wowhead.com/item=27920/mark-of-conquest
What bug ? . Im already check this trink. They work fine .

**Comment by Dmitriyres** [comment]
Tastemydmg. Create new Bugtracker and wisp what bug on this trink.
On this moment im close this . Bugracker
