### ISSUE TITLE
Ret Pally SOC & SOB

### ISSUE THREAD

**Issue by DimcheArt** [wowmw/bugtracker#175]
У ретри паладинов при смене SOB & SOC прокают оба с одного удара. SOB у БЭ прокает при каждом ударе, у SOC же есть шанс прока, в зависимости от скорости оружия. 
https://tbc.wowhead.com/spell=31892/seal-of-blood 
https://tbc.wowhead.com/spell=27170/seal-of-command
При тесте в шатре с паладином видно, что можно без крыльев, берсов, вф и прочего сносить 6-7к за удар.
Прокать от одного удара может только один Сиал, никак не 2.
Все это зависит от постоянной смены SOB/SOC во время удара.
Не получается сбросить скиншот на Имгур
https://ibb.co/H4jYtyD
https://ibb.co/y06nQ5r
Ник в игре - Гор

**Comment by Hentaika** [comment]
Это сил твистинг. Всё ок. Вторую печать для прока нужно вешать в последние 0.5 сек до удара, но на мунвеле это работает не так, нужно нажать не в 0.5 сек, а прям в момент удара, тогда две печати прокнут, из-за этого ретриком наносится меньше дпс, т.к. расходуется гкд(.
