### ISSUE TITLE
Не работает сокет-бонус с "Блистающий танзанит"

### ISSUE THREAD

**Issue by Jumange90** [wowmw/bugtracker#176]
При вставлении камня "Блистающий танзанит" (10ап + 4хит), который выпадает с героика Король воронов Айкисс, не срабатывает сокет-бонус. Здесь этот камень по цвету оранжевый, но пишет что для красного и синего гнезда (по идее должен быть фиолетовый). По ВОВДАТЕ этот камень называется по другому (смотрел дроп с Айкиса) [ССЫЛКА](https://ru.tbc.wowhead.com/item=30553/%D0%BD%D0%B5%D1%82%D1%80%D0%BE%D0%BD%D1%83%D1%82%D1%8B%D0%B9-%D0%BE%D0%B3%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BE%D0%BF%D0%B0%D0%BB)  - и он как раз оранжевый, для красного и желтого гнезда. Такая же история с "Блистающий танзанит" (5агилы + 4хит), тоже не дает сокет-бонус.
Скрины прилагаю
![WoWScrnShot_051422_123934](https://user-images.githubusercontent.com/105542416/168420362-c08879da-431a-4e59-9ce2-b11e8e026702.jpg)
![WoWScrnShot_051422_121158](https://user-images.githubusercontent.com/105542416/168420365-dea07419-71a8-4757-8af4-4f5b256901fa.jpg)
![WoWScrnShot_051422_121329](https://user-images.githubusercontent.com/105542416/168420371-2addc2a9-6f4a-4b55-96e1-bb899460a446.jpg)
![WoWScrnShot_051422_121414](https://user-images.githubusercontent.com/105542416/168420373-339a1c94-199d-4489-9b37-5e9b1913ec53.jpg)

Ник - Jumange

**Comment by Dmitriyres** [comment]
> При вставлении камня "Блистающий танзанит" (10ап + 4хит), который выпадает с героика Король воронов Айкисс, не срабатывает сокет-бонус. Здесь этот камень по цвету оранжевый, но пишет что для красного и синего гнезда (по идее должен быть фиолетовый). По ВОВДАТЕ этот камень называется по другому (смотрел дроп с Айкиса) [ССЫЛКА](https://ru.tbc.wowhead.com/item=30553/%D0%BD%D0%B5%D1%82%D1%80%D0%BE%D0%BD%D1%83%D1%82%D1%8B%D0%B9-%D0%BE%D0%B3%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BE%D0%BF%D0%B0%D0%BB) - и он как раз оранжевый, для красного и желтого гнезда. Такая же история с "Блистающий танзанит" (5агилы + 4хит), тоже не дает сокет-бонус. Скрины прилагаю ![WoWScrnShot_051422_123934](https://user-images.githubusercontent.com/105542416/168420362-c08879da-431a-4e59-9ce2-b11e8e026702.jpg) ![WoWScrnShot_051422_121158](https://user-images.githubusercontent.com/105542416/168420365-dea07419-71a8-4757-8af4-4f5b256901fa.jpg) ![WoWScrnShot_051422_121329](https://user-images.githubusercontent.com/105542416/168420371-2addc2a9-6f4a-4b55-96e1-bb899460a446.jpg) ![WoWScrnShot_051422_121414](https://user-images.githubusercontent.com/105542416/168420373-339a1c94-199d-4489-9b37-5e9b1913ec53.jpg)
> 
> Ник - Jumange

На нашем сервере всё работает коректно . https://tbc.wowhead.com/item=30553/pristine-fire-opal .
Вы не правильно вставляете камни(сокеты) потому и не работает сокет бонус .  В синие гнездо подходит Фиолетовый(но не оранжевый)- > Скрин выше прелагаю.
![image](https://user-images.githubusercontent.com/114337602/192263086-1fd11a40-7ce4-4d6a-b95d-4d7400a465b8.png)
Аналогично с Грудью -> https://tbc.wowhead.com/item=30905/midnight-chestguard
![image](https://user-images.githubusercontent.com/114337602/192263693-f4a92d79-b0c8-45b3-b589-222d8492ac15.png)
Удалите ваше Cache и зайдите в игру заново.

**Comment by Dmitriyres** [comment]
![image](https://user-images.githubusercontent.com/114337602/192264019-a2e7ce8f-38e5-456d-bff9-0dec67f18dc7.png)
