### ISSUE TITLE
Стратхольм, ворота на главную площадь закрыты

### ISSUE THREAD

**Issue by Vexalus** [wowmw/bugtracker#178]
После убийства всех трёх боссов у зиккуратов ворота на главную площадь остаются закрытыми (Верховный судья Бартилас тоже убит). Двери первого зиккурата не доступны для нажатия, ворота второго и третьего зиккурата могут быть открыты и закрыты персонажем, однако это не производит никаких изменений на процесс игры. Если зайти в зиккурат и заагрить на себя мобов "тузадинский послушник", из игры выкидывает со следующей ошибкой:
https://imgur.com/a/doZSqBG

**Comment by Dmitriyres** [comment]
> тузадинский послушник

Добрый день . Просмотрел ваш Багтрекер . Ошибки не найдено . Всё работает коректно . Двери/Npc -> https://classic.wowhead.com/npc=10399/thuzadin-acolyte . 
Проблема в вашем клиенте игры. Попробуйте Убрать все модификации и пройти заново.
Сейчас я закрываю ваш баг отчёт . Если у вас случится что то подобное сново сообщите нам . Спасибо.
