### ISSUE TITLE
moonwell not working

### ISSUE THREAD

**Issue by waletwa** [wowmw/bugtracker#180]
moonwell in darnassus and outside shattrath city not working for making primal mooncloth

**Comment by gchickengod** [comment]
Try it in cenarion expedition

**Comment by Dmitriyres** [comment]
![image](https://user-images.githubusercontent.com/114337602/192243556-646fa183-b7eb-4a9d-a6e4-22fe58764172.png)
![image](https://user-images.githubusercontent.com/114337602/192243919-929b1061-299d-44fd-9ad8-dbaead3df9b4.png)


> moonwell in darnassus and outside shattrath city not working for making primal mooncloth

Hoola . Already tested not see any problem . Work corect on all spot . 
Ty for help. Im close This Bugtraker
