### ISSUE TITLE
Domesticated Felboar не лутается, а значит не дает снять шкуру.

### ISSUE THREAD

**Issue by gchickengod** [wowmw/bugtracker#183]
Лута нет, а при попытке снять шкуру - пишет что нужно сначала залутать.

**Comment by Dmitriyres** [comment]
> Лута нет, а при попытке снять шкуру - пишет что нужно сначала залутать.

 Добрый вечер . Нам известно об этой ошибке(баге) . Ожидайте фикса в следуйщих обновлениях
  либо здесь https://github.com/wowmw/bugtracker/issues/204 (аналогичный Bugtracker)
  Спасибо вам за помощь.
