### ISSUE TITLE
 Chain Lightning Заклинание шамана - задержка анимации

### ISSUE THREAD

**Issue by Basmong** [wowmw/bugtracker#185]
Заклинание шамана  Chain Lightning (https://tbc.wowhead.com/spell=25442/chain-lightning) имеет задержку в анимации - 
сначала моб получает урон, а только потом, некоторое время спустя, появляется анимация молнии. Это портит впечатление от игры элем шаманом на Вашем сервере. Анимация должна появляться даже чуть-чуть раньше урона. Кстати у голема(пет в данжах) нормальная анимация - обратите внимание!
Ссылку на видео прикрепляю: https://disk.yandex.ru/i/t2TCoUjwosc-hQ
Спасибо.

**Comment by Dmitriyres** [comment]
> Заклинание шамана Chain Lightning (https://tbc.wowhead.com/spell=25442/chain-lightning) имеет задержку в анимации - сначала моб получает урон, а только потом, некоторое время спустя, появляется анимация молнии. Это портит впечатление от игры элем шаманом на Вашем сервере. Анимация должна появляться даже чуть-чуть раньше урона. Кстати у голема(пет в данжах) нормальная анимация - обратите внимание! Ссылку на видео прикрепляю: https://disk.yandex.ru/i/t2TCoUjwosc-hQ Спасибо.

Добрый день . Проверил ваш багтрекер. 
https://tbc.wowhead.com/spell=25442/chain-lightning Работает коректно .
Сделал много тестов на Npc . Скрин прикрепил.
Если столкнётесь с этим сново напишите новый багтрекер. 
Спасибо.
![image](https://user-images.githubusercontent.com/114337602/192267228-64fad19b-11a5-48ff-8ffb-abfe599e2b91.png)
