### ISSUE TITLE
Не воскресает НПЦ 

### ISSUE THREAD

**Issue by yalokin21** [wowmw/bugtracker#186]
Не воскресает НПЦ Zuluhed the Whacked
https://tbc.wowhead.com/npc=11980/zuluhed-the-whacked

**Comment by Dmitriyres** [comment]
> Не воскресает НПЦ Zuluhed the Whacked https://tbc.wowhead.com/npc=11980/zuluhed-the-whacked

Добрый день . Проверил Ваш багрепорт . Квест работает коректно .https://tbc.wowhead.com/quest=10866/zuluhed-the-whacked
Npc->https://tbc.wowhead.com/npc=11980/zuluhed-the-whacked Аналогично
![image](https://user-images.githubusercontent.com/114337602/192259993-1c296077-0bde-4696-aa8f-16035cc10bdc.png)
Отмените квест . А затем возмите его сново .
