### ISSUE TITLE
Шанс сопротивления фиру\стану

### ISSUE THREAD

**Issue by 2q2e** [wowmw/bugtracker#189]
![image](https://user-images.githubusercontent.com/110341467/182032124-0e4cdf22-f6d6-4126-bdd6-ff8c80f111d4.png)
![image](https://user-images.githubusercontent.com/110341467/182032153-e2ebfc8b-ac22-4f65-b4bd-cd4f61ed2591.png)
По друиду с вкачаным талантом проходят почти 99% станов и фиров. Меня фирил варлок 32 раза за это время случился 1 резист. У варлока  на скриншоте 2.7% меткости. 
Почему вообще решили протестировать, я на бг постоянно нахожусь в контроле от варлока рогов варов, и за все это время игры на бг мне не посчастливилось ни на один резист.  Это чуть ли ни самый важный талант друида в пвп, который должен  срабатывать практически на каждый условный 4-5 фир\стан. Найти видео с оффа мне не удалось, и снять свое тоже, т.к. у меня просто закончилась подписка. Но опыт игры в 15 лет на десятках серверов тоже сложно полагаться, т.к. везде интерпретируют по разному и везде все работает по-разному. На вовхеде написано единственная фраза "этот талант великолепен для пвп" но к сожалению тут он не работает вообще. 
![image](https://user-images.githubusercontent.com/110341467/182032649-779f0f6a-0d07-420d-91ab-39663a97c142.png)
Он должен работать либо по системе "псевдорандома" тоесть либо каждый 4\5 фир или стан в случайном порядке уходит в резист, либо по более сложной системе исходя из меткости того кто кидает заклинание и шанса споротивления высчитывается процент попадания.(без понятия как это реализуется) На данный момент шанс срабатывания резиста не более 3%, что при встрече с любым варлоком, рогой.  (т.к. шанс сопротивления станам талант тоже не повышает) вызывает очень смешанные чувства. Исправьте пожалуйста :) Пристовский фир выдает сопротивления, это мы тоже протестили.

**Comment by Gensen1** [comment]
1) Талант друля работает
2) Резисты проверялись недавно, работают на 100%
3) Псевдорандома в БК нет. Идет обычный ролл от 0 до 100. Если, например, у вас 15% резиста стана и выпадает значение >=15, то стан резистится.

**Comment by Gensen1** [comment]
1) Талант друля работает
2) Псевдорандома в БК нет. Идет обычный ролл от 0 до 100.
3) По поводу резистов давайте подробее на примере:

```
лок: базовый шанс на попадание фиром 96%
лок: [Подавление] вкачан на 3 - +6% = 96+6=102% (кап 100% был добавлен в ЛК)
друль: [Изначальная стойкость] в 3 дает 15% = 102-15=87%
лок: имеет 91 спелл хита, это +7.21% = 87+7.21=94.21
итого лок имеет 94.21% на попадание фиром в данном примере
```

Пруфы: https://wowwiki-archive.fandom.com/wiki/Spell_hit?oldid=1652497. 

1) Фир является бинарным спеллом, как и стан - "For binary spells that do not partially resist, the resistance mitigation is combined with the spell hit chance to give an overall percentage for the spell to land or be resisted."
2) With [patch 3.0.2], spell hit is capped at 100%

На многих пиратских БК ядрах резисты работают совсем по другому. Не нужно сравнивать. В нашем ядре при разработке формул мы полагались на информацию из официальных источников. 

В любом случае я открыт к диалогу. Если я в чем-то не прав - жду вашу аргументацию со ссылками на официальные источники.

**Comment by 2q2e** [comment]
У меня кончились аргументы, кроме того, что шанс сопротивления должен быть выше, ферал не должен ловить 99.9% контроля. Иначе это полнейший дисбаланс :) На офе естественно работает иначе, резисты на станы и фиры вылетают довольно часто.

**Comment by Gensen1** [comment]
Одни жалуются, что резисты случаются слишком часто, другие - что слишком редко. Никакого конструктива в этом нет. 

Я привел аргументацию в пользу правильной работы механики на нашем сервере. Если вы считаете, что я ошибаюсь, приведите свои аргументы. Полагаться исключительно на чьи-то ощущения я не могу.

**Comment by Dmitriyres** [comment]
> У меня кончились аргументы, кроме того, что шанс сопротивления должен быть выше, ферал не должен ловить 99.9% контроля. Иначе это полнейший дисбаланс :) На офе естественно работает иначе, резисты на станы и фиры вылетают довольно часто.

Добрый день . Тестил на протяжение пару дней . Работает коректно из 10 фиров(Страха) сопротивление 1-2 раза . Вам просто не повезло.
Если вы найдете другие аргументы в неправильной механике на нашем сервере напишите новый Багрепорт.
