### ISSUE TITLE
Порталы в наксе

### ISSUE THREAD

**Issue by Stormday** [wowmw/bugtracker#191]
Здравствуйте, около ластов на первом этаже накса (таддик, кони, мексна, лохтиб) стоят порталы для порта в начало инста. К сожалению они работают каждый раз рандомно только для одной фракции, сделайте, чтобы они работали для всех участников рейда.

**Comment by Gensen1** [comment]
Фикс был в одном из прошлых обновлений. Перепроверил - работает для обеих фракций в группе.

**Comment by Dmitriyres** [comment]
> Здравствуйте, около ластов на первом этаже накса (таддик, кони, мексна, лохтиб) стоят порталы для порта в начало инста. К сожалению они работают каждый раз рандомно только для одной фракции, сделайте, чтобы они работали для всех участников рейда.

Здраствуйте . Перепроверил . Работает коректно всё верно.
