### ISSUE TITLE
quest=10226

### ISSUE THREAD

**Issue by Stormday** [wowmw/bugtracker#192]
Суть квеста юзнуть итем квестовый на элементаля и его убить, но кристалл нужный выпадает, а взять его нельзя, даже полностью собрав все с сумок элема, хитбокс просто перекрывает квестовый итем

**Comment by Dmitriyres** [comment]
> Суть квеста юзнуть итем квестовый на элементаля и его убить, но кристалл нужный выпадает, а взять его нельзя, даже полностью собрав все с сумок элема, хитбокс просто перекрывает квестовый итем

Спасибо за ваш багрепорт . Проверил Работает не правильно . Ожидайте фикса.
