### ISSUE TITLE
Обледенение - заклинание мага 

### ISSUE THREAD

**Issue by dsadawergregf** [wowmw/bugtracker#195]
Здравствуйте. Заметил что изучаемое в ветке талантов мага "Лед" заклинание " Обледенение" не правильно отображает характеристики по мере изучения. По факту все работает, я проверил с этим талантов и без него, только отображает не верно. 
![WoWScrnShot_081922_184958](https://user-images.githubusercontent.com/111588449/185659469-54d8a373-9e59-4401-a1fe-a5b79018ea5e.jpg)
![WoWScrnShot_081922_185008](https://user-images.githubusercontent.com/111588449/185659472-eca06f8b-0c96-4507-8c45-54970bb990f4.jpg)

**Comment by Gensen1** [comment]
Перевод на русский хромает, это не единичный случай. Ошибка в самом клиенте и исправить ее нельзя.
