### ISSUE TITLE
No Moon Coins in Vote Chests

### ISSUE THREAD

**Issue by foxkrm** [wowmw/bugtracker#202]
After i first time bought/exchanged a couple of moon coins via NPC in Shattrath (paid with Honor points) for every single vote chest i opened, there is no moon coin inside.

Vote chest has drop rate category 100% 1-5 coins for every loot/opening.
I think that something triggered by exchanging the honor points to moon coins and now something it goes wrong.

Thanks.

**Comment by foxkrm** [comment]
No moon coins in any Vote chest on any character linked to the account that purchased Moon coins via honor points via NPC in Shattrath.

**Comment by Gensen1** [comment]
Hello. Moon Coins were removed from Vote Chest loot at one of last updates.
