### ISSUE TITLE
Flying Mount Bugged Inside buildings

### ISSUE THREAD

**Issue by weldonjames** [wowmw/bugtracker#205]
I was doing the "Down with Daellis" quest located in Netherstorm and flew into Manaforge on a flying mount and was logged off. I logged back in and finished the quest and went to turn it in to Custodian Dieworth but he wasn't there. I flew into the tower, which is beside the quest giver and was immediately logged off again and when i logged back in, I was a supposedly killed because I was in spirit form. I know i shouldn't have been flying inside buildings but I just assumed it would take my mount away. Thank you for your time and support!

**Comment by Dmitriyres** [comment]
Holla Weldonjames .
Already tested https://tbc.wowhead.com/quest=10223/down-with-daellis . Fine work for me on 2-3acc not see any problem.
Maybe u have problem with ur Addons (combat) etc

**Comment by Dmitriyres** [comment]
Thx . Im close this Bugtrack

**Comment by Dmitriyres** [comment]
I find another bug with same problem create another Bugtraker thx.
Now im close this .
