### ISSUE TITLE
some spells are not learnt automatically

### ISSUE THREAD

**Issue by konechuwa** [wowmw/bugtracker#206]
Hello, I have noticed I was using Mortal Strike rank 1 for several days. Because other spells are learnt automatically I didn't visit a trainer. There might be more spells like this for another classes. 
I wonder how many warriors are running out there with mortal strike rank 1.

I have used fast start and it's a spell firstly learnt from talents.

Kind regards
Konechuwa/Omanigato

EDIT: Nature's Grasp and Insect Swarm - the same issue, guess it's all spells learnt from talents

**Comment by Gensen1** [comment]
Hello. Fast Start learns all spells can be learned at the moment of character creation. Spells from talents are new spells that always have rank 1, so they should be upgraded manually.
