### ISSUE TITLE
Fear distance of cc

### ISSUE THREAD

**Issue by mati2224** [wowmw/bugtracker#207]
the ability sends you extremely far, sometimes, it encloses you in mountains or some texture passes through it.
In pvp there are times when it's not that unstable but in pve, they go very far.
and and in cases like sunwell plateau trash it complicates you.

https://www.youtube.com/watch?v=_XPup_E7Fxs&ab_channel=matiasgonzalez

https://www.youtube.com/watch?v=A-gP_8fwTrU&ab_channel=matiasgonzalez

https://www.youtube.com/watch?v=mu8nWL9SxF8&ab_channel=matiasgonzalez

**Comment by Dmitriyres** [comment]
[mati2224](https://github.com/mati2224) If this ur video fix.
Video unavailable
This is a restricted video. Cant watch . But we check and test ty.
![image](https://user-images.githubusercontent.com/114337602/192149425-b3c510d0-c1dd-4c9f-a6d6-4d79d415513a.png)

**Comment by mati2224** [comment]
> [mati2224](https://github.com/mati2224) If this ur video fix. Video unavailable This is a restricted video. Cant watch . But we check and test ty. ![image](https://user-images.githubusercontent.com/114337602/192149425-b3c510d0-c1dd-4c9f-a6d6-4d79d415513a.png)

https://youtu.be/mu8nWL9SxF8 

https://youtu.be/_XPup_E7Fxs


https://youtu.be/A-gP_8fwTrU


i fixed the videos link,sorry now can see it

**Comment by Dmitriyres** [comment]
> > [mati2224](https://github.com/mati2224) If this ur video fix. Video unavailable This is a restricted video. Cant watch . But we check and test ty. ![image](https://user-images.githubusercontent.com/114337602/192149425-b3c510d0-c1dd-4c9f-a6d6-4d79d415513a.png)
> 
> https://youtu.be/mu8nWL9SxF8
> 
> https://youtu.be/_XPup_E7Fxs
> 
> https://youtu.be/A-gP_8fwTrU
> 
> i fixed the videos link,sorry now can see it

Im test this another day (very late now) thx .

**Comment by mati2224** [comment]
thx!
