### ISSUE TITLE
[Благословление Природы] или формула хасты на баланс друиде???

### ISSUE THREAD

**Issue by Wilsewool** [wowmw/bugtracker#216]
Добрый вечер.
Давно хотел создать тему по этому поводу.
И вот я тут.)
Талант баланс друида [Благословление Природы] работает не верно.
Точнее идет неправильный расчет скорости спэла после критового каста.
Скриншот №1.
На персонаже спэл хасты 0.
Аддон Quartz указывает на нормальную скорость каста спэла Стар Фаер - 3,0с.
![1](https://user-images.githubusercontent.com/114786388/193376414-ed5295de-04f0-418d-9905-01c6dd2a03ba.jpg)
Скриншот №2.
Всё те же 0% спэл хасты, все тот же стар фаер но уже под бафом - каст 2,5с все верно.
![2](https://user-images.githubusercontent.com/114786388/193376429-0be2d100-e99f-4770-9ba7-bda664852970.jpg)
Скриншот №3.
Заряжаем шмотки на хасту и наблюдаем нормальную скорость каста стар фаера - 2,6с (12% спэл хаста).
![3](https://user-images.githubusercontent.com/114786388/193376440-1e5b2427-7770-4e96-8b1f-bea7680929bf.jpg)
Скриншот №4.
Да начнется шухер.
Уже под бафом баланса от крита каст становится 2,2с ( хотя баф снимает 0,5 от основного с учетом спэл хаста 2,6-0,5=2,1).
![4](https://user-images.githubusercontent.com/114786388/193376446-93bf7185-a300-4a6a-89a8-bad0ac01fe50.jpg)
Скриншот №5.
Добавим немножечно бладласта.
Нормальный каст 2,0с без бафа.
![5](https://user-images.githubusercontent.com/114786388/193376461-0280a953-ef0d-4a9c-9eb0-88f6ef426629.jpg)
И скриншот №6.
Заряженый под спэл хаст баланс с блом и бафом.
1,7с. 
![6](https://user-images.githubusercontent.com/114786388/193376472-33a04fce-efdb-401a-8b1b-1a566153aa9f.jpg)
Хотя должно быть 2,0с - 0,5с = 1,5с.
Стоит ли говорить, что дальнейшее увеличение хасты будет съедать баф ещё больше.
+Барабаны + Дополнительные бафы на спэл хаст.
Могу сделать вывод, что формула расчета каста не правильная.
Сейчас что то в духе: нормальная скорость каста -0,5с - % спэл хаст.
Хотя должна быть: нормальная скорость каста -% спэл хаста -0,5с бафа.
У меня все, спасибо за внимание.

**Comment by Dmitriyres** [comment]
> Добрый вечер. Давно хотел создать тему по этому поводу. И вот я тут.) Талант баланс друида [Благословление Природы] работает не верно. Точнее идет неправильный расчет скорости спэла после критового каста. Скриншот №1. На персонаже спэл хасты 0. Аддон Quartz указывает на нормальную скорость каста спэла Стар Фаер - 3,0с. ![1](https://user-images.githubusercontent.com/114786388/193376414-ed5295de-04f0-418d-9905-01c6dd2a03ba.jpg) Скриншот №2. Всё те же 0% спэл хасты, все тот же стар фаер но уже под бафом - каст 2,5с все верно. ![2](https://user-images.githubusercontent.com/114786388/193376429-0be2d100-e99f-4770-9ba7-bda664852970.jpg) Скриншот №3. Заряжаем шмотки на хасту и наблюдаем нормальную скорость каста стар фаера - 2,6с (12% спэл хаста). ![3](https://user-images.githubusercontent.com/114786388/193376440-1e5b2427-7770-4e96-8b1f-bea7680929bf.jpg) Скриншот №4. Да начнется шухер. Уже под бафом баланса от крита каст становится 2,2с ( хотя баф снимает 0,5 от основного с учетом спэл хаста 2,6-0,5=2,1). ![4](https://user-images.githubusercontent.com/114786388/193376446-93bf7185-a300-4a6a-89a8-bad0ac01fe50.jpg) Скриншот №5. Добавим немножечно бладласта. Нормальный каст 2,0с без бафа. ![5](https://user-images.githubusercontent.com/114786388/193376461-0280a953-ef0d-4a9c-9eb0-88f6ef426629.jpg) И скриншот №6. Заряженый под спэл хаст баланс с блом и бафом. 1,7с. ![6](https://user-images.githubusercontent.com/114786388/193376472-33a04fce-efdb-401a-8b1b-1a566153aa9f.jpg) Хотя должно быть 2,0с - 0,5с = 1,5с. Стоит ли говорить, что дальнейшее увеличение хасты будет съедать баф ещё больше. +Барабаны + Дополнительные бафы на спэл хаст. Могу сделать вывод, что формула расчета каста не правильная. Сейчас что то в духе: нормальная скорость каста -0,5с - % спэл хаст. Хотя должна быть: нормальная скорость каста -% спэл хаста -0,5с бафа. У меня все, спасибо за внимание.

Добрый день . Спасибо за ваш Bugtracker . Проверил. Работает (некореткно на нашем сервере) требуется  фикса . Ожидайте(спасибо за ваш пост)

**Comment by Wilsewool** [comment]
И вот я сново тут.
Добрый день.
Опровержение Ваших слов или доказательство моих нашлось так же неожиданно, как началась вся эта тема.
Уж очень редко я играю на холи паладинах. И вот вчера...
Короче к сути.
Скриншот №1.
Холи паладин с рейтом хасты 0% - скорость каста 2,5с.
![1](https://user-images.githubusercontent.com/114786388/196036044-29afb83b-bfee-4515-a994-e12d84327ee8.jpg)
Скриншот №2.
Баф холи падалина https://db.moonwell.su/?spell=31836 0% раст рейта - скорость каста 2,0с.
![2](https://user-images.githubusercontent.com/114786388/196036149-bc1b3427-fb7a-426e-af95-0d9b82ea7dba.jpg)
Скриншот №3.
Холи паладин с 13% хаста - скорость каста 2,2с.
![3](https://user-images.githubusercontent.com/114786388/196036195-45f9ad18-d83b-4c86-8e6b-356151da2a39.jpg)
Скриншот №4.
Холи паладин с 13% хаста и уже под бафом - скорость каста 1,7с.

Сервер - https://moonwell.su/

Встает логичный вопрос.
По вашей логике, если у баланса это было сделано с целью не максимизации хасты на чаре (хотя как мы знаем хаст имеет процесс регрессии от её количества) тогда почему у холи паладина все работает как надо?
...Или наоборот, работает не правильно...
Спасибо за внимание.

**Comment by Wilsewool** [comment]
![1](https://user-images.githubusercontent.com/114786388/196037463-47922779-3b2f-42b6-ba2c-186d613bc467.jpg)

**Comment by Wilsewool** [comment]
https://wowwiki-archive.fandom.com/wiki/Nature%27s_Grace?oldid=1369517

**Comment by Gensen1** [comment]
2.5 базовый каст
+320 хасты = 2.08 каст
+ талант = 1.66 каст
2.08-1.66 = 0.42

Видимо ваш аддон округляет время каста.
