### ISSUE TITLE
Баг победы на БГ Альтерак

### ISSUE THREAD

**Issue by DiKrasavkin** [wowmw/bugtracker#226]
Я зарегался на альтераке вся моя группа побежала бить боса осталось 50к хп мы не успели его добить ( мой персонаж ордынец - я играл за флаг альянса , после того как мы не успели добить боса провотиположная команда ( орды убила боса раньше команды альянс ) но мне всеровно зачиталась победа хотя я ордынец играл за альянс ) ( этот баг я уже наблюдаю не однократно сначала мне показалось что это сбой системы но после 3 раза уже как то подозрительно

**Comment by Dmitriyres** [comment]
> Я зарегался на альтераке вся моя группа побежала бить боса осталось 50к хп мы не успели его добить ( мой персонаж ордынец - я играл за флаг альянса , после того как мы не успели добить боса провотиположная команда ( орды убила боса раньше команды альянс ) но мне всеровно зачиталась победа хотя я ордынец играл за альянс ) ( этот баг я уже наблюдаю не однократно сначала мне показалось что это сбой системы но после 3 раза уже как то подозрительно

Добрый вечер. Спасибо за ваш баг отчёт. На данный момент проверяется. Ожидайте дальнейшей информации здесь.

**Comment by Dmitriyres** [comment]
> Я зарегался на альтераке вся моя группа побежала бить боса осталось 50к хп мы не успели его добить ( мой персонаж ордынец - я играл за флаг альянса , после того как мы не успели добить боса провотиположная команда ( орды убила боса раньше команды альянс ) но мне всеровно зачиталась победа хотя я ордынец играл за альянс ) ( этот баг я уже наблюдаю не однократно сначала мне показалось что это сбой системы но после 3 раза уже как то подозрительно

Проверил несколько раз .Вот примеры подтверждения что с нашей стороны всё работает коректно . Возможно какой то сбой в системе. 
![image](https://user-images.githubusercontent.com/114337602/193573758-34afbafb-6e4e-41d9-ae10-1992588d647f.png)
Проверяется.

**Comment by Dmitriyres** [comment]
Ключевое заключение. Сбой системы связаны с нагрузками на Бг. Проблем не выявлено. Спасибо за ваш отчёт. Если это случится сново напишите нам здесь. На данный момент я закрываю ваш Bugtracker . Удачной игры. Хорошего дня.
