### ISSUE TITLE
Друид (Увечье)

### ISSUE THREAD

**Issue by Planovui** [wowmw/bugtracker#228]
![WoWScrnShot_100922_020126](https://user-images.githubusercontent.com/115392634/194745953-2f2893d6-087b-4b92-bada-a3771c5b2840.jpg)
![WoWScrnShot_100922_020133](https://user-images.githubusercontent.com/115392634/194745961-3efa02dc-d58c-4656-ae4a-25e1791fe307.jpg)
![WoWScrnShot_100922_020137](https://user-images.githubusercontent.com/115392634/194745968-f2a9f410-251a-40a9-9279-5d06f0cc9376.jpg)
Прокачал друида до 70го уровня. Во второй ветке талант (Увечье (медведь , кот)). Который последний во второй ветке. Он появился в книге , всё работало нормально. Потом я решил чуть поменять ветку , юзнул книгу смены талантов , выбрал свободный слот. Понял что всю понель раставлять по новой и решил пока вернуть тот билд что был. Открыл книгу смены талантов и выбрал там 1ю позицию которая была изначально. И у меня с панели и с книги заклинаний пропал этот (Удар или как назвать правильно) (Увечье вкачено в ветке , в книге заклинаний  оно отсутствует) Писал тикет мне предложили почистить кеш и отключить адоны , это не чего не изменило. И гм или модератов сказал написать багрепорт , что я собственно и сделал.
Сейчас в процессе написания багрепорта я сбегал к тренеру друидов скинул ветку , вкачал по новой всё появилось . Потом опять в книге смены талантов выбрал пустую позицию , и снова вернулся на своё позицию где ветка вкачена и опять он пропал (Увечье (медведь кот)). Но у тренера появилась возможность изучить его , изучил и он снова есть в книге.Но если проделывать тоже самое с книгой смены ветки , он (Увечья) всё время исчезает из книги заклинаний и с панели. Извините за подачу текста нет времени всё редактировать и формулировать , пишите в дискорде Плановый #3758 созвонимся подробно всё расскажу. Это явно баг с книгой смены ветки. Спасибо за внимание.

**Comment by Dmitriyres** [comment]
> ![WoWScrnShot_100922_020126](https://user-images.githubusercontent.com/115392634/194745953-2f2893d6-087b-4b92-bada-a3771c5b2840.jpg) ![WoWScrnShot_100922_020133](https://user-images.githubusercontent.com/115392634/194745961-3efa02dc-d58c-4656-ae4a-25e1791fe307.jpg) ![WoWScrnShot_100922_020137](https://user-images.githubusercontent.com/115392634/194745968-f2a9f410-251a-40a9-9279-5d06f0cc9376.jpg) Прокачал друида до 70го уровня. Во второй ветке талант (Увечье (медведь , кот)). Который последний во второй ветке. Он появился в книге , всё работало нормально. Потом я решил чуть поменять ветку , юзнул книгу смены талантов , выбрал свободный слот. Понял что всю понель раставлять по новой и решил пока вернуть тот билд что был. Открыл книгу смены талантов и выбрал там 1ю позицию которая была изначально. И у меня с панели и с книги заклинаний пропал этот (Удар или как назвать правильно) (Увечье вкачено в ветке , в книге заклинаний оно отсутствует) Писал тикет мне предложили почистить кеш и отключить адоны , это не чего не изменило. И гм или модератов сказал написать багрепорт , что я собственно и сделал. Сейчас в процессе написания багрепорта я сбегал к тренеру друидов скинул ветку , вкачал по новой всё появилось . Потом опять в книге смены талантов выбрал пустую позицию , и снова вернулся на своё позицию где ветка вкачена и опять он пропал (Увечье (медведь кот)). Но у тренера появилась возможность изучить его , изучил и он снова есть в книге.Но если проделывать тоже самое с книгой смены ветки , он (Увечья) всё время исчезает из книги заклинаний и с панели. Извините за подачу текста нет времени всё редактировать и формулировать , пишите в дискорде Плановый #3758 созвонимся подробно всё расскажу. Это явно баг с книгой смены ветки. Спасибо за внимание.

Добрый день . Возможно у вас Единоразовая ошибка. Сделал несколько тестов (при сбросе талантов) с парочки новых друидов . Ошибки не обнаружил .При смене талантов . Выбрасивает в мир персонажей. Захожу всё остаётся на месте и все заклинания на месте.
![image](https://user-images.githubusercontent.com/114337602/194830628-adda56e9-c3a2-478a-ae60-87446aaa06ad.png)
![image](https://user-images.githubusercontent.com/114337602/194830658-b415eb97-c100-453e-be40-0707aeab58b6.png)
![image](https://user-images.githubusercontent.com/114337602/194830970-e52a99eb-82b5-47a3-b19c-08dda335c0fa.png)

![image](https://user-images.githubusercontent.com/114337602/194830209-384699a5-90ae-4099-9070-eb5de1307f29.png)
