### ISSUE TITLE
Арати и око (15-15)???

### ISSUE THREAD

**Issue by Planovui** [wowmw/bugtracker#230]
![WoWScrnShot_101022_235111](https://user-images.githubusercontent.com/115392634/194977453-326d02f3-7450-427b-9b0c-6eee15b70e70.jpg)
![WoWScrnShot_101022_235105](https://user-images.githubusercontent.com/115392634/194977464-1280778c-269c-4927-bb86-602b62da3c75.jpg)
Разве не 15 игроков максимальное количество? как альянса так и орды?

**Comment by Dmitriyres** [comment]
> ![WoWScrnShot_101022_235111](https://user-images.githubusercontent.com/115392634/194977453-326d02f3-7450-427b-9b0c-6eee15b70e70.jpg) ![WoWScrnShot_101022_235105](https://user-images.githubusercontent.com/115392634/194977464-1280778c-269c-4927-bb86-602b62da3c75.jpg) Разве не 15 игроков максимальное количество? как альянса так и орды?

Добрый день . В предыдущий обновлениях было сделано Бг(Батлграунд) . Увеличение с 15 до 40 .
