### ISSUE TITLE
Альтерак.

### ISSUE THREAD

**Issue by Planovui** [wowmw/bugtracker#231]
На альтераке , играл за орду. Пришел на базу альянса к ласт боссу , юзаю забрать вышку , мне сбивают юз. Я там рогой убегаю , жду они уходят. Возвращаюсь на эту же вышку а юзнуть (захватить) её я не могу. Просто не нажимается. Так же не должно быть?

**Comment by Dmitriyres** [comment]
> На альтераке , играл за орду. Пришел на базу альянса к ласт боссу , юзаю забрать вышку , мне сбивают юз. Я там рогой убегаю , жду они уходят. Возвращаюсь на эту же вышку а юзнуть (захватить) её я не могу. Просто не нажимается. Так же не должно быть?

Добрый день . Да не должно . Проблема с флагами на альтераке известна. Ожидайте фикса в следуйщих обновлениях.
