### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by cosmopolatan** [wowmw/bugtracker#233]
вибив метлу с швидкистю 150 300 коли сыдаеш на 150 и сразу на 300 то метла пропадает и персонаж как будто с флаем

**Comment by Dmitriyres** [comment]
> вибив метлу с швидкистю 150 300 коли сыдаеш на 150 и сразу на 300 то метла пропадает и персонаж как будто с флаем

Добрый день . Спасибо за ваш баг репорт . Проверим . Ожидайте.

**Comment by Dmitriyres** [comment]
> вибив метлу с швидкистю 150 300 коли сыдаеш на 150 и сразу на 300 то метла пропадает и персонаж как будто с флаем

Проверил . Это Визуальный баг для вас. Для остальных вы сидите и летаете на 280% метле. 
![image](https://user-images.githubusercontent.com/114337602/196220003-747937ca-8a88-4513-8029-b748145ced02.png)
![image](https://user-images.githubusercontent.com/114337602/196220143-624668ac-542c-4ec1-a5fd-6e37ea7f3597.png)

![image](https://user-images.githubusercontent.com/114337602/196219747-02942b89-ab69-44d8-bb71-520bff5bf0b6.png)
