### ISSUE TITLE
bug quest

### ISSUE THREAD

**Issue by mati2224** [wowmw/bugtracker#236]
hi this quest "elixir of suffering " drop this epic item
[](url)https://ibb.co/59Y9djz

**Comment by Dmitriyres** [comment]
> hi this quest "elixir of suffering " drop this epic item https://ibb.co/59Y9djz

Thx for ur bugtracker . I will check him soon .

**Comment by Dmitriyres** [comment]
> hi this quest "elixir of suffering " drop this epic item https://ibb.co/59Y9djz

Holla again. 
![image](https://user-images.githubusercontent.com/114337602/197310024-47c0412e-546b-461f-8c66-ad488c4b4940.png)
Quest item drop fine (u can see on photo) . U need be delete Cache for fix. 
Thx and GL
