### ISSUE TITLE
Изучение спеллов у петомца(Beast Training) Охотника x5

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#240]
При приручение любого питомца с оптимальным заклинанием  что бы получить его абилку в список желаемого(а именно в книгу Beast Training) спел будь то либо Спринт(Dive) или Screech как указано на фото он просто не изучается в книжку. Требует фикса.
![image](https://user-images.githubusercontent.com/114337602/198728875-253bc6b0-6be7-4a0f-b485-ab176e232d6d.png)
![image](https://user-images.githubusercontent.com/114337602/198729532-4ee5f2bf-79e6-4920-8053-fcfc94e949ee.png)
![image](https://user-images.githubusercontent.com/114337602/198729560-de53dd92-2e50-4f0c-a9ed-0f55a122fe8b.png)

**Comment by grebbly2** [comment]
> При приручении любого питомца с оптимальным заклинанием, чтобы получить его абилку в желаемом (а именно в книгу Beast Training) спел будь то либо Спринт (Dive) или Screech, как указано на фото, он просто не изучается в книжке. Требует фикса.
> ![Изображение](https://user-images.githubusercontent.com/114337602/198728875-253bc6b0-6be7-4a0f-b485-ab176e232d6d.png)
> ![Изображение](https://user-images.githubusercontent.com/114337602/198729532-4ee5f2bf-79e6-4920-8053-fcfc94e949ee.png)
> ![Изображение](https://user-images.githubusercontent.com/114337602/198729560-de53dd92-2e50-4f0c-a9ed-0f55a122fe8b.png)
 Все изучается, позавчера выучил пету все способносить. Для этого необходимо покормить питомца, и заставить его использовать тот спел который хотите выучить. Так работало и на официальных серверах. Не вводите людей в заблуждение.

**Comment by Hentaika** [comment]
> > При приручении любого питомца с оптимальным заклинанием, чтобы получить его абилку в желаемом (а именно в книгу Beast Training) спел будь то либо Спринт (Dive) или Screech, как указано на фото, он просто не изучается в книжке. Требует фикса.
> > ![Изображение](https://user-images.githubusercontent.com/114337602/198728875-253bc6b0-6be7-4a0f-b485-ab176e232d6d.png)
> > ![Изображение](https://user-images.githubusercontent.com/114337602/198729532-4ee5f2bf-79e6-4920-8053-fcfc94e949ee.png)
> > ![Изображение](https://user-images.githubusercontent.com/114337602/198729560-de53dd92-2e50-4f0c-a9ed-0f55a122fe8b.png)
> > Все изучается, позавчера выучил пету все способносить. Для этого необходимо покормить питомца, и заставить его использовать тот спел который хотите выучить. Так работало и на официальных серверах. Не вводите людей в заблуждение.

Всё верно. Изучается.
![WoWScrnShot_103022_193750](https://user-images.githubusercontent.com/18301825/198890426-6baa7a50-44f9-48df-9e26-a5fa96aed7a8.jpg)

**Comment by Hentaika** [comment]
[Dmitriyres](https://github.com/Dmitriyres), я сначало не совсем поняла, что речь про два конкретных спелла, а не про все вообщем.
Один из них я выучила спустя полчаса, т.к. не все спеллы питомца учатся с первого использования.
![WoWScrnShot_103022_213356](https://user-images.githubusercontent.com/18301825/198895541-68142d55-f096-42c9-b86e-4d857934453b.jpg)

**Comment by Hentaika** [comment]
Ну и второй указанный спелл.
![WoWScrnShot_103022_223326](https://user-images.githubusercontent.com/18301825/198898076-443c775c-b67e-4428-a3e9-4ec9ffc4f9f2.jpg)
