### ISSUE TITLE
Багается  счётчик  квеста на убийство NPC X5

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#244]
При убийстве NPC На квест https://db.moonwell.su/?quest=10390 
Защитывает Npc на 1 больше 
![image](https://user-images.githubusercontent.com/114337602/198886887-cc1e2a5c-adfb-4ae8-aed1-7c86ec864c51.png)
При поднятие https://db.moonwell.su/?item=29586 защитивает оба
Визуальный баг

**Comment by Hentaika** [comment]
При поднятии https://db.moonwell.su/?item=29586 идёт в счётчик как убитый https://db.moonwell.su/?npc=16947, из-за этого получается 9 убитых при отображении в 10, квест нельзя сдать, после релога показывает правильно: 9/10.
Если при счётчике 10/10 если убить ещё одного моба, будет 11/10, после релога естественно станет правильно: 10/10.
Визуальный баг с отображением.
![WoWScrnShot_103022_163429](https://user-images.githubusercontent.com/18301825/198888048-b9676262-0e5a-452f-a8cc-624db6cc1837.jpg)
![WoWScrnShot_103022_163526](https://user-images.githubusercontent.com/18301825/198888052-e40b7aca-a840-421d-9f65-daeffba270e9.jpg)
![WoWScrnShot_103022_163959](https://user-images.githubusercontent.com/18301825/198888061-2d6b8e25-9d3b-44c9-9f2e-3b894c9b6a9d.jpg)
![WoWScrnShot_103022_164008](https://user-images.githubusercontent.com/18301825/198888064-23045a0d-0edc-4b13-97a6-0de3af6ae519.jpg)
![WoWScrnShot_103022_164433](https://user-images.githubusercontent.com/18301825/198888103-0113f462-5aae-444a-9d1f-8a8f6ea18251.jpg)
