### ISSUE TITLE
Не работает цепочка квестов с репой Netherwing для маунта х100

### ISSUE THREAD

**Issue by Traneqq** [wowmw/bugtracker#268]
После сдачи квеста Ally of the Netherwing, npc Mordenai не даёт следующие  квесты  Blood Oath of the Netherwing и In Service of the Illidari. благодаря которым ты получаешь трансформацию в орка и можешь находиться на територии Netherwing Ledge, я прилетал туда, не смотря на то что у меня Exalted после сдачи Ally of the Netherwing и всёравно мобы враждебные ко мне, я не могу делать дейлики. скрин 
 https://cdn.discordapp.com/attachments/906477057846951956/1038995686856871956/WoWScrnShot_110722_041140.jpg

**Comment by Dmitriyres** [comment]
> После сдачи квеста Ally of the Netherwing, npc Mordenai не даёт следующие квесты Blood Oath of the Netherwing и In Service of the Illidari. благодаря которым ты получаешь трансформацию в орка и можешь находиться на територии Netherwing Ledge, я прилетал туда, не смотря на то что у меня Exalted после сдачи Ally of the Netherwing и всёравно мобы враждебные ко мне, я не могу делать дейлики. скрин https://cdn.discordapp.com/attachments/906477057846951956/1038995686856871956/WoWScrnShot_110722_041140.jpg

Добрый день проверяется. Ожидайте.

**Comment by Dmitriyres** [comment]
> После сдачи квеста Ally of the Netherwing, npc Mordenai не даёт следующие квесты Blood Oath of the Netherwing и In Service of the Illidari. благодаря которым ты получаешь трансформацию в орка и можешь находиться на територии Netherwing Ledge, я прилетал туда, не смотря на то что у меня Exalted после сдачи Ally of the Netherwing и всёравно мобы враждебные ко мне, я не могу делать дейлики. скрин https://cdn.discordapp.com/attachments/906477057846951956/1038995686856871956/WoWScrnShot_110722_041140.jpg

Проверил. Оформиляю как баг трекер. Ожидайте исправлений в след обновлениях.

**Comment by Dmitriyres** [comment]
После прохождение Цепочки задания на незервинга -> Залетая на територию драконов а именно Незервингов
https://www.wowhead.com/tbc/faction=1015/netherwing На Персонажа должен накладыватся дебаф орка( что бы враждебные к персонажу орки были дружелюбными)
![image](https://user-images.githubusercontent.com/114337602/200288129-0010315a-6a64-4a10-9cdc-d48e81a3f11f.png)

Фото прилагаю

**Comment by Dmitriyres** [comment]
Аналогично не даёт квесты всё верно.

**Comment by Dmitriyres** [comment]
> После сдачи квеста Ally of the Netherwing, npc Mordenai не даёт следующие квесты Blood Oath of the Netherwing и In Service of the Illidari. благодаря которым ты получаешь трансформацию в орка и можешь находиться на територии Netherwing Ledge, я прилетал туда, не смотря на то что у меня Exalted после сдачи Ally of the Netherwing и всёравно мобы враждебные ко мне, я не могу делать дейлики. скрин https://cdn.discordapp.com/attachments/906477057846951956/1038995686856871956/WoWScrnShot_110722_041140.jpg

Добрый день. День проверил . Все квесты доступны. И работает коректно 
Во вкладке ->Репутация-> Незервинг уберите галочку противник . И Сделайте релог.

**Comment by Traneqq** [comment]
Я понял в чём была моя проблема. У меня небыл изучен Riding artistan за
5000г и по этому квест не давался

пн, 7 нояб. 2022 г. в 14:34, Dmitriyres ***@***.***>:

**Comment by Traneqq** [comment]
спасибо большое

сб, 12 нояб. 2022 г. в 08:24, Lil _One ***@***.***>:
