### ISSUE TITLE
Ашбрингер комбат

### ISSUE THREAD

**Issue by Gensen1** [wowmw/bugtracker#278]
2 перса рядом - ашбрингер вводит в комбат

**Comment by Hentaika** [comment]
Вводит не только если другой перс рядом, но и когда простой моб
https://db.moonwell.su/?spell=28282

> 2 перса рядом - ашбрингер вводит в комбат

**Comment by Hentaika** [comment]
Ещё было бы неплохо проверить, работает ли ивент в скарлете 
![yoda_tea](https://user-images.githubusercontent.com/18301825/203977550-8cef7419-b5ab-45ee-a195-5412fbc6bd33.png)
