### ISSUE TITLE
не работает спел на варе 

### ISSUE THREAD

**Issue by Distimiya6** [wowmw/bugtracker#285]
в общем , у вара есть такой спел как слэм (сокрушение щитом) , собственно проблема заключается в том что спел сам по себе не бьёт и появляется всплывающий текст "нечего рассеивать''

**Comment by Dmitriyres** [comment]
> в общем , у вара есть такой спел как слэм (сокрушение щитом) , собственно проблема заключается в том что спел сам по себе не бьёт и появляется всплывающий текст "нечего рассеивать''

Добрый вечер . Данный баг вы нашли на х5 или на х100 реалме ?

**Comment by Dmitriyres** [comment]
https://www.wowhead.com/ru/spell=198912/%D1%83%D0%B4%D0%B0%D1%80-%D1%89%D0%B8%D1%82%D0%BE%D0%BC#-> Работает коректно. Протестировал несколько раз. 
![image](https://user-images.githubusercontent.com/114337602/206217003-9b586fc7-7dfb-48e6-a081-cd34492b45d8.png)

**Comment by Dmitriyres** [comment]
Аналогично Шилд Слем-<Заклинание -> https://www.wowhead.com/spell=23922/shield-slam
![image](https://user-images.githubusercontent.com/114337602/206217653-e8d5c1a0-8d9a-4784-a43b-a61e64fa7eeb.png)

**Comment by Dmitriyres** [comment]
![image](https://user-images.githubusercontent.com/114337602/206218791-1d68a34b-88c3-450f-a6d0-9c976eaa9a00.png)
Снимает бафы(ефекты тоже коректно)
![image](https://user-images.githubusercontent.com/114337602/206218940-6cd273a4-a132-4a62-b353-9e586c4cc32d.png)
![image](https://user-images.githubusercontent.com/114337602/206219139-20a26271-daa8-4b46-9a29-9ee75bfae228.png)
