### ISSUE TITLE
Spellsteal and nature swiftness. Так же работа спелстила в отношении других спеллов.

### ISSUE THREAD

**Issue by Elzikx** [wowmw/bugtracker#287]
"природная стремительность"  - стоит флаг тип рассеивания "магический". Что по идее означает, что её можно диспелить и пуржить(на сервере так). Спелстилом по идее так же можно воздействовать. 

https://www.wowhead.com/tbc/spell=30449/spellsteal#comments - комментарий By Victrium [on 2007/01/28] (Patch 2.0.6)

https://wowwiki-archive.fandom.com/wiki/Spellsteal - смотрим Patch changes. Обращаем внимание на [Patch 2.1.0] 
 (22-May-2007): Stolen buffs that affect specific spells from the original target's class will no longer have any effect for the mage.

Видео одного известного ютубера/стримера с офф сервера (тбк)
https://www.youtube.com/watch?v=Pg1pD9XS0kw&feature=youtu.be
Тайминг - 6:33 , ставим скорость воспроизведения на 0.25. Видим как маг стилит нс друида в фокусе.

В добавок (просто чтобы понимать, что на пиратках есть такой баг), наткнулся на одну тему. На одном известном сервере есть такой баг репорт, хотя и в версии пандарии. 
https://forum.wowcircle.com/showthread.php?t=574273

Update.
Недавно на бг спелстилом забрал у пала спелл из его талантов https://db.moonwell.su/?spell=20216 
1. При этом этот спелл не даёт магу никакого эффекта, т.к. он только для крита паладиновских спеллов. Но переходит в баффы мага, хотя не должен.
2. При этом спелл висит без времени (хотя все забранные спеллы должны забираться ровно на 2 минуты). Должен спелстилиться, но не вешаться на мага. Так же как и нс.
3. Это развеивает мои мысли по поводу бага некоторых украденных бафов. В числе таких есть баф https://db.moonwell.su/?spell=38905 от нпц https://db.moonwell.su/?npc=20932. Забирается на мага и висит (что в принципе верно именно для этого бафа, т.к. магический спелл аркан школы ) бесконечно, а должен только 2 минуты. К примеру сюда можно добавить "правильную работу украденного бафа" -  щит Астромансера из треша в ТК ( https://db.moonwell.su/?spell=35915 ), такой же как и у мага ( https://db.moonwell.su/?spell=30482 ) , крадётся магом и вешается на 2 минуты.

Вывод:
1. Украденные баффы, влияющие на определенные заклинания из класса первоначальной цели, больше не будут иметь никакого эффекта для мага.
2. "Определённые заклинания"(нс друида и шамана и некоторые другие) не должны передаваться магу, а лишь только забираться у цели. 
3. Все "безвременные" бафы, не влияющие на определённые заклинания из класса цели, должны забираться на 2 минуты. Все "временные бафы" должны забираться на столько, на сколько они действуют и сколько им осталось действовать.

**Comment by Dmitriyres** [comment]
> "природная стремительность" - стоит флаг тип рассеивания "магический". Что по идее означает, что её можно диспелить и пуржить(на сервере так). Спелстилом по идее так же можно воздействовать.
> 
> https://www.wowhead.com/tbc/spell=30449/spellsteal#comments - комментарий By Victrium [on 2007/01/28] (Patch 2.0.6)
> 
> https://wowwiki-archive.fandom.com/wiki/Spellsteal - смотрим Patch changes. Обращаем внимание на [Patch 2.1.0] (22-May-2007): Stolen buffs that affect specific spells from the original target's class will no longer have any effect for the mage.
> 
> Видео одного известного ютубера/стримера с офф сервера (тбк) https://www.youtube.com/watch?v=Pg1pD9XS0kw&feature=youtu.be Тайминг - 6:33 , ставим скорость воспроизведения на 0.25. Видим как маг стилит нс друида в фокусе.
> 
> В добавок (просто чтобы понимать, что на пиратках есть такой баг), наткнулся на одну тему. На одном известном сервере есть такой баг репорт, хотя и в версии пандарии. https://forum.wowcircle.com/showthread.php?t=574273
> 
> Update. Недавно на бг спелстилом забрал у пала спелл из его талантов https://db.moonwell.su/?spell=20216
> 
> 1. При этом этот спелл не даёт магу никакого эффекта, т.к. он только для крита паладиновских спеллов. Но переходит в баффы мага, хотя не должен.
> 2. При этом спелл висит без времени (хотя все забранные спеллы должны забираться ровно на 2 минуты). Должен спелстилиться, но не вешаться на мага. Так же как и нс.
> 3. Это развеивает мои мысли по поводу бага некоторых украденных бафов. В числе таких есть баф https://db.moonwell.su/?spell=38905 от нпц https://db.moonwell.su/?npc=20932. Забирается на мага и висит (что в принципе верно именно для этого бафа, т.к. магический спелл аркан школы ) бесконечно, а должен только 2 минуты. К примеру сюда можно добавить "правильную работу украденного бафа" -  щит Астромансера из треша в ТК ( https://db.moonwell.su/?spell=35915 ), такой же как и у мага ( https://db.moonwell.su/?spell=30482 ) , крадётся магом и вешается на 2 минуты.
> 
> Вывод:
> 
> 1. Украденные баффы, влияющие на определенные заклинания из класса первоначальной цели, больше не будут иметь никакого эффекта для мага.
> 2. "Определённые заклинания"(нс друида и шамана и некоторые другие) не должны передаваться магу, а лишь только забираться у цели.
> 3. Все "безвременные" бафы, не влияющие на определённые заклинания из класса цели, должны забираться на 2 минуты. Все "временные бафы" должны забираться на столько, на сколько они действуют и сколько им осталось действовать.

Добрый день проверю в течение суток.

**Comment by Dmitriyres** [comment]
Нужно более подробно рассматривать этот тикет . Следовательно больше времени. Ожидайте ответа.

**Comment by Gensen1** [comment]
Стилить Nature's Swiftness не позволяет сам клиент. При попытке стила клиент не отправляет никаких опкодов. Изменять 2.4.3 клиент мы не можем, следовательно, исправить не получится. Видимо в 2.5.2 исправили.

Не нашел нигде подтверждения, что бесполезные для мага спеллы должны исчезать из списка бафов, а не переходить магу. 

Добавил максимальную длительность 2 минуты для всех украденных спеллов.

**Comment by Elzikx** [comment]
В ссылке на комментарий с вовхеда написано же, что в отношении "нс" спелстил действует как диспел. И в видео всё четко видно. И это относится к версии до 2.4.3.
Это очень важно в пвп и нужно пробовать это исправить каким-либо способом.
Хотя бы конкретно в отношении нс.
