### ISSUE TITLE
Масла на спд

### ISSUE THREAD

**Issue by Elzikx** [wowmw/bugtracker#288]
https://db.moonwell.su/?item=20749  ,  https://db.moonwell.su/?item=20746 ,  https://db.moonwell.su/?item=22522 ,  https://db.moonwell.su/?item=20750 - добавляют и бонус к хилу и к спд, а должны только к спд.

**Comment by Dmitriyres** [comment]
> https://db.moonwell.su/?item=20749 , https://db.moonwell.su/?item=20746 , https://db.moonwell.su/?item=22522 , https://db.moonwell.su/?item=20750 - добавляют и бонус к хилу и к спд, а должны только к спд.

Добрый день данный баг был найден на х5 Мире?

**Comment by Dmitriyres** [comment]
Проверил действительно так .
Пример
до
![image](https://user-images.githubusercontent.com/114337602/207322029-66092a0e-4eb5-4f87-8167-d5a9fc03e082.png)

после 
![image](https://user-images.githubusercontent.com/114337602/207321977-59128edc-49d1-4e41-9443-19fffcb0a115.png)

**Comment by Gensen1** [comment]
Есть информация, что перечисленные масла всегда добавляли к хилу, даже на БК классик.

**Comment by Elzikx** [comment]
> Есть информация, что перечисленные масла всегда добавляли к хилу, даже на БК классик.

От Telecn (3,677 – 10·13) <Премиум-пользователь> 01.08.2020 (Classic) 
As of 7/31/2020, phase 5, this affects healing power as well. Overall wizard is better than mana oil for paladins.

От [iMathias]  (Обновление 2.4.1)
Does anyone know if spell damage = spell power? I.e. also applies to healing?
I tried this on my lock and my damage and my healing increased so... yes it works on healing as well
Последний раз редактировалось [iMathias] 27.05.2008 (Обновление 2.4.1)


От Gull (2,226 – 15·17) 12.02.2007 (Обновление 2.0.6) [12.02.2007] 	
According to my character sheet, it effects healing aswell.
[24688]  (Обновление 2.0.10)

Confirmed. This does in fact up your healing as well.



Соглашусь, репорт можно отклонить.
