### ISSUE TITLE
Не работает КОЛЬЦО ЛЬДА

### ISSUE THREAD

**Issue by Valakaspwnz** [wowmw/bugtracker#290]
Когда используешь маговское [Кольцо льда] вплотную к мобу, не срабатывает эффект заморозки. То есть, моб подходит вплотную, используешь кольцо льда, отбегаешь, но моб не примораживается к месту, а продолжает бежать за тобой, при том, что на нём висит дебаф от заморозки. В то время как, если использовать его на небольшом расстоянии от моба, он примораживается. 

https://www.wowhead.com/tbc/ru/spell=27088/%D0%BA%D0%BE%D0%BB%D1%8C%D1%86%D0%BE-%D0%BB%D1%8C%D0%B4%D0%B0

Должно быть иначе: кольцо льда примораживает в любом случае и на любом расстоянии, где бы не находился игрок и его цель относительно друг друга.

Можете убедиться на 0:27. https://youtu.be/HSB6DjsUqis

Чтобы воспроизвести баг, необходимо подпустить моба к себе вплотную и скастовать [Кольцо льда]

https://user-images.githubusercontent.com/120419035/207150322-c63bed45-246d-44f6-8dd6-b3b905914130.mp4

**Comment by Dmitriyres** [comment]
> Когда используешь маговское [Кольцо льда] вплотную к мобу, не срабатывает эффект заморозки. То есть, моб подходит вплотную, используешь кольцо льда, отбегаешь, но моб не примораживается к месту, а продолжает бежать за тобой, при том, что на нём висит дебаф от заморозки. В то время как, если использовать его на небольшом расстоянии от моба, он примораживается.
> 
> https://www.wowhead.com/tbc/ru/spell=27088/%D0%BA%D0%BE%D0%BB%D1%8C%D1%86%D0%BE-%D0%BB%D1%8C%D0%B4%D0%B0
> 
> Должно быть иначе: кольцо льда примораживает в любом случае и на любом расстоянии, где бы не находился игрок и его цель относительно друг друга.
> 
> Можете убедиться на 0:27. https://youtu.be/HSB6DjsUqis
> 
> Чтобы воспроизвести баг, необходимо подпустить моба к себе вплотную и скастовать [Кольцо льда]
> 
>  TRIAL____________Wow.2022-12-12.21-28-21-032.1.mp4

Добрый день проверю в течение суток.

**Comment by Dmitriyres** [comment]
Проверил все NPC Морозятся коректно. Проблема именно в этих NPC при использывание заморозки . Они бегут за тобой 
![WoWScrnShot_121322_152233](https://user-images.githubusercontent.com/114337602/207317555-35c798dc-066e-492a-8453-2e8a1105a26a.jpg)
![WoWScrnShot_121322_152248](https://user-images.githubusercontent.com/114337602/207317597-b4d53c92-7ad7-41c5-95d3-b0df529e8964.jpg)
![WoWScrnShot_121322_152452](https://user-images.githubusercontent.com/114337602/207317696-aca18f9f-926a-4e18-a017-d561b8a6a382.jpg)
![image](https://user-images.githubusercontent.com/114337602/207317747-3e7cb47c-2c50-4557-b091-b9b8d496eff7.png)
