### ISSUE TITLE
Master of Subtlety

### ISSUE THREAD

**Issue by Elzikx** [wowmw/bugtracker#291]
https://db.moonwell.su/?spell=31223
Атаки, совершенные в состоянии незаметности, а также в течение 6 сек. после выхода из незаметности, наносят 10% дополнительного урона.
Работает неверно.
Изначально, при первом заходе в стелс, баф есть. При выходе из стелса так же висит 6 секунд. Но:
С вкаченым https://db.moonwell.su/?spell=13975 на 5 очков, имеем кд на вход в стелс 5 секунд.
Тем самым если мы зайдём в стелс в первый раз, выйдем из него и через 5 секунд зайдём снова, баф пропадёт. Отсчёт начинает идти при выходе из стелса и баф не обновляется, если за эти 6 секунд снова зайти в стелс. По прошествии 6 секунд, "находясь в стелсе" баф исчезает. 
Точно так же при использовании https://db.moonwell.su/?spell=26889.
Если выйти из стелса, использовать ваниш, то попав в стелс, баф пропадёт. Отсчёт так же начинает идти с момента выхода и ровно 6 секунд.

Баф должен обновляться при заходе в стелс.
На других серверах этот баф можно было лицезреть среди бафов игрока. Т.к. на сервере включена видимость пассивных бафов, считаю правильным сделать так же видимым этот баф среди остальных бафов игрока.

**Comment by Dmitriyres** [comment]
> https://db.moonwell.su/?spell=31223 Атаки, совершенные в состоянии незаметности, а также в течение 6 сек. после выхода из незаметности, наносят 10% дополнительного урона. Работает неверно. Изначально, при первом заходе в стелс, баф есть. При выходе из стелса так же висит 6 секунд. Но: С вкаченым https://db.moonwell.su/?spell=13975 на 5 очков, имеем кд на вход в стелс 5 секунд. Тем самым если мы зайдём в стелс в первый раз, выйдем из него и через 5 секунд зайдём снова, баф пропадёт. Отсчёт начинает идти при выходе из стелса и баф не обновляется, если за эти 6 секунд снова зайти в стелс. По прошествии 6 секунд, "находясь в стелсе" баф исчезает. Точно так же при использовании https://db.moonwell.su/?spell=26889. Если выйти из стелса, использовать ваниш, то попав в стелс, баф пропадёт. Отсчёт так же начинает идти с момента выхода и ровно 6 секунд.
> 
> Баф должен обновляться при заходе в стелс. На других серверах этот баф можно было лицезреть среди бафов игрока. Т.к. на сервере включена видимость пассивных бафов, считаю правильным сделать так же видимым этот баф среди остальных бафов игрока.

Проверю в течение суток.

**Comment by Dmitriyres** [comment]
В TBC клиенте Саблети талант можно вкачать только на 3 поинта
![image](https://user-images.githubusercontent.com/114337602/207323998-5676346c-44f4-4351-8802-1b1f812b9e00.png)
Остальное проверяется.

**Comment by Elzikx** [comment]
Да на 3 принта, там опечатка. Смысл репорта вообще в другом.

**Comment by Dmitriyres** [comment]
> Да на 3 поинта, там опечатка. Смысл репорта вообще в другом.

Ожидайте исправления в след обновлениях.
