### ISSUE TITLE
Входящий спелл по трупу

### ISSUE THREAD

**Issue by Elzikx** [wowmw/bugtracker#292]
Весьма неприятный баг, в основном ощущаемый в пвп, в частности на бг. Объясню своими словами.
Любой спелл, кастующийся, не кастующийся(мгновенный) не должен "проходить в труп". Кроме спеллов имеющих анимацию полёта и скастованных до того, как цель мертва.  При этом кастующийся спелл не должен быть скастованным, если цель мертва. Можно начать кастовать когда цель ещё жива. Но не должно быть успешного докастовывания, если при завершении каста, цель уже мертва.

На сервере:

Любой мгновенный спелл (и магический и физический) съедаются трупом. Цель бывает уже мертва, но всё так же можно какой-либо инстант каст нажать и он пройдёт в труп. При этом бывает так, что можно "начать кастовать" в момент "смерти цели"(т.е. когда цель только что умерла, но не в живую цель, а уже в мёртвую) и что более удивляет, докастовать в неё(в труп), что просто полнейшая чушь.
При этом вешается кд на спелл, если он его имеет (кд самого спелла, а не гкд). При этом происходят затраты энергии, ярости, маны.

Если надо будет, покажу это в лайве.

**Comment by Dmitriyres** [comment]
> Весьма неприятный баг, в основном ощущаемый в пвп, в частности на бг. Объясню своими словами. Любой спелл, кастующийся, не кастующийся(мгновенный) не должен "проходить в труп". Кроме спеллов имеющих анимацию полёта и скастованных до того, как цель мертва. При этом кастующийся спелл не должен быть скастованным, если цель мертва. Можно начать кастовать когда цель ещё жива. Но не должно быть успешного докастовывания, если при завершении каста, цель уже мертва.
> 
> На сервере:
> 
> Любой мгновенный спелл (и магический и физический) съедаются трупом. Цель бывает уже мертва, но всё так же можно какой-либо инстант каст нажать и он пройдёт в труп. При этом бывает так, что можно "начать кастовать" в момент "смерти цели"(т.е. когда цель только что умерла, но не в живую цель, а уже в мёртвую) и что более удивляет, докастовать в неё(в труп), что просто полнейшая чушь. При этом вешается кд на спелл, если он его имеет (кд самого спелла, а не гкд). При этом происходят затраты энергии, ярости, маны.
> 
> Если надо будет, покажу это в лайве.

Добрый день . Проверил. Ожидайте фикса  в след обновлениях.
