### ISSUE TITLE
Криво отображаются модельки(игроков)

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#294]
Фото прикрепляю
![image](https://user-images.githubusercontent.com/114337602/207313210-d10c098b-5ccb-42a2-bb74-fd90c7dac9f9.png)
![image](https://user-images.githubusercontent.com/114337602/207313913-adce5cef-b0ba-47f0-937c-af5c8fff45fb.png)
![image](https://user-images.githubusercontent.com/114337602/207313886-0ba2ff99-9f79-4be4-96da-370767d0fe68.png)

**Comment by Gensen1** [comment]
Известно как воспроизводится?

**Comment by Dmitriyres** [comment]
> Известно как воспроизводится?

уточняю

**Comment by Dmitriyres** [comment]
> Известно как воспроизводится?

Уточняю

**Comment by Elzikx** [comment]
Хотел сделать такой же репорт. Да имеется такая проблема. Либо ферал стоит спиной к боссу, либо рядом стоящий кастер кастует спиной к боссу.

**Comment by Dmitriyres** [comment]
Закрою и перенесу в другой баг репорт. Есть очередной баг отчёт.
