### ISSUE TITLE
auto attack/shoot delayed by spell-caused gcd

### ISSUE THREAD

**Issue by NTRW333** [wowmw/bugtracker#297]
example: Shadow Word: Death + Shoot (Wand)
it takes [global cooldown + wand attack speed] seconds for the wand to shoot
https://www.wowhead.com/tbc/spell=5019

**Comment by Dmitriyres** [comment]
> example: Shadow Word: Death + Shoot (Wand) it takes [global cooldown + wand attack speed] seconds for the wand to shoot https://www.wowhead.com/tbc/spell=5019

Добрый день . Проверю в течение суток.

**Comment by Dmitriyres** [comment]
При использывание данного заклинания имеется задержка (гкд) на выстрел(удар вандом) примерно 5 секунд .
Нужно убрать это гкд что бы можно было использывать ванд

**Comment by NTRW333** [comment]
Not fixed. Attacks are still delayed by GCD. @Dmitriyres

**Comment by Dmitriyres** [comment]
> Not fixed. Attacks are still delayed by GCD. @Dmitriyres

Not be plan fixed. Admins say work corect. Thats why this closed.

**Comment by NTRW333** [comment]
unforch
