### ISSUE TITLE
negative leeway

### ISSUE THREAD

**Issue by NTRW333** [wowmw/bugtracker#298]
https://clips.twitch.tv/BlushingAbnegateMetalANELE
https://clips.twitch.tv/AnimatedLachrymoseMangoPipeHype
the clips are from classic wow, but it also existed in the original (can be seen in old videos)
i dont know if "negative leeway" is an appropriate description. my understanding is that the attacker is facing the target because their "circles" touch.

**Comment by Dmitriyres** [comment]
> https://clips.twitch.tv/BlushingAbnegateMetalANELE https://clips.twitch.tv/AnimatedLachrymoseMangoPipeHype the clips are from classic wow, but it also existed in the original (can be seen in old videos) i dont know if "negative leeway" is an appropriate description. my understanding is that the attacker is facing the target because their "circles" touch.

Holla im be test this soon. Thx for wait <3

**Comment by Dmitriyres** [comment]
We already know about this bug . Be wait fix soon . Ty <3

**Comment by Dmitriyres** [comment]
https://github.com/wowmw/bugtracker/issues/294 
Прикрепляю здесь

**Comment by NTRW333** [comment]
@Dmitriyres @Gensen1 "Targets can no longer be attacked at close range if you turned back to it."
I think you misunderstood the issue. Attacking a target that is slightly behind you should be possible. This helps especially in PVP - it prevents the cheesy tactic of running through your opponent before the spell casting ends.

**Comment by Gensen1** [comment]
@NTRW333 What the point of your report then?

**Comment by NTRW333** [comment]
It didn't work at the time of report (atleast for spells).

**Comment by NTRW333** [comment]
> @NTRW333 What the point of your report then?

so are there any plans to fix this? or are you just gonna close another legit report, as usual?
