### ISSUE TITLE
Хоггер

### ISSUE THREAD

**Issue by pristn** [wowmw/bugtracker#300]
На хоггера не действует замедление от фрост болта.
И я пытался его овцевать, он из овцы выходил практически сразу.

**Comment by pristn** [comment]
Я был 12 или 13 вобщем больше по лвлу.

**Comment by pristn** [comment]
Пытался только что на 15м его убить. Нереал. Бегает под фрост болтом как заведенный. Он точно не  замедляется.

**Comment by Dmitriyres** [comment]
> Пытался только что на 15м его убить. Нереал. Бегает под фрост болтом как заведенный. Он точно не замедляется.

Хорошо спасибо . Если подтверджу отправлю на фикс.

**Comment by Dmitriyres** [comment]
> Пытался только что на 15м его убить. Нереал. Бегает под фрост болтом как заведенный. Он точно не замедляется.

Овцуется норм не с 1 попытки но довольно нормально с 2-3 раза попробывал несколько раз. И норм 
Вот с фростболтом надо что то делать . Отправляю на фикс.

**Comment by Dmitriyres** [comment]
При использивание заклинания ФростБолт Ранг 2 магом NPC->https://www.wowhead.com/classic/npc=448/hogger
Не замедляется на 40% а бежит за тобой как было . Требуется фикс.

**Comment by pristn** [comment]
Проверьте пожалуйста работает этот баг с другой элитой или это только проблема Хоггера. Спасибо.

**Comment by Dmitriyres** [comment]
> Проверьте пожалуйста работает этот баг с другой элитой или это только проблема Хоггера. Спасибо.

Хорошо проверю. Если что создам новый баг отчёт.
