### ISSUE TITLE
Resist Retribution Aura x5

### ISSUE THREAD

**Issue by profilertox** [wowmw/bugtracker#303]
Аура не должна иметь сопротивления, если моб не имун к холи в целом

https://wowwiki-archive.fandom.com/wiki/Retribution_Aura?so=search

```
Since there is no resistance to Holy damage, the paladin's enemies will always take full damage (unless they fully resist it by the base miss chance).
```
![1](https://user-images.githubusercontent.com/120781146/208237037-1d878557-b991-4b81-915b-700e16d97eb3.png)

**Comment by Gensen1** [comment]
Since there is no resistance to Holy damage, the paladin's enemies will always take full damage **(unless they fully resist it by the base miss chance)**.
