### ISSUE TITLE
Дроп с редких мобов

### ISSUE THREAD

**Issue by pristn** [wowmw/bugtracker#304]
С них не падает зеленка. Убил трех уже. Дроп как с обычного моба.

**Comment by pristn** [comment]
УПД. Убил Рарников в Редридже. 20+ С них точно должна падать.

**Comment by Dmitriyres** [comment]
> С них не падает зеленка. Убил трех уже. Дроп как с обычного моба.

Добрый день. Проверю в течение суток.

**Comment by pristn** [comment]
Доп. Заметил, что если у Рарника есть своя собственная вещь- именная. Как например клык Нараксиса. Она падает. Не знаю 100% ли, но упала.

**Comment by Gensen1** [comment]
> Должна падать 1=зелёнка с шансом 100%

Пруфы?

**Comment by Dmitriyres** [comment]
> > Должна падать 1=зелёнка с шансом 100%
> 
> Пруфы?

Пересмотрев . Очень много разных источников. Пришёл к выводу что . Ошибся. Дроп зелёнок не ровно 100% а довольно меньше. 100% это нововедение пираток.
Закрываю багтрекер.
