### ISSUE TITLE
"Незаметность" отключается после перезахода в игру х5

### ISSUE THREAD

**Issue by AmawaH** [wowmw/bugtracker#307]
(https://www.wowhead.com/tbc/ru/spell=1784/%D0%BD%D0%B5%D0%B7%D0%B0%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C)
Незаметность как и любой другой баф/дебаф и подобно стойкам воина и форм друида обязан сохраняться после перезахода в игру.
Все аддоны выключены для чистоты эксперимента

В стелсе ухожу в релог
![В стелсе ухожу в релог](https://i.imgur.com/Q8H665F.jpg)
Зашел в игру:
![зашел в игру](https://i.imgur.com/txCoyvE.jpg[/img])

**Comment by Dmitriyres** [comment]
Добрый день . Проверю в течение суток.

**Comment by Gensen1** [comment]
SPELL_AURA_MOD_SHAPESHIFT (стойки и формы) + SPELL_AURA_MOD_STEALTH намеренно снимаются в коде ядра. Не просто так было это сделано. Однако неизвестно зачем. Нужны пруфы.

//Player::_SaveAuras()

**Comment by Dmitriyres** [comment]
После длительной проверки. Инвиз должен сниматся и все другие ефекты. Пруфы взяты с актуала.
