### ISSUE TITLE
Shadow Word Death

### ISSUE THREAD

**Issue by NTRW333** [wowmw/bugtracker#309]
Damage on the target is instant, and because there is no batching, it pushes back the enemy spell for longer than the backlash delay so its not possible to break enemy spells like Polymorph.
The same is probably true for Seal of Blood and other backlash effects.

**Comment by Dmitriyres** [comment]
Holla . Will be test soon.

**Comment by Elzikx** [comment]
Не подкреплённые слова. 
Посмотрите видосы uzb где он играет пристом. В каждый раз швд рефлектит назад через время, что может выбить из успешно скастованной овцы. Сейчас швд работает так, как должен.

**Comment by NTRW333** [comment]
I'm not sure why this is Rejected and what exactly Elzikx said, but this is definitely not working correctly. The only time you can break Polymorph as priest is if the damage on the mage is absorbed, so there is no pushback. @Dmitriyres
