### ISSUE TITLE
Не собирается кожа при лимите профессии 

### ISSUE THREAD

**Issue by Atrecom** [wowmw/bugtracker#312]
![image](https://user-images.githubusercontent.com/44858756/208301848-05b9af83-ba41-4810-876b-ea920bcbcffd.png)
75/75
при попытке собрать кожу с моба ничего не происходит, только проигрывается анимация

**Comment by Dmitriyres** [comment]
Добрый день . Проверю в течение суток.

**Comment by Dmitriyres** [comment]
![image](https://user-images.githubusercontent.com/114337602/208302955-80bcc36b-bb95-4a72-a84f-872aafec1aa7.png)

**Comment by Atrecom** [comment]
я даже видео сниму. до вступления в силу последних обновлений всё было нормально. кликов мышкой не видно, но по трупу они есть
https://www.youtube.com/watch?v=BQamp20QrT0&ab_channel=Atrecom
да, наверное, это не так важно, но...

**Comment by Dmitriyres** [comment]
> я даже видео сниму. до вступления в силу последних обновлений всё было нормально. кликов мышкой не видно, но по трупу они есть https://www.youtube.com/watch?v=BQamp20QrT0&ab_channel=Atrecom да, наверное, это не так важно, но...

Возможно проблем в самом мобе. Проверил огромное количество NPC со всех снялась  кожа.
