### ISSUE TITLE
Книга талантов

### ISSUE THREAD

**Issue by Atrecom** [wowmw/bugtracker#313]
Всё еще нельзя использовать на 18м уровне
![image](https://user-images.githubusercontent.com/44858756/208303652-27b621de-80f5-40fd-bf99-0801ed79aeab.png)

**Comment by Dmitriyres** [comment]
> Всё еще нельзя использовать на 18м уровне ![image](https://user-images.githubusercontent.com/44858756/208303652-27b621de-80f5-40fd-bf99-0801ed79aeab.png)

 Обновления должны вступить после рестарта. Если не вступят в силу. Оставлю открытим . Пока что.

**Comment by Atrecom** [comment]
Рестарт уже был, сразу после поста.
Спасибо за внимание.

**Comment by Dmitriyres** [comment]
Проверил после очистки кеша досих пор стоит для уровня 70. Ожидайте хотфикса в блийшее время.
