### ISSUE TITLE
Первый маунт

### ISSUE THREAD

**Issue by pristn** [wowmw/bugtracker#314]
Просьба сделать дешевле первого маунта. На х5 35г+10г-45!голд за маунта сумма не подъемная. Спасибо.

**Comment by Dmitriyres** [comment]
> Просьба сделать дешевле первого маунта. На х5 35г+10г-45!голд за маунта сумма не подъемная. Спасибо.

Это не сайт для Предложений :) 
С подобной информацией и предложением обратитесь в дискорд .
Фото Прикрепляю 
![image](https://user-images.githubusercontent.com/114337602/208306401-af8aa54e-bba0-4320-b53c-35a14b135722.png)
