### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#316]
Баги.
- не работает скининг (бесконечно скинет, нету прогресса/полоски скининга)
- очень мало травы
- очень мало руды
- мало квестовых вещей, которых нужно подобрать с земли 
создалось впечатление что ВЫ все урезали раз в 5 (наверно из-за Х5 рейта ? )
- не сохраняется последние действия в чате, например если я писал в общий чат /6, то игра сбрасывает всегда на чат "/сказать" а не в общий , постоянно приходится дописывать /6 чтобы попасть в общий чат

**Comment by Dmitriyres** [comment]
1Пунк Известно Ожидайте фикса.
2-3 пунк 
Зависит от количества людей в локации.

**Comment by narcoshka** [comment]
Как может зависеть количество (не путать с респом) цветков или камней?  Оно работает, вы проверяли?

**Comment by Dmitriyres** [comment]
> Как может зависеть количество (не путать с респом) цветков или камней? Оно работает, вы проверяли?

Точная информация . Уточняется. Проблема со снятием должна быть устранена.

**Comment by Dmitriyres** [comment]
> Баги.
> 
> * не работает скининг (бесконечно скинет, нету прогресса/полоски скининга)
> * очень мало травы
> * очень мало руды
> * мало квестовых вещей, которых нужно подобрать с земли
>   создалось впечатление что ВЫ все урезали раз в 5 (наверно из-за Х5 рейта ? )
> * не сохраняется последние действия в чате, например если я писал в общий чат /6, то игра сбрасывает всегда на чат "/сказать" а не в общий , постоянно приходится дописывать /6 чтобы попасть в общий чат

Шанс будет увеличен. На траву/руду/Предметы В След обновлению. Спасибо за ожидание.
