### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by pristn** [wowmw/bugtracker#318]
Не линкуются в чат некоторые вещи( зеленого качества) . Например Бандитский плащ, Коралловое кольцо, Зеленотканые сандали.

**Comment by Dmitriyres** [comment]
> Не линкуются в чат некоторые вещи( зеленого качества) . Например Бандитский плащ, Коралловое кольцо, Зеленотканые сандали.

Проверил не линкуются названия с длинным сочитанием символом от 25 и больше.

**Comment by pristn** [comment]
Будет ли это исправлено? На русской раскладке почти всё длинней 25и символов

**Comment by Elzikx** [comment]
Предположу, что проблема кроется на стороне сервера. Дело точно не в клиенте или аддонах.

**Comment by narcoshka** [comment]
на русских серверах всегда линковались вещи, какой бы длины они не были. Тут не линкуются длинные.

**Comment by Dmitriyres** [comment]
> на русских серверах всегда линковались вещи, какой бы длины они не были. Тут не линкуются длинные. И их много, вы что -нибудь предпримете?

Ожидание ответа от Администрации.

**Comment by narcoshka** [comment]
После исправления (патча) - не работает линк

**Comment by Elzikx** [comment]
Кэш чистили после обновления? 
Конкретно какую вещь не линкует. Отпишите сюда ссылку или id вещи.
