### ISSUE TITLE
Терзаемый высокорожденный

### ISSUE THREAD

**Issue by pristn** [wowmw/bugtracker#319]
Данный моб при атаке персонажа вызывает критическую ошибку и выбрасывает из игры с ошибкой #132 (0x85100084) Выкинуло 3 раза подряд именно на нем.

**Comment by Dmitriyres** [comment]
> Данный моб при атаке персонажа вызывает критическую ошибку и выбрасывает из игры с ошибкой #132 (0x85100084) Выкинуло 3 раза подряд именно на нем.
Проверю в течение суток.

**Comment by Dmitriyres** [comment]
Данный баг известен ожидайте фикса

**Comment by Dmitriyres** [comment]
https://github.com/wowmw/bugtracker/issues/311
