### ISSUE TITLE
Нереальный урон

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#320]
В Сумеречном лесу (ДаркШир), на кладбище есть гули с названием "Гнилая нежить" После смерти остаются 2 червяка, они имеют свыше 700 хп и кушают медведя (с половиной хп),  на  4-6 левела выше них, за 4-6 секунд 
Это слишком много для таких мобов

**Comment by Dmitriyres** [comment]
Проверяется . Подскажите каким уровнем вы были примерно.

**Comment by AmawaH** [comment]
Полагаю "мишка был" 30 лвла.
Речь идет о мобе ["Гнилая нежить" ](https://www.wowhead.com/tbc/ru/npc=948/%D0%B3%D0%BD%D0%B8%D0%BB%D0%B0%D1%8F-%D0%BD%D0%B5%D0%B6%D0%B8%D1%82%D1%8C#english-comments) Который при смерти вызывает одного или двух [Кусеница](https://www.wowhead.com/wotlk/ru/npc=2462/%D0%BA%D1%83%D1%81%D0%B5%D0%BD%D0%B8%D1%86%D0%B0#english-comments) которые судя по [коментарию](https://www.wowhead.com/tbc/npc=948/rotted-one#comments:id=2834679)
 `От rogierpoep 14.08.2007 (Обновление 2.1.3) Тема: "Re: Rotted One" they spawn 2 lvl 23-25 mobs with 1 hp who attack you`
имеют 1 НР. Урон полагаю либо тоже 1, либо не больше чем от моба-спанера "Гнилая нежить"

**Comment by narcoshka** [comment]
Да, мишка был 30й уровень, а мобы 23-24 уровень

**Comment by Dmitriyres** [comment]
> Да, мишка был 30й уровень, а мобы 23-24 уровень

Хорошо спасибо . Проверю в течение суток.

**Comment by Dmitriyres** [comment]
После убийства NPC->https://www.wowhead.com/tbc/ru/npc=948/%D0%B3%D0%BD%D0%B8%D0%BB%D0%B0%D1%8F-%D0%BD%D0%B5%D0%B6%D0%B8%D1%82%D1%8C#english-comments -> вызывает 2 NPC->https://www.wowhead.com/wotlk/ru/npc=2462/%D0%BA%D1%83%D1%81%D0%B5%D0%BD%D0%B8%D1%86%D0%B0#english-comments
Исправить их HP показатель с 700 + на Единицу.
Урон входящий остаётся(Пропадают со временем) вполне можно выжить
