### ISSUE TITLE
Багается счётчик квеста на убийство NPC X5

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#322]
Выполняя задание https://db.moonwell.su/?quest=826 Багается счётчик (нельзя сдать квест) 
![image](https://user-images.githubusercontent.com/114337602/208717736-e0f31e37-9690-42e5-a937-cf34a251b735.png)
![image](https://user-images.githubusercontent.com/114337602/208717761-dfafda8d-b141-49c9-9c81-519ba929b14b.png)
Фото прилагаю

**Comment by Elzikx** [comment]
При убийстве и поднятии головы Залазана https://db.moonwell.su/?item=4866 в последнюю очередь - счётчик проклятых шаманов с 8 перескакивает на 9.
![WoWScrnShot_122122_082039](https://user-images.githubusercontent.com/120413127/208839755-4c973999-014f-4c1b-8c92-796fa04e60ad.jpg)
При убийстве первого проклятого троля https://db.moonwell.su/?npc=3207  после 8 убитых троллей-вудуистов  https://db.moonwell.su/?npc=3206 и уже поднятой головы Залазана https://db.moonwell.su/?item=4866 счётчик проклятых троллей перескакивает в книге на 2, хотя убиваем только первого.
![WoWScrnShot_122122_081730](https://user-images.githubusercontent.com/120413127/208840004-c68a79b4-e27b-4cb5-b936-e138eb9dbb58.jpg)
При этом, если убить или просто добавить голову Залазана в сумки, счётчик проклятых троллей изменяется на 1.
![WoWScrnShot_122122_082548](https://user-images.githubusercontent.com/120413127/208840228-148cf173-5db7-40d6-a0c5-c6751df7dda7.jpg)
При этом, если убить 8 троллей-вудуистов, 7 проклятых троллей и поднять голову Залазана(при поднятии головы кол-во проклятых троллей с 7 изменится на 8), квест будет считаться выполненым. Но сдать квест не получится.
![WoWScrnShot_122122_090424](https://user-images.githubusercontent.com/120413127/208842629-a1d299ed-aeaa-4cae-8184-0eb6b872c9cb.jpg)

**Comment by Elzikx** [comment]
Полагаю, что в первом сообщении на скринах было убито 7 проклятых троллей и затем поднята голова Залазана, в следствие счётчик перескочил на 8, но квест сдать не получается. Баг есть.

**Comment by Hentaika** [comment]
> Полагаю, что в первом сообщении на скринах было убито 7 проклятых троллей и затем поднята голова Залазана, в следствие счётчик перескочил на 8, но квест сдать не получается. Баг есть.

Сначало я подобрала голову, а потом убивала троллей.
Встречала похожий баг https://github.com/wowmw/bugtracker/issues/244, тоже квест, где надо убить и подобрать голову.
