### ISSUE TITLE
Исправить предмет (DEV x5)

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#324]
Если использывать сброс кд (каким то образом)
Используя https://www.wowhead.com/classic/item=16022/arcanite-dragonling (должен быть только 1)
Можно настакивать кучу дракончиков
![image](https://user-images.githubusercontent.com/114337602/208725496-50ac9b77-1839-44c8-a955-72a9e844ee9b.png)
Фото прилагаю

**Comment by Elzikx** [comment]
Такое невозможно. 20-ти минутный кулдаун не сбрасывается. Только гм командой.
Баг на сброс кд был давно исправлен. А все кулдауны которые больше 15-ти минут - не сбрасываются никаким образом.
