### ISSUE TITLE
ЧАТ

### ISSUE THREAD

**Issue by Nintendik** [wowmw/bugtracker#326]
При использовании чата, нужно всегда использовать команды по типу /g гильдия /p группа и т.д тоесть, если я пишу в пати и хочу быстро ответить в этом же канале пати при использовании клавиши Enter тоесть начать печатать текст ставиться канал по умолчанию /s сказать. Функция забаганна на все каналы, а также неработает быстрый ответ даже если прописать команду /w - быстрый ответ поледнему написавшему в ПМ. Клиент игры чистый без единого аддона.

**Comment by AmawaH** [comment]
Ванильное и БКшное UI жуткое убожество (да простят меня еще те олдовые Близы которые стольдавно это клепали). Нормальная практика использовать аддоны. К примеру pfUI как у меня (да да, многим эта сборка противна до рвоты, но мне удобно). Тут пришиты много полезных вещей, в том числе и чат. Потому даже не знаю есть ли смысл сию тему рассматривать как баг.

**Comment by Elzikx** [comment]
В чём собственно баг? Ваши хотелки на быстрый ответ в том же чате осуществляются с помощью аддонов.
В оригинале вы всегда должны обозначать перед сообщением канал, в котором собираетесь написать сообщение.

**Comment by pristn** [comment]
Должен запоминаться последний канал, в которым ты общаешься и энтером он и должен вызываться. Но у некоторых пользователей при нажатии Энтер чат всегда сбрасывается на \Сказать.

**Comment by Elzikx** [comment]
Пробовал без аддонов на свежем аккаунте. Всё работает. Запоминается чат группы, рейда.
/w работает только если дописывать никнейм. Вызывается "R" по умолчанию.
Проблема не на стороне сервера.

**Comment by narcoshka** [comment]
уже писал такое - исправлять админы не хотят

**Comment by Elzikx** [comment]
Скачал другой клиент, всё запоминается. Проблема либо в битых клиентах, либо в отсутствии разрешения на запись для текстового документа куда сохраняются настройки чата и т.д.
Проблема не на стороне сервера. 
Если у вас не сохраняется, пользуйтесь аддонами. К тому же оригинальный чат морально устарел, а модификации аддонов куда приятнее для глах.
Репорт можно закрыть.
