### ISSUE TITLE
Не вешается баф при взятие квеста (Dev x5)

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#327]
При взятии задания https://db.moonwell.su/?npc=17391 должен вешать баф https://db.moonwell.su/?spell=30424.

**Comment by Elzikx** [comment]
Сам квест https://db.moonwell.su/?quest=9540 берётся и сдаётся. Скрипт нпц https://db.moonwell.su/?npc=17391 корректный.
Между первой и второй фазой должен вешать на игрока баф https://db.moonwell.su/?spell=30424
Баф не вешает. 
Как должно быть https://www.youtube.com/watch?v=I8_UkGNM_2w

**Comment by kuzinsun** [comment]
FIXED
