### ISSUE TITLE
Долгий респаун монстра

### ISSUE THREAD

**Issue by Welloshe** [wowmw/bugtracker#328]
В начальной локации троллей\орков квестовый скорпион Саркот, респаунится свыше 5 минут.
У него край респ минута

**Comment by Elzikx** [comment]
https://db.moonwell.su/?npc=3281
Респаун точно такой же, какой указан в базе.

**Comment by narcoshka** [comment]
Если точно такой же как указан в базе, то почему трупы исчезают быстро (почти минута) и почему респавн многих мобов быстрый?

**Comment by Elzikx** [comment]
> Если точно такой же как указан в базе, то почему трупы исчезают быстро (почти минута) и почему респавн многих мобов быстрый?
> 
> Вы противоречите сами себе. Сервер х5, значит респавн быстрый. Зачем придерживаться к тому что рассчитано на х1?

1. Ссылку на конкретного нпц, который быстро респаунится.
2. По поводу деспауна трупов репорт есть, в разбработке.
3. В чём противоречие? Рейты на сервер указаны ниже.
![Новый рисунок](https://user-images.githubusercontent.com/120413127/209073578-4da8a9ef-2cbc-4fa5-90ca-c53f36b21158.jpg)
