### ISSUE TITLE
Убрать Появление NPC DEV(X5)

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#329]
При атаке NPC - > http://wowdata.ru/npc.html?id=4966
![image](https://user-images.githubusercontent.com/114337602/208986212-9c813211-0be9-4652-8049-926e47cae8f7.png)
![image](https://user-images.githubusercontent.com/114337602/208986275-3f883d40-55d1-4282-a552-dbd993156104.png)
Побегав с ним к палатке и обратно опуская уровень HP До критического уровня он кричит в чат Фразу
![image](https://user-images.githubusercontent.com/114337602/208986907-747e6a74-9fec-40a9-bd87-db6b3443c089.png)
И к нему на помощь прибегают 3 NPC 
Фото прилагаю
Если сделать доп урон по данному NPC 
прибегают ещё 3
как указано на фото

![image](https://user-images.githubusercontent.com/114337602/208986846-ba8e2de0-367c-4c52-b63d-b83cde0f5ec6.png)

**Comment by Elzikx** [comment]
При доведении до критической отметки, **Хендел отагривается и становится дружелюбным. Его невозможно атаковать.** Прибегают 3 нпц на помощь, происходит диалог и квест засчитывается. Собственно так и получилось.
Единственно что можно, это отменить этот квест и взять заново в момент когда происходит диалог. Два стража рядом с палаткой и Хендел вновь станут враждебными, пока Хендел не достигнет критической отметки здоровья. Далее всё происходит так же, как описано выше. 
Можно конкретнее описать в чём заключается баг?

**Comment by Dmitriyres** [comment]
> При доведении до критической отметки, **Хендел отагривается и становится дружелюбным. Его невозможно атаковать.** Прибегают 3 нпц на помощь, происходит диалог и квест засчитывается. Собственно так и получилось. Единственное что можно, это отменить этот квест и взять заново в момент когда происходит диалог. Два стража рядом с палаткой и Хендел вновь станут враждебными, пока Хендел не достигнет критической отметки здоровья. Далее всё происходит так же, как описано выше. Можно конкретнее описать в чём заключается баг? https://db.moonwell.su/?quest=1324 исправен и работает корректно.

Дело в том что . Эти 3 NPC которые прибегают на помощь. Атакуют тебя. И появляются не 1 раз а несколько.

**Comment by Elzikx** [comment]
Данный квест был багнутый ещё в актуале.
Я перепроверил его. При нанесении урона по Хенделу, он и 2 стражника начинают атаковать и становятся враждебными. При доведении до критической отметки здоровья Хендела, он и 2 стража перестают атаковать и становятся дружелюбными. Леди Джайна и двое других пояаляются уже дружелюбными. Воспроизвести их враждебность не удалось.
Попробую другой рассой, лвлом. Результат отпишу.

**Comment by Dmitriyres** [comment]
![image](https://user-images.githubusercontent.com/114337602/209164119-869cf7d9-274b-4f26-af93-f43a2c51bcbf.png)
После фразы как он кричит(мы делаем доп удар) и бегут новые( и сразу же агрятся на вас)

**Comment by Dmitriyres** [comment]
Работает для Альянс стороны нормально(если у вас есть в наличие заклинание)
Для Орды (просто не отАгривается) можно заевейдить.
