### ISSUE TITLE
Disenchant

### ISSUE THREAD

**Issue by P0ppl3r** [wowmw/bugtracker#334]
Runned Copper Gauntlets, Runned Copper Belt are not uncommon items after crafting and therefore they cannot be disenchanted.

**Comment by Elzikx** [comment]
Everything is right. And on the server exactly so.
![WoWScrnShot_122422_140643](https://user-images.githubusercontent.com/120413127/209435559-a80b89cd-f09e-45c4-b60f-51d0dc4f9645.jpg)
![WoWScrnShot_122422_140640](https://user-images.githubusercontent.com/120413127/209435590-0b8408dc-afb3-4d35-85a0-0366c8ceac66.jpg)

**Comment by P0ppl3r** [comment]
White items dont have stats. Only starting from green item there are stats

**Comment by Elzikx** [comment]
belt - https://www.wowhead.com/tbc/ru/item=2857/%D1%80%D1%83%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BC%D0%B5%D0%B4%D0%BD%D1%8B%D0%B9-%D0%BF%D0%BE%D1%8F%D1%81
![54063808-135dc100-41dd-11e9-8e2e-ccd6743c613d](https://user-images.githubusercontent.com/120413127/209446871-ae39d12d-32fb-4c28-a033-3e8bb2551900.png)
Gauntlest - https://www.wowhead.com/tbc/ru/item=3472/%D1%80%D1%83%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BC%D0%B5%D0%B4%D0%BD%D1%8B%D0%B5-%D1%80%D1%83%D0%BA%D0%B0%D0%B2%D0%B8%D1%86%D1%8B

Да действительно, после бк были изменены и добавлены статы. Статов быть не должно.

**Comment by Gensen1** [comment]
There were only 3 items in the game. Fixed
```
+-------+------------------------+---------+
| entry | name                   | quality |
+-------+------------------------+---------+
|  2857 | Runed Copper Belt      |       1 |
|  3472 | Runed Copper Gauntlets |       1 |
|  3480 | Rough Bronze Shoulders |       1 |
+-------+------------------------+---------+
```
