### ISSUE TITLE
bobi96

### ISSUE THREAD

**Issue by bobi966** [wowmw/bugtracker#335]
have bug with group loot , and you can see other person loot in corpse

**Comment by bobi966** [comment]
in the starting area of ​​the orcs and trolls there is a cave in which you attack monsters that are on the upper floor while you fight on the lower floor and they beat and kill you through the wall.

**Comment by Elzikx** [comment]
Hello! Need more information describing your bug (links, coordinates, screenshots)
https://github.com/wowmw/bugtracker - for review.
