### ISSUE TITLE
Квест The Earthbinder спавнит НПС под текстурами земли

### ISSUE THREAD

**Issue by Atrecom** [wowmw/bugtracker#336]
Добрый день.
Квест https://www.wowhead.com/tbc/quest=10349/the-earthbinder
требует начать диалог с https://www.wowhead.com/tbc/npc=19294/earthbinder-galandria-nightbreeze
однако НПС  под землей
![image](https://user-images.githubusercontent.com/44858756/209443036-32dd0d99-ec7d-474c-be2c-c75f4e0d9791.png)

**Comment by Elzikx** [comment]
Добрый. Баг подтверждён. Ожидайте исправления.
