### ISSUE TITLE
Тотемы(Dev x5)

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#338]
При атаке определённых NPC- > данные NPC вызывают тотем 
![image](https://user-images.githubusercontent.com/114337602/209444719-349f843a-c56b-457c-b51f-8d785b19a4d5.png)
 И они бегают за тобой куда ты не пошёл с твоей целью(нужно закрепить) появление тотема в 1 месте.

**Comment by Dmitriyres** [comment]
![Uploading image.png…]()
 Пример

**Comment by Elzikx** [comment]
1. https://www.wowhead.com/ru/npc=1144/%D0%B7%D0%BD%D0%B0%D1%85%D0%B0%D1%80%D1%8C-%D0%B8%D0%B7-%D0%BA%D0%BB%D0%B0%D0%BD%D0%B0-%D0%BC%D0%BE%D1%88%D0%BE%D0%B3%D0%B3#abilities
Должен призывать через n-oe время тотем. Работает верно.
2. Тотем призывается, но не входит в бой. Просто стоит и никак не воздействует. Входит в бой, только если по нему нанести урон. Работает не верно. Тотем должен входить в бой без нанесённого по нему урона и воздействовать абилкой.
https://www.wowhead.com/tbc/ru/spell=3827/%D0%BE%D0%B1%D0%B5%D1%80%D0%B5%D0%B3-%D0%BB%D0%B5%D0%BD%D0%BE%D1%81%D1%82%D0%B8#english-comments
3. https://www.wowhead.com/tbc/ru/npc=1144/%D0%B7%D0%BD%D0%B0%D1%85%D0%B0%D1%80%D1%8C-%D0%B8%D0%B7-%D0%BA%D0%BB%D0%B0%D0%BD%D0%B0-%D0%BC%D0%BE%D1%88%D0%BE%D0%B3%D0%B3#abilities
Сам знахарь работает верно. Кастует свой перечень абилок.
4. Сам тотем должен быть статичен. Работает не верно. Если по нему нанести урон, он войдёт в комбат с целью и будет преследовать и передвигаться за ней.
