### ISSUE TITLE
Квест "Take down Tethyr!"(х5)

### ISSUE THREAD

**Issue by XenusONE** [wowmw/bugtracker#339]
1. Квест https://www.wowhead.com/tbc/quest=11198/take-down-tethyr не работает. Мортиры, которыми нужно обстреливать Тетир, нельзя использовать.
2. Как должно работать https://www.youtube.com/watch?v=JKXS6Ty1Tw4

**Comment by Makcumys** [comment]
Удалось воспроизвести на тесте. Сам квест рабочий. Сообщите дополнительную информацию.
Tethyr был призван или нет? Либо он находился уже в воде? Либо он был уже мёртв? Был ли он вообще?
Появились ли дополнительные нпц возле мортир?(они помогают в процессе квеста)
Как вариант, попробуйте ещё раз выполнить квест. Отмените и возьмите заново через время. Чтобы в воде не было Tethyr.

**Comment by Makcumys** [comment]
![WoWScrnShot_122622_135343](https://user-images.githubusercontent.com/120413127/209546139-318ef12d-d092-4071-9419-0a8986eace77.jpg)

**Comment by XenusONE** [comment]
Уже был в воде, без трети хп, с серым ником(как будто его кто-то другой бил). НПЦ возле мортир не было.

**Comment by Makcumys** [comment]
> Уже был в воде, без трети хп, с серым ником(как будто его кто-то другой бил). НПЦ возле мортир не было.

В таком случае вам нужно найти в игре гма или создать тикет в дискорде с указанием вашей проблемы. Она решается респавном этого моба.
