### ISSUE TITLE
Квест "The end of the desrters"(х5)

### ISSUE THREAD

**Issue by XenusONE** [wowmw/bugtracker#340]
1. Квест https://www.wowhead.com/tbc/quest=11134/the-end-of-the-deserters . Не засчитывает критерий квеста, после победы над НПЦ. Во время боя, около 10%-15% хп, НПЦ зеленеет, и, по идее, должен квест выполнится.
2. Как должно работать https://www.youtube.com/watch?v=7USO7ySdSOg

**Comment by Makcumys** [comment]
Проверил на тесте, работает корректно. После кат. сцены нпц исчезает и вам нужно доделать квест. А именно: 
![123](https://user-images.githubusercontent.com/120413127/209548504-67285ed3-750b-4759-a3e5-a338cfc8858a.jpg)
![WoWScrnShot_122622_141627](https://user-images.githubusercontent.com/120413127/209548517-273809d3-66e7-430e-922d-5647cd78482c.jpg)
После этого квест засчитывается.

**Comment by Hentaika** [comment]
> Проверил на тесте, работает корректно. После кат. сцены нпц исчезает и вам нужно доделать квест. А именно: ![123](https://user-images.githubusercontent.com/120413127/209548504-67285ed3-750b-4759-a3e5-a338cfc8858a.jpg) ![WoWScrnShot_122622_141627](https://user-images.githubusercontent.com/120413127/209548517-273809d3-66e7-430e-922d-5647cd78482c.jpg) После этого квест засчитывается.

А ничего что это другой квест?)))
