### ISSUE TITLE
не рабочий квест

### ISSUE THREAD

**Issue by mutilatelol** [wowmw/bugtracker#343]
название квеста  Assassination Plot
проблема: в  локации тысяча игл бегает кентавр месенджер с него выпадает письмо юзаеш письмо он дает данный квест  этот квест принимает нпц kanati greycloud.  так вот он не принимает квест он вообще ничего не делает.

**Comment by Makcumys** [comment]
Квест рабочий, перепроверено на тесте. Проблема с самим нпц, который багается при каких-то обстоятельствах.
Для решения проблемы свяжитесь с гмом в игре, либо создайте тикет в дискорде с описанием вашей проблемы.
