### ISSUE TITLE
2 чата,  2 проблемы

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#344]
Я вам писал по поводу как будем общаться с иностранцами и как будут они видеть русские ники? Вы не захотели или если точнее вы проигнорировали то что я ВАМ писал. А сейчас когда проблема возникла, вы сделали глупую вещь - сделать 2 чата. На самом деле оно не решает проблему а еще больше загоняет. Чтобы пойти в данж, нужно искать группу. Русские или Иностранцы -все равно кого брать. Но искать в двух каналах или смотреть два канала чтобы найти группу, это ооочень не удобно. Вы сами себе создаете проблему с этими чатами. А нужно просто было сделать так, чтобы все  создавали ники на англ. языке. 
Вторая проблема - совместная группа, совместная гильдия между ордой и альянсом. Когда вне группы то игроки между собой Пвпшутся или Впвпшутся, находясь в гильдии или вне. Это как бы не нормально. Я уж молчу про совместные группы, из-за нехватки людей на сервере, совместный чат между ордой и альянсом, когда один кого то убил в игре (впвп) а тот вылил свои эмоции в общий чат на него. Не зря придумали раздельный чат Близы, чтобы не было такого. Закончили данж, вышли с группы, и тут же друг друга прирезали=)

P.S. Вещи с длинным названием - НЕ ЛИНКУЮТСЯ!!! что вы исправили?

**Comment by Gensen1** [comment]
В багтрекере рассматриваются баги, а не предложения.

1) По поводу совместных групп не понятно что вы имеете в виду. Все работает как должно.
2) Какие именно предметы не линкуются?

**Comment by narcoshka** [comment]
Все вещи не линкуются, которые имеют длинные названия(случайные называния), вы писали что исправили. Не исправлено

**Comment by Gensen1** [comment]
Остались еще некоторые айтемы с нюансами, которые я не учел. Будет исправлено после рестарта.
