### ISSUE TITLE
Багается квест иногда

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#346]
Не рабочий квест "конец вражеской пропаганде"  (https://www.wowhead.com/tbc/ru/quest=11134/%D0%BA%D0%BE%D0%BD%D0%B5%D1%86-%D0%B2%D1%80%D0%B0%D0%B6%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%B3%D0%B0%D0%BD%D0%B4%D0%B5) Альянс. 

Нужный НПС на корабле, должен сразиться с нами, а потом на лоу хп стать дружелюбным. и мы его арестовываем. Квест засчитывается.

По факту, данный НПС ведет себя всегда по разному,  - либо становясь дружным, продолжает бить и потом исчезает, он не юзабельный.

- либо он говорит свой нужный монлог, вроде идет с нами, но исчезает и квест не засчитывается. Пробовали в соло, так и в группе

**Comment by Makcumys** [comment]
https://github.com/wowmw/bugtracker/issues/340
