### ISSUE TITLE
квест

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#347]
Я вам писал про кривых червей (которые вы не исправили) в квесте "Гадость это ваше Запределье", где нужно собрать 6 ящиков. Так вот их всего 4 шт и респ 5 минут. Это нормально?? их было штук 8-10
Квест "какого работать на гоблинов" не работают в группе (не засчитывается в группе). Респаун невидимых нпц (нпц появляется в клетке и тут же исчезает) в клетке, 5 минут.

**Comment by Makcumys** [comment]
https://github.com/wowmw/bugtracker
1 баг - 1 репорт.
Будьте добры, чётко излагайте баг с описанием (с предоставлением ссылок на нпц, предметы, квесты и т.д.)
Перечитайте ссылку ещё раз. Следующие репорты с кучей текста будут удаляться без рассмотрения.
