### ISSUE TITLE
Не засчитывается этап квеста: "Конец вражеской пропаганде"

### ISSUE THREAD

**Issue by wolfar1980** [wowmw/bugtracker#354]
https://www.wowhead.com/ru/quest=27213/%D0%BA%D0%BE%D0%BD%D0%B5%D1%86-%D0%B2%D1%80%D0%B0%D0%B6%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%B3%D0%B0%D0%BD%D0%B4%D0%B5 Не работает эта часть квеста. После победы над Гависом Серым Щитом квест не засчитывается.

**Comment by Makcumys** [comment]
Добрый день. Вы предоставили ссылку на данный квест который был переделан в версии выше тбк.
Вот ответ на то, как сделать этот квест в текущей версии игры 
https://github.com/wowmw/bugtracker/issues/340
