### ISSUE TITLE
Бой через текстуры.

### ISSUE THREAD

**Issue by Ratmus** [wowmw/bugtracker#358]
Добрый день! Баг в общем в чем. Можно заагрить моба через тексты автоатакой и стоять его бить, при этом он не может юзать в тебя свои способности, при этом нужно стоять на одном месте, если чуть шевельнуться, то моб выбегает и уже бой нормально идёт.

**Comment by Makcumys** [comment]
Добрый день. Бить автоатакой через текстуры можно было и на оффе. Даже на арене это работало, если доставал рейндж милиатаки до цели.
По поводу моба - укажите ссылкой моба, который не атакует.

**Comment by Ratmus** [comment]
А, ну если это норма, то пусть😁 не знал. А на счет моба, так почти все так. Спасибо за информацию 👍🏼
