### ISSUE TITLE
Смерть после дисконекта

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#363]
Когда игрока дискает (по каким либо причинам) в бою, и в это время бьет его моб или не бьет (в инсте как пример) то после захода в игру - этот игрок уже мертвый. Это большая проблема, если на боссах (как у нас получилось в Шадов Лабиринте) умер дисконектила игрока и он зашел уже мертвым

**Comment by Gensen1** [comment]
Если игрок выходит из игры (закрытие клиента, дисконнект, потеря интернета - не важно) в бою, то он умирает. Так и должно быть, иначе можно проводить различные азубы.

**Comment by narcoshka** [comment]
вообще то нет, в любой игре, в любом аддона при релоге игрок живой, если он успел зайти, пока моб его не убил, или если моба сагрил втрой игрок. Откуда у вас такия инфа - неясно. 17 лет играю в ВОВ и такое у на Вашем сервере впервые слышу

**Comment by narcoshka** [comment]
очень интересно, даже как не правдоподобно
