### ISSUE TITLE
Использование книги талантов (dual spec)

### ISSUE THREAD

**Issue by Chleftain** [wowmw/bugtracker#364]
Друид. 5/42/14 ферал.
Просто ради интереса решил опробовать книгу, в итоге спекнув таланты решил вернуть свой спек в сток.
Абилка "Увечье" для кота и для медведя с панели пропала, в книге тоже не было. Пришлось еще раз учить у тренера за деньги соответственно:)

**Comment by Dmitriyres** [comment]
> Друид. 5/42/14 ферал. Просто ради интереса решил опробовать книгу, в итоге спекнув таланты решил вернуть свой спек в сток. Абилка "Увечье" для кота и для медведя с панели пропала, в книге тоже не было. Пришлось еще раз учить у тренера за деньги соответственно:)

Добрый вечер. Извините за ожидание . Талант пропадает при каждом сбросе талантов ?

**Comment by Chleftain** [comment]
Доброй ночи. Эта проблема была единожды. Только когда использовал впервые. После того как заново изучил спеллы и юзал респек, спеллы уже остались на месте--Отправлено из мобильной Яндекс Почты28.12.2022, 02:37, "Dmitriyres" ***@***.***>:

Друид. 5/42/14 ферал. Просто ради интереса решил опробовать книгу, в итоге спекнув таланты решил вернуть свой спек в сток. Абилка "Увечье" для кота и для медведя с панели пропала, в книге тоже не было. Пришлось еще раз учить у тренера за деньги соответственно:)

Добрый вечер. Извините за ожидание . Талант пропадает при каждом сбросе талантов ?
