### ISSUE TITLE
Не работает задание

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#366]
"Экзорцизм над полковником Джулсом" -> https://www.wowhead.com/tbc/ru/quest=10935/%D1%8D%D0%BA%D0%B7%D0%BE%D1%80%D1%86%D0%B8%D0%B7%D0%BC-%D0%BD%D0%B0%D0%B4-%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%BE%D0%BC-%D0%B4%D0%B6%D1%83%D0%BB%D1%81%D0%BE%D0%BC
Указано, что нужно для начала экзорцизма поговорить с Анахорет Берада, но с ним не удается поговорить, не открывается окно для разговора.

**Comment by Makcumys** [comment]
Воспроизвёл на тесте. Всё работает корректно.
