### ISSUE TITLE
Лут в героиках

### ISSUE THREAD

**Issue by Srtsrtsrt** [wowmw/bugtracker#367]
С ластов в 5 ппл героиках падает 1 вещь + 1 примал.
Должно падать 2 вещи редкого качества, 1 примал гарантированно, а также 1 вещь эпического качества и 1 ювелирный камень с некоторым шансом.

**Comment by Makcumys** [comment]
Перепроверил все героики. С шансом падает 1 либо 2 вещи одинакового или разного качества. Лут в порядке.
