### ISSUE TITLE
Alt Tab

### ISSUE THREAD

**Issue by Mosal2** [wowmw/bugtracker#374]
When I alt tab I cannot go to desktop and r
![Screenshot (184)](https://user-images.githubusercontent.com/117767995/209773313-9db313b7-1a5b-46e1-baf0-a082938780b5.png)
return to the game (dropped to 4fps). Only empty streets and I cannot move normally.

**Comment by Gensen1** [comment]
Hello. Check your system settings. This issue is not related to in game bugs.

**Comment by Mosal2** [comment]
Ok, thanks. What should I check in my system or do?
