### ISSUE TITLE
Пещера полёта в приозерье

### ISSUE THREAD

**Issue by FollowerWind** [wowmw/bugtracker#382]
В приозерье, есть квест на убийств войнов чёрной горы (Или как-то так), они живут в пещере, в этой пещере есть квест на солдата которого надо вывести из пещеры, однако. При взятии квеста он улетает куда-то вверх и пропадает. лол)

Все мобы входящие в центр пещеры начинают ходить по воздуху улетая куда-то вверх в итоге теряя агр возвращаясь к себе на позицию но уже вися в воздухе.

**Comment by Dmitriyres** [comment]
Добрый день о проблеме извесно идёт поиск решений .
