### ISSUE TITLE
Тухлое яйцо араккоа

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#389]
https://x5.moonwell.su/?item=30500
Шанс собрать его 16% согласно - https://www.wowhead.com/tbc/ru/item=30500/%D1%82%D1%83%D1%85%D0%BB%D0%BE%D0%B5-%D1%8F%D0%B9%D1%86%D0%BE-%D0%B0%D1%80%D0%B0%D0%BA%D0%BA%D0%BE%D0%B0
На сервере в базе показывает 100% https://x5.moonwell.su/?item=30500 
Хотя собирается далеко не со 100% шансом, но так и должно быть.
Что исправить:
Некорректное отображение шанса в базе.

**Comment by Gensen1** [comment]
Объектов несколько https://x5.moonwell.su/?search=Rotten+Arakkoa#objects
То яйцо, которое должно выдать айтем со 100% вероятностью, спавниться случайно по пулу.
