### ISSUE TITLE
Welcoming the Wolf Spirit

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#392]
Выполняя задание в локации -> Лес Терокар.
Мы встречаемся с заданием ->https://www.wowhead.com/tbc/quest=10791/welcoming-the-wolf-spirit
Если убежать на огромное расстояние от NPC Примерно в другую часть локации или в растояние 300 ярдов то задание багается(а точнее NPC котому мы не можешь здать)
Помогает только Респавн NPC

**Comment by kuzinsun** [comment]
Fixed.
Исправлено.

@Dmitriyres просьба перепроверить на новой сборке после релиза. У себя проверял при разных ситуациях (тепался в других локации, убегал, улетал, пытался запустить несколько раз ивент, пытался запускать разными персонажами) - все ок.
