### ISSUE TITLE
Spirit Healer

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#395]
Если Умереть в Глубинах Чёрной горы (BRD) нас выбрасывает к неправильному ангелу
![image](https://user-images.githubusercontent.com/114337602/210102968-928a3d5b-befb-4d9b-9cd5-d8ead7a7f8a0.png)
Фото прилагаю.
Как должно быть 
Должно выбрасывать дух к другому ангелу в локацие Searing Gorge

**Comment by Hentaika** [comment]
Не пойму что за локация на скрине. Но всегда выбрасывало в Burning Steps, куда следует.
