### ISSUE TITLE
NPC missing

### ISSUE THREAD

**Issue by kongasdrakos** [wowmw/bugtracker#400]
the priest trainer npc in the Northshire abbey does not exist (in moonwell x5)

![WoWScrnShot_123022_134457](https://user-images.githubusercontent.com/93923588/210165443-bba9e022-6963-4819-9bd1-015e0d938241.jpg)

**Comment by kuzinsun** [comment]
FIXED

Greetings, kongasdrako! 

Thanks for the report. The NPC was on the second floor, which was a mistake. Moved this NPC to the ground floor.

Have a nice game.
