### ISSUE TITLE
Detect traps passive displayed in Buffs

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#402]
Bug for Moonwell x5:
Detect Traps as a passive shouldn't be displayed in Buff section.

How to reproduce:
- Create a rogue
- Get some levels
- Train Detect Traps passive ability

P.S.
There are more passives like Parry or Dodge, that are not displayed. Detect Traps shouldnt be displayed at all in Buffs section.
![detectingTraps](https://user-images.githubusercontent.com/49869412/210208722-2c23cbba-ec92-4e7a-b36c-117c81ee3f10.png)

**Comment by Makcumys** [comment]
Hello! This is a feature of the server and the passive abilities are visible. Made to understand the performance of many players of certain passive abilities (for example, as hit from the Draenei)
