### ISSUE TITLE
Bug or Feature? Quest: [Boiling Blood]

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#404]
Hello,

Quest: Boiling Blood in Hellfire Peninsula.
People get stuck here, If you click on Cauldron, you actually get into it, and you cannot get out. Took me 2mins of jumping to get out.
And what are the red crystals all around it? What's the purpose?

Thanks.

![bugOrfeature](https://user-images.githubusercontent.com/49869412/210223770-8c052e60-5c77-4e7b-83c8-262c47a76fa0.png)

**Comment by Makcumys** [comment]
Hello! This is a bug and it has already been fixed. Will be applied in the next update
