### ISSUE TITLE
Приходить пустий ящик за голосування

### ISSUE THREAD

**Issue by Fardoser** [wowmw/bugtracker#406]
Вже другий день підряд приходить пустий ящик за голосування за сервер x5
![WoWScrnShot_010323_191442](https://user-images.githubusercontent.com/121890248/210408063-6b7d73bf-daae-457f-90ec-5573473708fa.jpg)

**Comment by Makcumys** [comment]
https://x5.moonwell.su/?item=20366
Имеет содержимое с маленьким шансом выпадения.
