### ISSUE TITLE
Усталость в воде работает не правильно

### ISSUE THREAD

**Issue by XandrKhv** [wowmw/bugtracker#407]
Исправьте работу усталости в воде.
На данный момент любое нахождение в воде приводит героя к усталости и последующей смерти, даже без движения.
Даже находясь в воде уже трупом, будет опять срабатывать усталость и труп умрёт повторно (как бы смешно это не звучало).

**Comment by Makcumys** [comment]
Усталость срабатывает тогда, когда вы отплываете за пределы допустимого радиуса плавания.. И будет срабатывать до тех пор, пока вы не вернётесь в допустимый радиус плавания.
Всё работает так как и должно.

**Comment by XandrKhv** [comment]
> Усталость срабатывает тогда, когда вы выплыли за пределы допустимого радиуса плавания. И будет срабатывать до тех пор, пока вы не вернётесь в допустимый радиус плавания. Всё работает так как и должно.

Как то, что труп умирает повторно, может быть правильно ?
