### ISSUE TITLE
Missing enchanting recipes in trainers [x5]

### ISSUE THREAD

**Issue by Spartanv** [wowmw/bugtracker#409]
Enchanting recipes missing from "learn list" in trainer:
Enchant Shield - Resilience
Small Prismatic Shard

Source:
https://www.wowhead.com/tbc/spell=44383/enchant-shield-resilience
https://www.wowhead.com/tbc/spell=42615/small-prismatic-shard#taught-by-npc

**Comment by Makcumys** [comment]
Will become available from the 3rd phase

**Comment by Spartanv** [comment]
This is not how it worked in TBC classic. Gatekeeping such enchants just makes game experience worse. Even Blizzard released that in phase 1 straight ahead.
