### ISSUE TITLE
Shattered Halls - few issues

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#415]
Shattered Halls:
- Mobs are sometimes facing opposite side while hitting a player. Animation related to direction of hitting is broken.
- Half dungeon through, on the sides there are Shattered Hand Centurion and Shattered Hand Gladiators training. When they reach 50% of hp, then they should be "pull-able". Here, instead, they just reset and bug out and restore hp.
The whole trick here is that you should be able to pull these mobs when they are lower hp, but unfortunately not possible right now.
- 1st boss can be pulled through door with hunter's pet.
- Shattered Hand Heathen mob hits twice per 1 attack. Should be normal 1 atack and not like he has a mini windfury proc.

**Comment by Dmitriyres** [comment]
> Shattered Halls:
> 
> * Mobs are sometimes facing opposite side while hitting a player. Animation related to direction of hitting is broken.
> * Half dungeon through, on the sides there are Shattered Hand Centurion and Shattered Hand Gladiators training. When they reach 50% of hp, then they should be "pull-able". Here, instead, they just reset and bug out and restore hp.
>   The whole trick here is that you should be able to pull these mobs when they are lower hp, but unfortunately not possible right now.
> * 1st boss can be pulled through door with hunter's pet.
> * Shattered Hand Heathen mob hits twice per 1 attack. Should be normal 1 atack and not like he has a mini windfury proc.

We know about this problem. U need be wait more time for fix this . Thx <3

**Comment by Gensen1** [comment]
1) Will be fixed
2) Tested - they're not evaded when reaching 50% hp. Need proper description.
3) Known issue
4) He's using Bloodthirst, which has different CD with meele attacks
