### ISSUE TITLE
Black Moras - 2 issues

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#416]
- Last boss should drop 2 items instead of 1 item
- Spawn time on small mobs when fighting Rift Lords is inconsistent. Sometimes we've seen 3 big mobs spawn within a 10sec timeframe, sometimes we had 1 big mob in 10sec.

**Comment by Dmitriyres** [comment]
> * Last boss should drop 2 items instead of 1 item
> * Spawn time on small mobs when fighting Rift Lords is inconsistent. Sometimes we've seen 3 big mobs spawn within a 10sec timeframe, sometimes we had 1 big mob in 10sec.

Olla . Check Info on website about drop item in p1.
