### ISSUE TITLE
Bloody imp-ossible!

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#421]
Задание -> https://db.moonwell.su/?quest=10924
Работает не правильно у класса охотника.
При использывание квестового предмета -> https://db.moonwell.su/?item=31815 призывается бес который должен собирать кровь с пригуан.
Но беса считает 2 петомца у охотника и квест не работает.
Если отозвать петомца и призвать беса то будет работать.
Требуется -> что бы защитывало при наличие петомца у охотника.

**Comment by Gensen1** [comment]
Проблема не в пете, а в радиусе, в котором скрипт квестового моба ищет импа. Будет исправлено.
