### ISSUE TITLE
Животные заповедников

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#422]
Выполняя задание -> https://db.moonwell.su/?quest=10427 , игроку даётся квестовый предмет ->https://db.moonwell.su/?item=29817 для этого нам нужно опустить NPC До уровня 20% и потом нажать предмет . Но проблема в том что мы не можем атаковать данных NPC->
https://www.wowhead.com/tbc/npc=20610/talbuk-doe
проблема решается только рестартом.

**Comment by Gensen1** [comment]
Не могу воспроизвести. Мобы атакуются и усыпляются без проблем. Как входят в сон, становятся неатакуемыми. Через 60 сек снова становятся атакумыми.

**Comment by Hentaika** [comment]
> Не могу воспроизвести. Мобы атакуются и усыпляются без проблем. Как входят в сон, становятся неатакуемыми. Через 60 сек снова становятся атакумыми.

Козочки должны иметь связывающий пак скрипт, например, если атаковать одну, может позвать другую. Он не рабоает. Полагаю проблема может быть в этом.

Я выполняла квест, было несколько пачек, какие то можно было атаковать, какие то нет.

**Comment by Gensen1** [comment]
Воспроизвести так и не удается, но фикс должен исправить проблему.
