### ISSUE TITLE
Отсутствие рецептов

### ISSUE THREAD

**Issue by narcoshka** [wowmw/bugtracker#424]
Не секрет, что многие рецепты как за репутацию, так и просто в профах вырезаны по не известным причинам. Причем некоторые из них существовали в классике и перенесены в БК и их вырезали (пример: 2% агронабора на перчатки были в классике, добавили в БК за репутацию Нижнего Города и его там нет). 
Особенно касается кулинарии, где прокачка 275 стопаяется из-за того что у вендора рецептов на различное мясо - НЕТ. 
Но самое интересное то, что по не объяснимым причинам есть веши которые должны быть начиная со 2й фазы, а доступны уже сейчас., например вещи которые можно сделать в Огириле (дроп с мобов) и некоторые другие.

Вам не кажется что это глупо?

**Comment by SecurityDetachment** [comment]
Прогрессив реалм предполагает такие изменения. Чарки - вы можете выбить в Анкираже, либо ждать нужной фазы для покупки у вендора.
Понятие 1-2 фаза слишком размыто, это по сути один и тот же патч.
