### ISSUE TITLE
 Plans: Ragesteel Shoulders

### ISSUE THREAD

**Issue by maximuuss** [wowmw/bugtracker#425]
I've been trying to drop Plans: Ragesteel Shoulders for a long time, and all the other 3 pieces I already droped, but this Plans: Ragesteel Shoulders is taking too long, so far so good. after 1000 mobs I killed I dropped the wrong recipe, when I saw that it was the wrong Plans I  took a screenshot at the time so that I could prove it, since this mob does not drop Plans: Ragesteel Helm and this was the one that dropped, please help me, it took hours dedicated to drop this recipe and unfortunately it came wrong, as I said I have proof and screenshot of the exact moment that the mob dropped the  wrong recipe.
![plans wrong](https://user-images.githubusercontent.com/122139414/211130963-e5d84898-4c6e-4539-9cdb-a2f63cdc8ef1.jpg)
![plans](https://user-images.githubusercontent.com/122139414/211130990-428b6f67-b4e5-4358-aa4d-89af42fe7bf5.jpg)

**Comment by maximuuss** [comment]
I've leveled up from 68 to 70 just killing those mobs to get the drop, i took about 7 days farming 3 to 4 hours a day. please I need those shoulders.

**Comment by Kapsulalkr** [comment]
that's why u just stood there the this week? lol

theres a bunch of people talking about those on the general chat.

**Comment by Hentaika** [comment]
https://moonwell.su/ru/progressive?info=item_drop

**Comment by Dmitriyres** [comment]
Dont drop in phase 1
