### ISSUE TITLE
Insignia 17k honor??

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#430]
Apparently insignia at vendor for horde in Orgrimmar is 16983 honor.
This has to be a mistake. For 15 years on private servers, Insignia was never above 8k honor.

**Comment by sasadubi** [comment]
![17kinsignia](https://user-images.githubusercontent.com/49869412/211174087-9c3d7f65-b7bf-450c-bf9d-0a2c0bb6ea89.png)

**Comment by NTRW333** [comment]
https://wowpedia.fandom.com/wiki/Medallion_of_the_Horde_(rare)?oldid=1597194

[By najshu on 2008/05/14](https://www.wowhead.com/tbc/item=28240/medallion-of-the-horde#comments:id=287882) (Patch 2.4.1)		
Medaillon of the Alliance and Medaillon of the Horde prices have been lowered to 8 000 honor with patch 2.4.2.

**Comment by sasadubi** [comment]
@NTRW333  There are ton of reasons why private servers were running 2.4.3 state of patch. Because it was most stable, fair, and most reasonable. Moonwell can do progressive patches, but they should've told us then.

P.S.
![243](https://user-images.githubusercontent.com/49869412/211188027-30f83f0e-6d47-4318-9359-fa3dd6d63281.png)

**Comment by sasadubi** [comment]
So we are calling it 2.4.3, but ton of things are not actually 2.4.3.
It's like buying something in store, on shelf price says 15 bucks, but you go to pay, and it's 23 bucks.
Moonwell has to work on their transparency if arguments are gonna be eg: "hey it's added in 2.4.2"

**Comment by Gensen1** [comment]
Hello. Prices are changed according to the progression https://moonwell.su/ru/progressive
