### ISSUE TITLE
Engi head not in game

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#432]
Hello,

We need clarification on overall Sunwell server standpoint when it comes to patching.
Server advertises as 2.4.3, but yet there are ton of things that are present in a state of earlier patch.
What does 2.4.3 actually refers to?

Main topic of this is described in title of ticket.
Engineering epic head is not ingame even after t4 release, myself and plenty of my guildies would like clarification on what's 2.4.3 for Moonwell server? And why is not engi head ingame?

![engiHead](https://user-images.githubusercontent.com/49869412/211193926-4d814afd-7ad7-489b-ae2b-20f676702b59.png)

**Comment by Gensen1** [comment]
Hello. 

Moonwell is a version 2.4.3 server, but at the moment x5 is following the progress described on this page https://moonwell.su/ru/progressive?info=craft
