### ISSUE TITLE
Зараженные саблезубы

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#433]
https://db.moonwell.su/?quest=4506 - квест
Даётся https://db.moonwell.su/?item=12565 который используется в https://db.moonwell.su/?object=300025.
С помощью https://db.moonwell.su/?item=12565 вызывается https://db.moonwell.su/?npc=9937
https://db.moonwell.su/?npc=9937 - отсутствует скрипт.
Котёнок призывается, в чате пишется один раз (то что на скрине 3, это для перепроверки) что он должен сделать. Но он этого не делает. Просто призывается и всё.
![WoWScrnShot_010823_183329](https://user-images.githubusercontent.com/120413127/211208291-76fe3545-004d-45fd-b064-c7863ead6068.jpg)

Как должно быть https://www.youtube.com/watch?v=XMxrTr8MnG4

**Comment by Dmitriyres** [comment]
https://github.com/wowmw/bugtracker/issues/388 Прикреплю здесь (свой закрыл)
