### ISSUE TITLE
Фиал виденья Талваша

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#435]
Цепочка квестов.
3-ий квест - https://db.moonwell.su/?quest=2200. Берётся у https://db.moonwell.su/?npc=6826. В нём даётся https://db.moonwell.su/?item=7667. Сдаётся квест - https://db.moonwell.su/?npc=6912.
4-и квест - https://db.moonwell.su/?quest=2201 берётся у https://db.moonwell.su/?npc=6912 и должен сдаваться https://db.moonwell.su/?item=7667 (предмету который даётся в 3 квесте). 
Вместо этого сдаётся нпц, который начинает 3-ий квест.

https://db.moonwell.su/?item=7667 - используется корректно, но предмет не завершает и не начинает следующий квест.

https://db.moonwell.su/?quest=2201 - должен сдаваться предмету https://db.moonwell.su/?item=7667 и этот предмет должен начинать https://db.moonwell.su/?quest=2204

https://www.wowhead.com/tbc/ru/quest=2201

**Comment by kuzinsun** [comment]
FIXED
