### ISSUE TITLE
баг із здачею квесту.

### ISSUE THREAD

**Issue by Fardoser** [wowmw/bugtracker#437]
квест "одежды духа волка" не можу його здати .
![WoWScrnShot_010923_120137](https://user-images.githubusercontent.com/121890248/211283293-15028a4a-2dd1-4501-b526-90b74fbb2e59.jpg)

**Comment by Dmitriyres** [comment]
Создайте игровой тикет. В дискорде . Head GM реснёт вам Данного NPC и вы сможете здать его
