### ISSUE TITLE
Квест на тотем земли.

### ISSUE THREAD

**Issue by Shanguy124** [wowmw/bugtracker#439]
![1111111](https://user-images.githubusercontent.com/122325852/211433270-1caf8e2a-15f8-4cb8-a84f-5fce0fe2525a.png)
![1111111](https://user-images.githubusercontent.com/122325852/211433359-625af581-2d31-42b8-a436-d04444cbb788.png)
Взял квест у NPC - Канага заклинатель земли, npc=5887, не смог его выполнить дальше, вызвал элементаля земли, но квеста у него не оказалось. Отменил задание но повторно у Канаги его взять уже не получилось, ибо квест пропал. Докачался до 70 , до сих пор нет тотема. Кэш чистил, не помогло. 
У других игроков спрашивад, ничего подобного у них небыло. Возможно проблема в клиенте игры ( скачиваю заново, буду смотреть) Думаю проблема не со стороны сервера. Возможно ли просто выслать на почту тотем земли?

**Comment by Hentaika** [comment]
> ![1111111](https://user-images.githubusercontent.com/122325852/211433270-1caf8e2a-15f8-4cb8-a84f-5fce0fe2525a.png) ![1111111](https://user-images.githubusercontent.com/122325852/211433359-625af581-2d31-42b8-a436-d04444cbb788.png) Взял квест у NPC - Канага заклинатель земли, npc=5887, не смог его выполнить дальше, вызвал элементаля земли, но квеста у него не оказалось. Отменил задание но повторно у Канаги его взять уже не получилось, ибо квест пропал. Докачался до 70 , до сих пор нет тотема. Кэш чистил, не помогло. У других игроков спрашивад, ничего подобного у них небыло. Возможно проблема в клиенте игры ( скачиваю заново, буду смотреть) Думаю проблема не со стороны сервера. Возможно ли просто выслать на почту тотем земли?

Ну как бы квест на тотем земли берётся у своей расы, что ты тауреном забыл у орков и троллей?
https://x5.moonwell.su/?quest=1519
