### ISSUE TITLE
Спи спокойно, гронн

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#440]
Выполняя задание -> https://x5.moonwell.su/?quest=10800
нам даётся квестовый предмет -> https://db.moonwell.su/?item=31403
по данному заданию нам нужно усыпить NPC-> https://db.moonwell.su/?npc=20216 данным порошком(но он имунный)
нужно исправить что бы данный порошочек усыплял данного NPC

**Comment by kuzinsun** [comment]
@Dmitriyres не смог воспроизвести. Попробуй с чисткой кэша.

**Comment by Dmitriyres** [comment]
> @Dmitriyres не смог воспроизвести. Попробуй с чисткой кэша.

Всё так же имунен. Я же не глупый
