### ISSUE TITLE
Paladins casting BoP on their friendly targets while sitting in Blind

### ISSUE THREAD

**Issue by sasadubi** [wowmw/bugtracker#441]
title is self explanatory.

**Comment by Makcumys** [comment]
Боп пладина.
1. Можно использовать на себя во время стана, ошеломления, фира (только если сс физической школы). Фир вара, сап рога.
2. Нельзя использовать на тиммейтов находясь в сс. Только на себя, и только если п.1
3. Можно использовать на тиммейта, если сам паладин не в сс. При этом тиммейт может находится в сс и боп снимает cc,  если он физической школы).

**Comment by sasadubi** [comment]
Not sure if you understood what bug here is:
So, Im rogue in battleground and I attack holy paladin and rogue. I attack rogue, he is low, I blind paladin, then paladin BoP's his rogue but remains in blind. So he does it from the Blind and Blind doesn't break neither.

**Comment by Makcumys** [comment]
> Not sure if you understood what bug here is: So, Im rogue in battleground and I attack holy paladin and rogue. I attack rogue, he is low, I blind paladin, then paladin BoP's his rogue but remains in blind. So he does it from the Blind and Blind doesn't break neither.

Just the same, I understand the whole essence of the above, and for the developer I described how the bop spell should be used with crowd control and without it on myself and on the teammate.

**Comment by Makcumys** [comment]
> Not sure if you understood what bug here is: So, Im rogue in battleground and I attack holy paladin and rogue. I attack rogue, he is low, I blind paladin, then paladin BoP's his rogue but remains in blind. So he does it from the Blind and Blind doesn't break neither.

Just the same, I understand the whole essence of the above, and for the developer I described how the bop spell should be used with crowd control and without it on myself and on the teammate
