### ISSUE TITLE
Баг выдаёт ошибку выкидывает с игры 

### ISSUE THREAD

**Issue by Sometimess99** [wowmw/bugtracker#442]
в вершине чёрной горы когда подбегаешь к жнецам в центре где их 4 стоит выдаёт ошибку и выкидывает с игры ! 
![WoWScrnShot_011223_154038](https://user-images.githubusercontent.com/122534914/212069121-9a2e2ea9-549b-43b6-9f6a-77395e632d41.jpg)

вот на этом месте как к ним подбегаешь начинаешь бить сразу ошибка ! и откат

**Comment by Dmitriyres** [comment]
Проблема в вашем клиенте. Возможно Розрыв каких то файлов.
