### ISSUE TITLE
Quest 

### ISSUE THREAD

**Issue by bobi966** [wowmw/bugtracker#443]
[Tooga's Quest] Quest in tanaris to escort turtle . Turtle follow me right to 20-21 min then turtle FLY and Q was FAILED !!

**Comment by Gensen1** [comment]
@Makcumys @Dmitriyres @kuzinsun check it, please.

**Comment by Makcumys** [comment]
@Gensen1 провёл через весь танарис. Даже отвлекаясь на агрессивных нпц, при их убийстве черепаха корректно возвращается. В данном квесте её нужно вести, т.е. она следует за игроком. После 20 минуты черепаха никуда не уходит.
Всё работает корректно. Правда пришлось отключить аддоны, т.к. какой-то конфликтует в этом квесте. Без аддонов сделал без проблем. Скриншот прилагаю
![WoWScrnShot_012023_203517](https://user-images.githubusercontent.com/120413127/213779517-f220856a-6360-40e0-9d95-0430ed2714fc.jpg)

**Comment by kuzinsun** [comment]
![image](https://user-images.githubusercontent.com/60097141/213787574-d4e8151d-e032-4c23-a6bf-84c567e56f2c.png)
@Gensen1 Quest is working fine. Turtle followed the character, entered in battle with another NPC's and correctly exited it and started following again.
