### ISSUE TITLE
Отсутствие почтового ящика

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#446]
В Стальгорне (IF) Отсутствует Почтовый ящик.
![image](https://user-images.githubusercontent.com/114337602/212279745-6e366c6b-55fe-464f-8009-2d43b0f52213.png)
Фото прикрепляю.
https://www.wowhead.com/tbc/ru/object=32349/%D0%BF%D0%BE%D1%87%D1%82%D0%BE%D0%B2%D1%8B%D0%B9-%D1%8F%D1%89%D0%B8%D0%BA#comments

**Comment by kuzinsun** [comment]
Ящик будет добавлен в ближайшей обновлении.
