### ISSUE TITLE
Прок крусейдера дает 100 АП, вместо 100 силы

### ISSUE THREAD

**Issue by zlobinilya1998** [wowmw/bugtracker#453]
![изображение](https://user-images.githubusercontent.com/65910295/212461830-6ecff110-4e5f-45e0-8861-a109be15d5b5.png)

**Comment by kuzinsun** [comment]
Доброго времени суток!

Работает корректно, дает 100 силы на персонаже 60 уровня. (проверено на войне - прибавилось 200 АП)
На персонаже какого уровня проверялось?
Крусейдер это инчант для 60лвл. На 60+ с каждым левелом дает меньше силы.
