### ISSUE TITLE
NPC Ranger Lilatha (entry=16295)

### ISSUE THREAD

**Issue by Russaooo** [wowmw/bugtracker#455]
https://www.wowhead.com/tbc/npc=16295/ranger-lilatha
Время респавна данного нпс в мире х5 очень долгое, более 10 минут.

**Comment by kuzinsun** [comment]
Проверил. NPC респавнится 5 мин (300сек). Судя по комментам на вовхеде время респа должно быть не менее 5 мин. 

@Gensen1 просьба проверить в "боевой" базе. Если spawntimesecs 300, то все все хорошо.
