### ISSUE TITLE
Узилище. Весь инст в бою!

### ISSUE THREAD

**Issue by XandrKhv** [wowmw/bugtracker#465]
Вступив в бой однажды, остаёшься в нём навсегда.
Пробовал выйти из инста, вышел из боя.
Зашёл заново, новый пак и опять та-же самая история.
Вся группа шла весь инст в бою, без возможности поесть и попить, это просто жесть!

небольшое видео из инста
https://youtu.be/A4CG1UvJJ_8

**Comment by Dmitriyres** [comment]
Возможно у вас застрял где то NPC В текстурах и за этого комбат. Нужно знать точное место застревания будет проверятся.
