### ISSUE TITLE
Зыбун (Босс в Узилище)

### ISSUE THREAD

**Issue by XandrKhv** [wowmw/bugtracker#467]
Босс нереально большой (по размерам). В оригинале он меньше.
Помимо этого в оригинале он изначально находится под водой.

**Comment by Dmitriyres** [comment]
> Босс нереально большой (по размерам). В оригинале он меньше. Помимо этого в оригинале он изначально находится под водой.

Размер стоит оригинальный. Позиция будет расмотрена.
