### ISSUE TITLE
Малая волна заклинания

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#479]
https://db.moonwell.su/?spell=32106 - сам спелл. Бонус от комплекта https://db.moonwell.su/?itemset=559
"При успешной атаке вашим боевым заклинанием"
Не распространяется на заклинания, наносящие периодический урон (доты). 
Должен распространятся на доты.
Именно "доты" (бинарные заклинания не трогать).

**Comment by kuzinsun** [comment]
@Makcumys приветствую! На других спелах срабатывает? Аура/бафф накладывается?

**Comment by Makcumys** [comment]
@kuzinsun @Gensen1  https://github.com/wowmw/bugtracker/issues/482
Там всё очень сложно. В доказательство было одно весьма сомнительное видео, где якобы от минд флая приста прок сработал. Единственное видео в ютубе.
Комментарии с вовхеда так же от игроков, которые пишут что срабатывает от наложения дот.
Нет прямых доказательств.
Моё предположение касательно бинарности имеет место быть, т.к. не срабатывает на таких видах заклинаний.
1. Срабатывает на всех заклинаниях прямого урона.
2. Не срабатывает при наложении дот, заклинаний наносящих непрямой урон (в том числе бинарные).
3. "При успешной атаке вашим боевым заклинанием" - должен ли относится п.2 сюда или нет, вам предстоит решить самим.
Я скинул доп инфу Генсену.

**Comment by kuzinsun** [comment]
https://github.com/wowmw/bugtracker/issues/482 @Gensen1  сюда же я так понимаю

**Comment by kuzinsun** [comment]
https://www.youtube.com/watch?v=vBVXnRDtlTE&ab_channel=Xposed
это TBC classic - на присте одет этот сет.

0:55 - четко видно что - на мобе висят доты и прист использует Mind Flay и прокает бонус.
По поводу бинарности не скажу, факт остается в том, что судя по описанию + той информации, что я нашел - баф должен наклдываться при "your harmful spells LAND". Скорее всего под этим нужно понимать каст + хит (первое столкновение заклинания и цели, первый тик)

Вывод: 
Должно прокать от любого урона - прямой + первый тик от ченелинг или доты. При этом прокать должно достаточно часто. (на видео прокает через одного моба)

Постараюсь вечером проверить у себя на стенде.

**Comment by SecurityDetachment** [comment]
https://github.com/wowmw/bugtracker/issues/482
