### ISSUE TITLE
Комбат не спадает сразу после боя

### ISSUE THREAD

**Issue by XandrKhv** [wowmw/bugtracker#498]
Комбат висит еще какое-то время (несколько секунд) после смерти последнего моба.
Хотя он должен спадать сразу после его смерти. Возможность отпиваться должна появляться сразу после смерти последнего заагреного моба!

**Comment by Gensen1** [comment]
Комбат спадает сразу после убийства мобов. Приведите примеры где, и при каких условиях воспроизводится баг.
