### ISSUE TITLE
Кильдар <Учитель верховой езды>

### ISSUE THREAD

**Issue by mikeevstropov** [wowmw/bugtracker#500]
Андед с Превознесением в Оргриммаре не может взаимодействовать с Кильдар <Учитель верховой езды> - не открывается диалоговое окно для изучения навыка верховой езды в Аллее Чести. Вероятно, что рабочий вариант - только рассовый учитель.

**Comment by Dmitriyres** [comment]
Обучает только расовый учитель. В 4 фазе открывается для всех
