### ISSUE TITLE
Zereketh the Unbound - босс подземелья Arcatraz

### ISSUE THREAD

**Issue by Russaooo** [wowmw/bugtracker#506]
Сущность Unbound Void Zone [NPC entry = 21101](https://www.wowhead.com/tbc/npc=21101/unbound-void-zone), призываемая заклинанием Void Zone [spellid = 36119](https://www.wowhead.com/tbc/spell=36119/void-zone) не фиксирована после спавна на месте, что в корне нарушает механику энкаунтера Zereketh the Unbound [ссылка на npc](https://www.wowhead.com/tbc/npc=20870/)

Как должно быть: [Youtube](https://www.youtube.com/watch?v=d0d8vyK5IdM) снято 15 лет назад

**Comment by Hentaika** [comment]
https://github.com/wowmw/bugtracker/issues/391
Уже есть репорт

**Comment by Russaooo** [comment]
за месяц не пофиксили...беда
