### ISSUE TITLE
1

### ISSUE THREAD

**Issue by A4our** [wowmw/bugtracker#511]
1

**Comment by Gensen1** [comment]
Здравствуйте. Почему удалили тему?

**Comment by A4our** [comment]
Добрый день, не знал название квеста и предмета, хотел сходить посмотреть
чтоб дать точную информацию, да и подумал потом стоит ли оглашать это для
всех.
Могу здесь описать способ эксплойта или тикет написать?

чт, 2 февр. 2023 г. в 23:27, Gensen ***@***.***>:

**Comment by A4our** [comment]
Эсксплойт связан с бесконечным спамом каждые 2 секунды мобов и фармом с них
кожи Rugged Leather и остальных предметов

пт, 3 февр. 2023 г. в 17:46, Миротворец ***@***.***>:

**Comment by Gensen1** [comment]
Напишите в тикет.

**Comment by Dmitriyres** [comment]
Ответ был дан в тикете и в новом багрепорте.
