### ISSUE TITLE
The End of the Deserters - 11134

### ISSUE THREAD

**Issue by Tyrvana** [wowmw/bugtracker#512]
Quest does not give completion credit upon the NPC disappearing (captured)/dealing damage below threshold becoming friendly.
https://www.wowhead.com/tbc/quest=11134/the-end-of-the-deserters

**Comment by Dmitriyres** [comment]
More info about fix this quest here <3 ^

**Comment by Tyrvana** [comment]
I'm not sure what additional information there would be since the description is exactly what happens/how its supposed to work.
