### ISSUE TITLE
Не правильно работает талант у друида в ветке баланс

### ISSUE THREAD

**Issue by Jeyson64** [wowmw/bugtracker#514]
Талант https://www.wowhead.com/tbc/spell=16880/natures-grace
Талант срабатывает на крит атаки в форме медведя и в форме кошки.

**Comment by Dmitriyres** [comment]
Будет рассмотрено.

**Comment by kuzinsun** [comment]
Поправил. Изменения будут добавлены с ближайшим обновлением.

@Jeyson64 Благодарим за информацию.
