### ISSUE TITLE
Эксплойт по фарму мобов

### ISSUE THREAD

**Issue by A4our** [wowmw/bugtracker#515]
В локации Western Plagues, имеется квест A matter of time (Вопрос времени) в котором выдается квестовый предмет Temporal Displacer, при помощи которого можно бесконечно спамить мобов и снимать с них кожу (Rugged Leather)

**Comment by Gensen1** [comment]
Здравствуйте. Напишите свой ник для начисления коинов.

**Comment by A4our** [comment]
Gunzel

пн, 13 февр. 2023 г., 03:23 Gensen ***@***.***>:
