### ISSUE TITLE
Пересмотреть Промахи в ПВП

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#516]
Имея кап меткости(хита) для пвп а именно 5% для физ дд(милишника) игроки часто промахиваются
Даже если собрать больше всё ровно промахиваешься по персонажу
(Нужно пересмотреть) этот показатель*

**Comment by SecurityDetachment** [comment]
Проверял в тикете лично, да, работает некорректно. Пруф https://wowwiki-archive.fandom.com/wiki/Hit?oldid=1626266

**Comment by Gensen1** [comment]
5% это базовый шанс промаха, но еще есть показатель Defence rating, который дополнительно понижает шанс попадания.

https://www.wowhead.com/forums/topic/defense-rating-in-pvp-67949
