### ISSUE TITLE
Заклинание Presence of Mind

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#518]
При Одетому комплекте 4х вещей из сета т4 мага
способность ->https://www.wowhead.com/classic/spell=12043/presence-of-mind
После своего первого применения не угодит на Кд( а остаётся в своём изначальном виде как будто её не применяли)
Проблема активна только когда одето 4 вещи из сета. Без сета исправно.

**Comment by Gensen1** [comment]
Не воспроизводится
1) надел сет https://db.moonwell.su/?item=29077
2) юзнул  [Presence of Mind]
3) появился баф, отменил - спелл ушел на КД

**Comment by Dmitriyres** [comment]
> * надел сет https://db.moonwell.su/?item=29077
> * юзнул  [Presence of Mind]
> * появился баф, отменил - спелл ушел на КД

Порядок что бы воизвести :
1.надел сет https://db.moonwell.su/?item=29077
2.юзнул [Presence of Mind]
3.появился баф
4.Используй спел (фростболт или другой что бы заклинание ушло на кд)
