### ISSUE TITLE
Баг на аукционе

### ISSUE THREAD

**Issue by Reback21** [wowmw/bugtracker#522]
При покупке на аукционе 1 шт. Адамантитовые латные перчатки с чаркой +5 к силе, пришли еще такие же 1 шт. только уже без чарки.
![image](https://user-images.githubusercontent.com/124460384/216782951-0c4189aa-bd9d-44e6-9102-b3812e972d40.png)
![image](https://user-images.githubusercontent.com/124460384/216782960-b70561df-51b0-4c79-922a-0b2cd33433db.png)

**Comment by Reback21** [comment]
#items

**Comment by Russaooo** [comment]
У вас изготовители предмета разные. Вы походу две перчатки выкупили

**Comment by Gensen1** [comment]
> У вас изготовители предмета разные. Вы походу две перчатки выкупили

Так и есть.
