### ISSUE TITLE
Dissapearing Gold vein

### ISSUE THREAD

**Issue by Tony9898A** [wowmw/bugtracker#531]
Hello there, I found the gold vain in Growless cave (37,66) in Alterac mountains. I can see it from the distance, but when I come closer it disappear. Can you please check if it is bugged vain? Thanks :)

![WoWScrnShot_020523_193051](https://user-images.githubusercontent.com/123499949/216838505-b76f8be5-ead0-4302-a0de-c64d58364555.jpg)

![WoWScrnShot_020523_193058](https://user-images.githubusercontent.com/123499949/216838512-9ffcd30d-af06-4dae-b360-f0a52ef32d0f.jpg)

**Comment by Dmitriyres** [comment]
Problem with Geodate. Im test this and we fix this :)

**Comment by Dmitriyres** [comment]
> Hello there, I found the gold vain in Growless cave (37,66) in Alterac mountains. I can see it from the distance, but when I come closer it disappear. Can you please check if it is bugged vain? Thanks :)
> 
> ![WoWScrnShot_020523_193051](https://user-images.githubusercontent.com/123499949/216838505-b76f8be5-ead0-4302-a0de-c64d58364555.jpg)
> 
> ![WoWScrnShot_020523_193058](https://user-images.githubusercontent.com/123499949/216838512-9ffcd30d-af06-4dae-b360-f0a52ef32d0f.jpg)

Problem with Geodate. Im test this and we fix this :)
