### ISSUE TITLE
Assassination Plot Thousand Needles

### ISSUE THREAD

**Issue by razorslack** [wowmw/bugtracker#532]
cant speak with npc Kanati greycloud
![WoWScrnShot_020523_183608](https://user-images.githubusercontent.com/121767649/216845252-2f79ec85-316a-4c3f-a3a2-abe9f5058ecf.jpg)
![WoWScrnShot_020523_183633](https://user-images.githubusercontent.com/121767649/216845255-6a930ff6-8f63-47ee-8f85-8cc96a0bf75f.jpg)

**Comment by Dmitriyres** [comment]
Log in disc and use #support for GMs respawn this NPC <3 Thx

**Comment by Dmitriyres** [comment]
> cant speak with npc Kanati greycloud ![WoWScrnShot_020523_183608](https://user-images.githubusercontent.com/121767649/216845252-2f79ec85-316a-4c3f-a3a2-abe9f5058ecf.jpg) ![WoWScrnShot_020523_183633](https://user-images.githubusercontent.com/121767649/216845255-6a930ff6-8f63-47ee-8f85-8cc96a0bf75f.jpg)

^
