### ISSUE TITLE
Astral Flare

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#535]
При вступление с 6тым боссом каражана . 
Куратор ID 15691
Босс во время боя призывает прислужников 
Astral Flare -> ID 17096
Эти прислужники подходя к колонам застревают её нельзя быть/вывести и т.д
![image](https://user-images.githubusercontent.com/114337602/217018880-b8d6aa13-5efe-4656-b663-e7168e301dbb.png)
![image](https://user-images.githubusercontent.com/114337602/217019021-706c9601-a389-4fde-929b-072426df690f.png)
![image](https://user-images.githubusercontent.com/114337602/217019062-a0457ac9-a222-4609-958e-33222224502a.png)
Предполагаю так и со всеми колонами если их забагать.

**Comment by Russaooo** [comment]
Аое урон от Blizzard по таким мобам проходит. Аналогичный баг есть в Паровом на колоннах 1 этажа

**Comment by Gensen1** [comment]
Проверил - мобы не застревают. Недавно был апдейт по геодате, наверное, исправилось.
