### ISSUE TITLE
Каражан

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#536]
NPC проваливается в текстурах
![image](https://user-images.githubusercontent.com/114337602/217029253-66baa19c-4541-427d-b887-a5d361b1769e.png)

**Comment by Dmitriyres** [comment]
Ещё 1 место. 
![image](https://user-images.githubusercontent.com/114337602/217259513-1f20b596-48c0-4330-a0a1-0288e47a8888.png)

**Comment by Gensen1** [comment]
Сагрил на себя пачку, побегал в этих местах и никто не провалился. Недавно был апдейт по геодате, наверное, исправилось.
