### ISSUE TITLE
Timbermaw Hold, Kernda no interaction

### ISSUE THREAD

**Issue by kevszin** [wowmw/bugtracker#545]
Quests: Deadwood Ritual Totem, Winterfall Ritual Totem 

I was trying to speak with Kendra in the Timbermaw cave after I made enough reputation with them. The quest requires neutral, I am now friendly with them but still can't speak to him. ( when I was only neutral, there could first no interaciton, I relogged, then I only could attack them ) I can't even make any interaction with the Timbermaws in their cave neither.

**Comment by kuzinsun** [comment]
Greeting!

it is necessary to turn off the "At war" mode.
It's not bug, dat works normally for this type of faction. (bloodsail, timber and etc)

![image](https://user-images.githubusercontent.com/60097141/217969210-c8c5776f-e981-4317-bc00-70c47ec51871.png)
