### ISSUE TITLE
Маленькие ракеты

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#546]
Изменить требуемый уровень для взятие задания ->
https://www.wowhead.com/tbc/ru/quest=8876/%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B8%D0%B5-%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D1%8B
Npc->https://www.wowhead.com/tbc/ru/npc=15909
![image](https://user-images.githubusercontent.com/114337602/217556896-cd65d187-f909-42b7-8638-a7d86e427272.png)

**Comment by kuzinsun** [comment]
Будет исправлено в ближайшем обновлении.
