### ISSUE TITLE
1ед ловкости, сколько это ап в ренже для охотника? 

### ISSUE THREAD

**Issue by Gorzoth** [wowmw/bugtracker#547]
Ради теста поигрался с вещами на ловку, по итогу в ренже 1агила у вас = 1ап для ренж атак.
Это не критическая ошибка? Как у вас дела ?
Все хорошо? =) Не болеете ?
![1](https://user-images.githubusercontent.com/124702827/217568812-80686264-b421-47cf-9440-f409b6f8be8f.jpg)
![2](https://user-images.githubusercontent.com/124702827/217568830-79d2fcb5-ed25-4724-8ba6-152ab27a54e8.jpg)
![3](https://user-images.githubusercontent.com/124702827/217568846-a8519f2b-953b-4fbe-8398-de2b83b1dcb2.jpg)

**Comment by SecurityDetachment** [comment]
[For the Burning Crusade the formula for AEP as it pertains to Hunters has changed somewhat. This information is based on WOW and has only been partially validated in play.

Formula: 1 Agility = .552 Crit Rating = 1 Attack Power
](https://wowwiki-archive.fandom.com/wiki/Agility_Equivalence_Points?oldid=1496999)

Работает корректно.
