### ISSUE TITLE
Проблема с заданием

### ISSUE THREAD

**Issue by Gorzoth** [wowmw/bugtracker#548]
Задание Нечестивый союз id 6522, оно должно быть с 28 уровня, а с 28 задание нельзя получить.

**Comment by kuzinsun** [comment]
![image](https://user-images.githubusercontent.com/60097141/223230343-9798251f-c45f-4164-9d6f-11764a100712.png)
Баг не подтвержден. Квест берется с помощью предмета https://db.moonwell.su/?item=17008
