### ISSUE TITLE
Ashenvale Horde quest - Warsong Supplies

### ISSUE THREAD

**Issue by 3ntrust** [wowmw/bugtracker#549]
The NPC Warfmaster Lozgil has no quest dialogue options to recieve the shipment of axes thereby stopping the continuation of the quest and then completing it.

**Comment by kuzinsun** [comment]
Greeting! Which quest is meant?

https://db.moonwell.su/?quest=6571
For this quest, you need to loot this box.

https://db.moonwell.su/?quest=1180
For this, need to speak with NPC.

It's works fine. Nothing bugged.
