### ISSUE TITLE
Не падает предмет!

### ISSUE THREAD

**Issue by Gorzoth** [wowmw/bugtracker#552]

**Comment by Gorzoth** [comment]
Нет возможности получить предмет "Белая перфокарта" id 9279 (ссыль на вашу бд, где дроп 100%, но она почему то не падает https://db.moonwell.su/?item=9279 , прошу решить данную проблему.

**Comment by Hentaika** [comment]
> Нет возможности получить предмет "Белая перфокарта" id 9279 (ссыль на вашу бд, где дроп 100%, но она почему то не падает https://db.moonwell.su/?item=9279 , прошу решить данную проблему.

Квест возьми и будет падать.

**Comment by kuzinsun** [comment]
@Gorzoth

https://db.moonwell.su/?quest=2930 предмет падает со 100% вероятностью при условии что взят этот квест.

@Hentaika Благодарю за подсказку.
