### ISSUE TITLE
Astral Flare

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#554]
При вступление с 6тым боссом каражана .
Куратор ID 15691 ->https://www.wowhead.com/tbc/npc=15691
Босс во время боя призывает прислужников
Astral Flare -> ID 17096 ->https://www.wowhead.com/tbc/ru/npc=17096/%D0%B0%D1%81%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BE%D0%B3%D0%BE%D0%BD%D1%8C
Если на Шаме весит способность Water Shield или другой ефект щита он не срабатывает если( моб ударил ) шамана . Хотя в Бафе указано работает при атаке или заклинание 
Water Shield ->https://www.wowhead.com/tbc/spell=33736/water-shield
 [Lightning Shield] -> https://db.moonwell.su/?spell=25472
 Earth Shield ->https://db.moonwell.su/?spell=32594

**Comment by Gensen1** [comment]
Прок щита срабатывает только при прямом уроне. Так же работает и с дотами.
