### ISSUE TITLE
Bug - fake players

### ISSUE THREAD

**Issue by Nightmarenun** [wowmw/bugtracker#556]
Hi there. I find a bug with fake player. I been in orgrimmar center and saw how many fake players with level 62 (they all got 62lvl) Just runing from fly path to durotar and back. Runing same way and all the time. I can see its is some script, so its can be fake online.
Realm x5
My character name - Nightmarenun.

**Comment by Gensen1** [comment]
Hello. Today we banned a lot goldfarmer bots when they were exactly at lvl 62.
![Безымянный](https://user-images.githubusercontent.com/64833670/218281192-b074ed83-cfd1-4b5e-bb2d-0805e9aae4db.png)

We are constantly scanning server for bots. Don't worry.
