### ISSUE TITLE
Предел разрушения (талант Warlock) 

### ISSUE THREAD

**Issue by Geriani** [wowmw/bugtracker#557]
Либо просто неправильное описание в тултипе, либо талант реально неправильно работает. Должен давать увеличенную дистанцию применения и снижение уровня угрозы, в тултипе вместо уровня угрозы написано снижение урона, что вводит в заблуждение.

**Comment by SecurityDetachment** [comment]
У вас русскоязычный клиент, это ошибка локального перевода. Спелл работает корректно.
