### ISSUE TITLE
Стрела тьмы (заклинание Warlock)

### ISSUE THREAD

**Issue by Geriani** [wowmw/bugtracker#558]
Неправильная стоимость заклинания Стрела тьмы 6 уровня (занижена). Если я правильно помню, то 9 серебряных, при этом даже 5 уровень Стрелы тьмы стоил дороже

**Comment by kuzinsun** [comment]
Приветствую!

Цена будет изменена на 90 серебряных монет.
Изменение будет добавлено в ближайшем обновлении.

Спасибо за обращение.
