### ISSUE TITLE
Волхв Забраксис <Реагенты>

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#560]
https://x5.moonwell.su/?npc=16829 - Волхв Забраксис <Реагенты>
Продаёт реагенты, доступен 1 квест (https://x5.moonwell.su/?quest=9494)
Пока квест не выполнен нельзя купить реагенты (нет строки для выбора и покупки)
Когда квест выполнен всё появляется.
Должна быть строка с выбором для покупки реагентов.
![WoWScrnShot_021323_195341](https://user-images.githubusercontent.com/120413127/218534976-7e4a719c-14ee-4add-91c1-290e49b9c08c.jpg)
![WoWScrnShot_021323_195205](https://user-images.githubusercontent.com/120413127/218535063-97a51b05-d1fb-4845-bc01-33e6e4f08070.jpg)

**Comment by kuzinsun** [comment]
FIXED
