### ISSUE TITLE
Воин | Талант Precision/Точность spell=29592

### ISSUE THREAD

**Issue by mikeevstropov** [wowmw/bugtracker#561]
Талант не влияет на шанс нанести урон в ближнем бою в окне характеристик персонажа во вкладке Ближний бой.
1. берем любой уровень таланта, к примеру 3й,
2. открываем окно персонажа,
3. выбираем в характеристиках Ближний бой,
4. наводим на Рейт. меткости и видим:

`Шанс нанести цели урон в ближнем бою увеличен на 0,00%`

**Comment by SecurityDetachment** [comment]
Добрый день, это скрытая аура которая не должна отображаться в характеристиках. Работает корректно, выведена в визуальных баф.
