### ISSUE TITLE
Квест Hidden Enemies  содержит ошибку

### ISSUE THREAD

**Issue by SemionSputnik** [wowmw/bugtracker#580]
Квест [Hidden Enemies](https://www.wowhead.com/classic/quest=5727/) не требует похода к Neeru Fireblade. После взятия квеста у Тралла квест можно сдать моментально. А должен требоваться предварительный разговор с Нииру.

**Comment by Hentaika** [comment]
Я ещё давно в тикет писала об этом баге, но видимо его забыли оформить.

**Comment by kuzinsun** [comment]
Исправил требования для выполнения квеста и немного поправил шанс дропа итема.

**Comment by kuzinsun** [comment]
https://github.com/wowmw/core/pull/14
