### ISSUE TITLE
Каражан

### ISSUE THREAD

**Issue by Dmitriyres** [wowmw/bugtracker#582]
4 Босс Каражана
Эвент -> Страна ОЗ
https://www.wowhead.com/tbc/npc=18168/the-crone#abilities;mode:n10
Сломаны ветерки (которые должны перемещаться по платформе за игроками (на нашем сервере просто стоят в 1 месте)
Касается и гер и об режимов

**Comment by Dmitriyres** [comment]
1 Босс Каражана https://www.wowhead.com/tbc/ru/npc=16152/%D0%BB%D0%BE%D0%B2%D1%87%D0%B8%D0%B9-%D0%B0%D1%82%D1%82%D1%83%D0%BC%D0%B5%D0%BD
Усилить урон (на 2 фазе урон слабее чем на 1) танков почти не бьёт.

**Comment by Dmitriyres** [comment]
8Босс - Аран
https://www.wowhead.com/tbc/npc=16524/shade-of-aran#abilities;mode:n10
Способность не захватывает всю комнату можно спрятаться в проходе и обузить входящий урон(на гер режиме)
https://www.wowhead.com/tbc/spell=29969/summon-blizzard

**Comment by Dmitriyres** [comment]
10 Босс(Игровая Зона) Шахматы(гер)
https://www.wowhead.com/tbc/spell=39343/fury-of-medivh
Способность не наносит урон фигурам.

**Comment by Gensen1** [comment]
Все исправлено, кроме https://www.wowhead.com/tbc/spell=39343/fury-of-medivh - временно отключено, так как нужна другая реализация.
