### ISSUE TITLE
not working quest!!!! The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by flyaka91** [wowmw/bugtracker#584]
The Exorcism of Colonel Jules 
can't interact with NPC after quest start, ritual doesn't start

**Comment by Dmitriyres** [comment]
> The Exorcism of Colonel Jules can't interact with NPC after quest start, ritual doesn't start

work corect . Create ticket in discord -> use suport and wisp for GMs for respawn this npc or wait restart server for done quest
