### ISSUE TITLE
Gladdy fix plz

### ISSUE THREAD

**Issue by tbc123** [wowmw/bugtracker#588]
Здравствуйте есть проблема с конфигурацией аддона Gladdy на вашем сервере а именно при вхождения на арену не видно игроков противника в глади и после открытия ворот тоже их не видно пока они не попадут в ваше поле зрение только после этого появляется игрок в Gladdy прошу обратить внимание на эту ошибку и исправить по возможности

**Comment by Gensen1** [comment]
Здравствуйте. Считаю, что так и должно быть, чтобы сетапы с инвизерами не обнаруживались до опена.

**Comment by tbc123** [comment]
А ну раз считает что так должно быть значит, значит так должно быть kekw)))

**Comment by Gensen1** [comment]
Я специально оставил тему открытой, чтобы услышать контраргументы, а не сарказм.

Информация о сетапе до начала боя может дать преимущество. Для примера возьмем сетап из дабл магов. Если противники будут знать что против них вышли 2 мага, то изначально будут играть сейвово, уменьшая шансы магов на победу. Такой же пример можно привести с любым другим сетапом имеющим инвизеров.

**Comment by tbc123** [comment]
можно настроить глади чтобы не показывал до открытия ворот но как только открылись ворота они должны появится в гладди так всегда работало даже на tbc classic но у вас на сервере он явно работает с ошибками

**Comment by tbc123** [comment]
вот на старом вашем проекте работал гладди правильно он до открытия не показывал противников но как ворота открывались гладди учитывал енеми вот видео доказательство https://www.youtube.com/watch?v=xgPo3y2hnos&ab_channel=SladeWilson

**Comment by tbc123** [comment]
на видео четко показывает что после выхода из стелса противники появляются в глади без никаких проблем а вот у вас оно работает ошибочно

**Comment by Gensen1** [comment]
Видимо раньше было неправильно.

https://youtu.be/jHwYgVHhaVE - здесь видно, что на бк офе друид появляется в гладди только после выхода из стелса.
