### ISSUE TITLE
Выбрасывает из игры при попытке атаковать моба Проклятый Высокорожденный

### ISSUE THREAD

**Issue by Mattye1282** [wowmw/bugtracker#591]
Описание бага:
При попытке атаковать в форме кота монстра [Проклятый высокорождённый](https://www.wowhead.com/classic/ru/npc=2176/проклятый-высокорожденный) выбрасывает из игры с появлением окна: "This application has encountered a critical error: ERROR # 132 (0x85100084) Fatal Exception. Exception: 0x0000005 (ACCESS_VIOLATION) at 0023:00466FE3. The instruction at "0x00466FE3" referenced memory at "0x11F3E208". The memory could not be read".

Воспроизвёл этот баг три раза подряд. 
Шаги:
1. Перекинуться в форму кота;
2. Зайти в локацию "Амет'Аран" на Тёмных берегах;
3. Попытаться в форме кота атаковать Проклятого Высокорожденного (женского пола).

Параметры ПК:
Процессор - Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz   2.40 GHz
ОЗУ - Crucial 2x8 GB
Система - Windows 11 Pro (версия 22H2, сборка 22621.1265).

Скриншот: [https://imgur.com/5f0b5UX](https://imgur.com/5f0b5UX)

**Comment by Dmitriyres** [comment]
Добрый день. О проблеме известно рекомендую пропустить ту местность(и задание связаное с ним)

**Comment by Dmitriyres** [comment]
Больше информации в 311. Обьеденил этот закрываю
