### ISSUE TITLE
Mongoose не прокает от жёлтых атак (только автоатака)

### ISSUE THREAD

**Issue by ugidugi185** [wowmw/bugtracker#595]
https://www.wowhead.com/tbc/ru/item=22559/%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0-%D1%87%D0%B0%D1%80-%D0%B4%D0%BB%D1%8F-%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D1%8F-%D0%BC%D0%B0%D0%BD%D0%B3%D1%83%D1%81%D1%82

https://db.moonwell.su/?item=22559

Данное зачарование срабатывает ТОЛЬКО от белых атак (автоатак). Удары девастейта (devastate https://www.wowhead.com/tbc/ru/spell=30022/%D1%80%D0%B0%D0%B7%D1%80%D1%83%D1%88%D0%B5%D0%BD%D0%B8%D0%B5 ) не триггерят, не прокают это зачарование. Соответственно мангуст срабатывает очень редко. 
Проверил это на манекене, при 700 ударах девастейта 0 проков. Думаю пробелема зачарования мангуст, что оно не прокает вообще ни от каких жёлтых атак.
Все инчанты на оружии и проки ВСЕГДА на всех серверах, включая офф, прокали от девастейта и прочих жёлтых атак.

**Comment by kuzinsun** [comment]
Исправлено.
Изменение будет добавлено в ближайшем обновлении.
