### ISSUE TITLE
Спавн Golden Sansam внутри дерева

### ISSUE THREAD

**Issue by Russaooo** [wowmw/bugtracker#601]
В локации Eastern Plaguelands по координатам (клиент) 55.7 | 64.7 спавн травы Golden Sansam [https://x5.moonwell.su/?object=176583](https://x5.moonwell.su/?object=176583) расположен внутри текстуры дерева, из-за чего недоступен для сбора при помощи професси Травничество [https://x5.moonwell.su/?spell=50301](https://x5.moonwell.su/?spell=50301)
![изображение](https://user-images.githubusercontent.com/20137489/224525406-3fe96a77-c561-48bd-9379-29b39ff86f5d.png)

**Comment by Russaooo** [comment]
@kuzinsun подвиньте тоже, пожалуйста

**Comment by kuzinsun** [comment]
![image](https://user-images.githubusercontent.com/60097141/224543260-b6ad3030-1d17-4d4a-81ef-86b7469e1da0.png)
Готово. Ждите в ближайшем обновлении.
