### ISSUE TITLE
Спавн Mountain Silversage внутри дерева

### ISSUE THREAD

**Issue by Russaooo** [wowmw/bugtracker#602]
В локации Eastern Plaguelands по координатам (клиент) 68.9 | 31.2 спавн травы Mountain Silversage [https://x5.moonwell.su/?object=176586](https://x5.moonwell.su/?object=176586) расположен внутри текстуры дерева, из-за чего недоступен для сбора при помощи професси Травничество [https://x5.moonwell.su/?spell=50301](https://x5.moonwell.su/?spell=50301)
![изображение](https://user-images.githubusercontent.com/20137489/224526173-f0a05e90-82d7-4ff4-b287-f5a699efb455.png)

**Comment by kuzinsun** [comment]
![image](https://user-images.githubusercontent.com/60097141/224541393-b7d8c840-f2b5-4309-a8c3-f1a3b7af8035.png)
Передвинул. Изменение будет добавлено в ближайшем обновлении.
