### ISSUE TITLE
Завышенный дроп Healthy Dragon Scale

### ISSUE THREAD

**Issue by Russaooo** [wowmw/bugtracker#603]
У NPC [Plagued Hatchling](https://x5.moonwell.su/?npc=10678) entry=10678
Cтоит 100% шанс дропа на [Healthy Dragon Scale](https://x5.moonwell.su/?item=13920), а должен быть 20%.
![изображение](https://user-images.githubusercontent.com/20137489/224542027-64d686f3-5266-4b10-8322-9bbcdc8c845d.png)

**Comment by kuzinsun** [comment]
Исправлено. Изменения вступят в силу в следующем обновлении.
