### ISSUE TITLE
WELCOMING THE WOLF SPIRIT IS BROKEN

### ISSUE THREAD

**Issue by ptaluc** [wowmw/bugtracker#614]
The end of this quest in Terrokar is Mulukas. Once you use the incense he is supposed to give you your reward, but instead he goes into a fit and no longer responds - this lasts for a long time. It happens every time someone wants to complete the quest. Please fix. Thanks

**Comment by kuzinsun** [comment]
@ptaluc Hi!

Will be fixed in this->https://github.com/wowmw/bugtracker/issues/392 ticket.
