### ISSUE TITLE
Боевой цыпленок гномов

### ISSUE THREAD

**Issue by Makcumys** [wowmw/bugtracker#616]
https://x5.moonwell.su/?item=10725
При проке накладывает баф https://x5.moonwell.su/?spell=23133
Баф распространяется на группу. При этом 5 человек в группе могут единовременно призвать цыплёнка и при проке https://x5.moonwell.su/?spell=23133 от каждого из этих 5 цыплят, баф должен стакаться. На данный момент заменяет сам себя от другого цыплёнка.
Баф от цыплёнка должен стакаться с бафом от другого цыплёнка.

**Comment by kuzinsun** [comment]
Приветствую!

Есть какая нибудь инфа по поводу того, должен ли он стакаться?
Я найти не смог. По механике (в теории) стакаться не должен. (spell ID 23060)
Применяется ко всей группе корректно. Если появится инфа - переоткройте тикет.
