### ISSUE TITLE
#Баг на бг с наложение страха на другого игрока 

### ISSUE THREAD

**Issue by Sagiittarius** [wowmw/bugtracker#83]
Играл на бг за елема находился на карте ''Низина Арати'' бежал на лесопилку произошла стычка на моего персонажа был наложен страх от лока возле пенька большого  #провалился под текстуры!!
Есть два скриншота!
![WoWScrnShot_101020_150547](https://user-images.githubusercontent.com/75760653/101698448-879c5700-3a8a-11eb-86c7-a08de9936611.jpg)
![WoWScrnShot_101020_150549](https://user-images.githubusercontent.com/75760653/101698450-88cd8400-3a8a-11eb-82d8-66c7a24a6409.jpg)

**Comment by Gensen1** [comment]
Такое иногда случается. Полагаю, что очень редко. Такая геодата...

**Comment by Sagiittarius** [comment]
Ну я просто сообщил вам о таком баге=)
