### ISSUE TITLE
Подымаемся почти на что угодно.

### ISSUE THREAD

**Issue by Redbyll** [wowmw/bugtracker#87]
Играя на бг - варсонг магом - Magewtf стоя у снизу у респа я получил одно времено маинд контроль от приста и в это время ко мне сделал чардж вар, после сразу я нажал блинк и уже бегал по всем горам где есть хоть малой уклон. 
![WoWScrnShot_051420_173856](https://user-images.githubusercontent.com/76531698/103023622-fb446680-4556-11eb-8a12-716463e59f09.jpg)
![WoWScrnShot_051420_174015](https://user-images.githubusercontent.com/76531698/103023627-fc759380-4556-11eb-8493-a739e3cd2795.jpg)
![WoWScrnShot_051420_174348](https://user-images.githubusercontent.com/76531698/103023629-fd0e2a00-4556-11eb-8806-efac9fb1feb7.jpg)

**Comment by Gensen1** [comment]
Был баг на старом х100. Уже неактуально.
