### ISSUE TITLE
Баг, Ущелье песни войны.

### ISSUE THREAD

**Issue by Vasmsag** [wowmw/bugtracker#93]
Играл бг, случайно наткнулся на этот легальный вх (просмотр стен). Этот баг дает преимущество в сражении, т.к будет известно сколько человек в "кишке". Играл на других сервах, там такого не было. Надеюсь на поощрение с вашей стороны)
![ау](https://user-images.githubusercontent.com/76851374/103445924-a73e2e00-4c8a-11eb-948a-85a6ff140972.jpg)
![а](https://user-images.githubusercontent.com/76851374/103445932-bd4bee80-4c8a-11eb-8c0a-8565b3c245ae.jpg)

**Comment by Gensen1** [comment]
Баг клиента.
