### ISSUE TITLE
rep the Consortium in mana tombs

### ISSUE THREAD

**Issue by lawltoxd** [wowmw/bugtracker#94]
hello as you know after killing thrash or boss in mana tombs you will earn reputation of the consortium but... take look this please
[bandicam 2021-01-07 04-42-55-704.zip](https://github.com/wowmw/bugtracker/files/5778966/bandicam.2021-01-07.04-42-55-704.zip)
 if you fix this please give my coins to character "Lawltoxd" thank you

**Comment by Dmitriyres** [comment]
> hello as you know after killing thrash or boss in mana tombs you will earn reputation of the consortium but... take look this please [bandicam 2021-01-07 04-42-55-704.zip](https://github.com/wowmw/bugtracker/files/5778966/bandicam.2021-01-07.04-42-55-704.zip) if you fix this please give my coins to character "Lawltoxd" thank you

Hoola already Check ur Bugreport after 6k rep 
![image](https://user-images.githubusercontent.com/114337602/193594294-7e158132-1b19-4342-9bef-772cf67c2949.png)
 u cant farm rep in normal mode->run heroic mode for continue rep farm. 
 Work corect on this server . Thx if u find another Bug post here.
