### ISSUE TITLE
Обман в трейде

### ISSUE THREAD

**Issue by BeyfonGG** [wowmw/bugtracker#96]
Продавал 61 баджик по 30 гольды каждый в сумме за 1830 гольды. Мне кинули трейд положили в трейд окно полную сумму 1830 золота. Я убедился в правильности суммы. Положил свои баджики. и подтвердил обмен. сделка состоялась мои баджи ушли а в замен пришло не 1830 гольды а 183. сумма во время подтверждения была верной иначе я бы просто не подтвердил трейд. ник игрока с которым я торговал "Женщинаа" каким образом он смог убрать ноль в конце суммы когда его окно горело зеленым то есть он уже нажал подтверждение я понятия не имею.

**Comment by Gensen1** [comment]
Просто быстро изменяют сумму, потом подтверждают.
