### ISSUE TITLE
Моб "Зверь Пустоты"

### ISSUE THREAD

**Issue by Saferin34** [wowmw/bugtracker#97]
Данный моб находится в Пустоверти. Но также он каким то образом находится на полуострове адского пламени, в локации "Лощина смерти скверны", он там находится не должен. Он не бьётся, не атакует, также пропадает, и спавнится до 6 штук. Прошу пофиксить этот баг . Ник в игре - Мейкан

**Comment by Dmitriyres** [comment]
> Данный моб находится в Пустоверти. Но также он каким то образом находится на полуострове адского пламени, в локации "Лощина смерти скверны", он там находится не должен. Он не бьётся, не атакует, также пропадает, и спавнится до 6 штук. Прошу пофиксить этот баг . Ник в игре - Мейкан

Добрый день . Проверяю ваш Баг отчёт . Спасибо . Ожидайте

**Comment by Dmitriyres** [comment]
Данный тип NPC Отсутсвует. Закрываю ваш баг отчёт . Спасибо. В след раз присылайте фото это поможет и ускорит поиск. Спасибо
